/*
 * Copyright (C) 2008 NHN Corporation
 * Copyright (C) 2008 CUBRID Co., Ltd.
 *
 * env_str_def.h - 
 */

#ifndef _ENV_STR_DEF_H_
#define _ENV_STR_DEF_H_

#ident "$Id$"

#define UNIWEB_DOC_ROOT_ENV_STR		"UNIWEB_DOC_ROOT"
#define VISION3_APPL_ROOT_ENV_STR	"VISION3_APPL_ROOT"
#define APPL_ROOT_ENV_STR		"APPL_ROOT"
#define VISION3_EXE_ROOT_ENV_STR        "VISION3_EXE_ROOT"
#define UNIWEB_EXE_ROOT_ENV_STR         "UNIWEB_EXE_ROOT"
#define VISION3_UPLOAD_ROOT_ENV_STR     "VISION3_UPLOAD_ROOT"
#define UNIWEB_UPLOAD_ROOT_ENV_STR      "UNIWEB_UPLOAD_ROOT"
#define PORT_NUMBER_ENV_STR             "UTS_PORT"
#define APPL_NAME_ENV_STR               "APPL_NAME"
#define MASTER_SHM_KEY_ENV_STR		"MASTER_SHM_KEY"
#define APPL_SERVER_SHM_KEY_STR		"APPL_SERVER_SHM_KEY"
#define ACCESS_LOG_ENV_STR		"ACCESS_LOG_FILE"
#define ERROR_LOG_ENV_STR		"ERROR_LOG_FILE"
#define PORT_NAME_ENV_STR		"UW_PORT_NAME"

#define SID_ENV_STR			"UW_SID"
#define PATH_INFO_ENV_STR		"PATH_INFO"
#define REQUEST_METHOD_ENV_STR		"REQUEST_METHOD"
#define CONTENT_LENGTH_ENV_STR		"CONTENT_LENGTH"
#define DELIMITER_ENV_STR		"DELIMITER"
#define OUT_FILE_NAME_ENV_STR		"OUT_FILE_NAME"
#define CLT_APPL_NAME_ENV_STR		"CLT_APPL_NAME"
#define SESSION_REQUEST_ENV_STR		"SESSION_REQUEST"
#define QUERY_STRING_ENV_STR		"QUERY_STRING"

#define REMOTE_ADDR_ENV_STR		"REMOTE_ADDR"

#define ERROR_LOG_LOCK_FILE_ENV_STR	"ERROR_LOG_LOCK_FILE"

#define AS_PORT_STR_SIZE		512

#endif /* _ENV_STR_DEF_H_ */
