/*
 * Copyright (C) 2008 Search Solution Corporation. All rights reserved by Search Solution. 
 *
 * Redistribution and use in source and binary forms, with or without modification, 
 * are permitted provided that the following conditions are met: 
 *
 * - Redistributions of source code must retain the above copyright notice, 
 *   this list of conditions and the following disclaimer. 
 *
 * - Redistributions in binary form must reproduce the above copyright notice, 
 *   this list of conditions and the following disclaimer in the documentation 
 *   and/or other materials provided with the distribution. 
 *
 * - Neither the name of the <ORGANIZATION> nor the names of its contributors 
 *   may be used to endorse or promote products derived from this software without 
 *   specific prior written permission. 
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, 
 * OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY 
 * OF SUCH DAMAGE. 
 *
 */

package cubridmanager.query;

/**
 * This class contains the perl syntax keywords
 */
public class QuerySyntax {
	public static final String[] KEYWORDS = { "ABS", "ABSOLUTE", "ACTION",
			"ADD", "ADD_MONTHS", "AFTER", "ALIAS", "ALL", "ALLOCATE", "ALTER",
			"AND", "ANY", "ARE", "AS", "ASC", "ASSERTION", "ASYNC", "AT",
			"ATTACH", "ATTRIBUTE", "AUDIT", "AUTHORIZATION", "AVG", "BEFORE",
			"BEGIN", "BETWEEN", "BIT", "BIT_LENGTH", "BOOLEAN", "BOTH",
			"BREADTH", "BY", "CALL", "CASCADE", "CASCADED", "CASE", "CAST",
			"CATALOG", "CEIL", "CHANGE", "CHAR", "CHARACTER",
			"CHARACTER_LENGTH", "CHAR_LENGTH", "CHECK", "CHR", "CLASS",
			"CLASSES", "CLOSE", "CLUSTER", "COALESCE", "COLLATE", "COLLATION",
			"COLUMN", "COMMIT", "COMPLETION", "CONNECT", "CONNECTION",
			"CONSTRAINT", "CONSTRAINTS", "CONTINUE", "CONVERT",
			"CORRESPONDING", "COUNT", "CREATE", "CROSS", "CURRENT",
			"CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP",
			"CURRENT_USER", "CURRENT_VALUE", "CURRVAL", "CURSOR", "CYCLE",
			"DATA", "DATA_TYPE___", "DATE", "DAY", "DEALLOCATE", "DEC",
			"DECIMAL", "DECLARE", "DECODE", "DEFAULT", "DEFERRABLE",
			"DEFERRED", "DELETE", "DEPTH", "DESC", "DESCRIBE", "DESCRIPTOR",
			"DIAGNOSTICS", "DICTIONARY", "DIFFERENCE", "DISCONNECT",
			"DISTINCT", "DOMAIN", "DOUBLE", "DROP", "EACH", "ELSE", "ELSEIF",
			"END", "EQUALS", "ESCAPE", "EVALUATE", "EXCEPT", "EXCEPTION",
			"EXCLUDE", "EXEC", "EXECUTE", "EXISTS", "EXTERNAL", "EXTRACT",
			"FALSE", "FETCH", "FILE", "FIRST", "FLOAT", "FLOOR", "FOR",
			"FOREIGN", "FOUND", "FROM", "FULL", "FUNCTION", "GENERAL", "GET",
			"GE_INF", "GE_LE", "GE_LT", "GLOBAL", "GO", "GOTO", "GRANT",
			"GREATEST", "GROUP", "GROUPBY_NUM", "GT_INF", "GT_LE", "GT_LT",
			"HAVING", "HOUR", "IDENTITY", "IF", "IGNORE", "IMMEDIATE", "IN",
			"INCREMENT", "INDEX", "INDICATOR", "INF_LE", "INF_LT", "INHERIT",
			"INITIALLY", "INNER", "INOUT", "INPUT", "INSERT", "INSTR",
			"INSTRB", "INST_NUM", "INT", "INTEGER", "INTERSECT",
			"INTERSECTION", "INTERVAL", "INTO", "IS", "ISOLATION", "JOIN",
			"KEY", "LANGUAGE", "LAST", "LAST_DAY", "LDB", "LEADING", "LEAST",
			"LEAVE", "LEFT", "LENGTH", "LENGTHB", "LESS", "LEVEL", "LIKE",
			"LIMIT", "LIST", "LOCAL", "LOCAL_TRANSACTION_ID", "LOOP", "LOWER",
			"LPAD", "LTRIM", "MATCH", "MAX", "MAXVALUE", "METHOD", "MIN",
			"MINUTE", "MINVALUE", "MODIFY", "MODULE", "MOD", "MONETARY",
			"MONTH", "MONTHS_BETWEEN", "MULTISET", "MULTISET_OF", "NA",
			"NAMES", "NATIONAL", "NATURAL", "NCHAR", "NEXT", "NEXT_VALUE",
			"NEXTVAL", "NO", "NOCYCLE", "NOMAXVALUE", "NOMINVALUE", "NONE",
			"NOT", "NULL", "NULLIF", "NUMERIC", "NVL", "NVL2", "OBJECT",
			"OCTET_LENGTH", "OF", "OFF", "OID", "ON", "ONLY", "OPEN",
			"OPERATION", "OPERATORS", "OPTIMIZATION", "OPTION", "OR", "ORDER",
			"ORDERBY_NUM", "OTHERS", "OUT", "OUTER", "OUTPUT", "OVERLAPS",
			"PARAMETERS", "PARTIAL", "PENDANT", "POSITION", "POWER",
			"PRECISION", "PREORDER", "PREPARE", "PRESERVE", "PRIMARY", "PRIOR",
			"PRIVATE", "PRIVILEGES", "PROXY", "PROCEDURE", "PROTECTED",
			"QUERY", "READ", "REAL", "RECURSIVE", "REF", "REFERENCES",
			"REFERENCING", "REGISTER", "RELATIVE", "RENAME", "REPLACE",
			"RESIGNAL", "RESTRICT", "RETURN", "RETURNS", "REVOKE", "RIGHT",
			"ROLE", "ROLLBACK", "ROUND", "ROUTINE", "ROW", "ROWNUM", "ROWS",
			"RPAD", "RTRIM", "SAVEPOINT", "SCHEMA", "SCOPE___", "SCROLL",
			"SEARCH", "SECOND", "SECTION", "SELECT", "SENSITIVE", "SEQUENCE",
			"SEQUENCE_OF", "SERIAL", "SERIALIZABLE", "SESSION", "SESSION_USER",
			"SET", "SETEQ", "SETNEQ", "SET_OF", "SHARED", "SHORT", "SIGN",
			"SIGNAL", "SIMILAR", "SIZE", "SMALLINT", "SOME", "SQL", "SQLCODE",
			"SQLERROR", "SQLEXCEPTION", "SQLSTATE", "SQLWARNING", "START",
			"STATISTICS", "STDDEV", "STRING", "STRUCTURE", "SUBCLASS",
			"SUBSET", "SUBSETEQ", "SUBSTR", "SUBSTRB", "SUBSTRING", "SUM",
			"SUPERCLASS", "SUPERSET", "SUPERSETEQ", "SYSTEM", "SYSTEM_USER",
			"SYS_DATE", "SYS_TIME", "SYS_TIMESTAMP", "SYSDATE", "SYSTIME",
			"SYSTIMESTAMP", "SYS_USER", "TABLE", "TEMPORARY", "TEST", "THEN",
			"THERE", "TIME", "TIMESTAMP", "TIMEZONE_HOUR", "TIMEZONE_MINUTE",
			"TO", "TO_CHAR", "TO_DATE", "TO_NUMBER", "TO_TIME", "TO_TIMESTAMP",
			"TRAILING", "TRANSACTION", "TRANSLATE", "TRANSLATION", "TRIGGER",
			"TRIM", "TRUE", "TRUNC", "TYPE", "UNDER", "UNION", "UNIQUE",
			"UNKNOWN", "UPDATE", "UPPER", "USAGE", "USE", "USER", "USING",
			"UTIME", "VALUE", "VALUES", "VARCHAR", "VARIABLE", "VARIANCE",
			"VARYING", "VCLASS", "VIEW", "VIRTUAL", "VISIBLE", "WAIT", "WHEN",
			"WHENEVER", "WHERE", "WHILE", "WITH", "WITHOUT", "WORK", "WRITE",
			"YEAR", "ZONE" };
}
