/*
 * Copyright 2008 Search Solution Corporation
 * Copyright 2016 CUBRID Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */


/*
 * dup_key.h - Definition for management of duplicate key indexes
 */

#ifndef _DUP_KEY_H_
#define _DUP_KEY_H_

#ident "$Id$"


// 
#define DUP_MODE_OVFL_LEVEL_NOT_SET   (-1)
#define OVFL_LEVEL_DEFAULT   (10)
#define OVFL_LEVEL_MIN       (0)
#define OVFL_LEVEL_MAX       (16)

typedef enum
{
  DUP_MODE_NONE = 0,
  DUP_MODE_OID,
  DUP_MODE_PAGEID,
  DUP_MODE_SLOTID,
  DUP_MODE_VOLID,
  DUP_MODE_LAST
} EN_DUP_MODE;
#define DUP_MODE_DEFAULT  (DUP_MODE_PAGEID)

//---------------------------------------------------------------------
#define SUPPORT_KEY_DUP_LEVEL

#define HIDDEN_INDEX_COL_ATTR_ID_BASE    (-2848048)
#define HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  "_cub_idx_col_"
#define HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_LEN  (13)

#define HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_OID     "o_"
#define HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_PAGEID  "p_"
#define HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_SLOTID  "s_"
#define HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_VOLID   "v_"

static const char *st_hidden_index_col_name[] = {
/* *INDENT-OFF* */
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_OID "00",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_OID "01",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_OID "02",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_OID "03",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_OID "04",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_OID "05",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_OID "06",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_OID "07",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_OID "08",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_OID "09",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_OID "10",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_OID "11",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_OID "12",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_OID "13",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_OID "14",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_OID "15",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_OID "16",
 
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_PAGEID "00",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_PAGEID "01",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_PAGEID "02",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_PAGEID "03",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_PAGEID "04",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_PAGEID "05",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_PAGEID "06",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_PAGEID "07",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_PAGEID "08",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_PAGEID "09",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_PAGEID "10",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_PAGEID "11",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_PAGEID "12",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_PAGEID "13",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_PAGEID "14",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_PAGEID "15",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_PAGEID "16",
 
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_SLOTID "00",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_SLOTID "01",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_SLOTID "02",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_SLOTID "03",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_SLOTID "04",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_SLOTID "05",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_SLOTID "06",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_SLOTID "07",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_SLOTID "08",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_SLOTID "09",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_SLOTID "10",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_SLOTID "11",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_SLOTID "12",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_SLOTID "13",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_SLOTID "14",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_SLOTID "15",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_SLOTID "16",
 
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_VOLID "00",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_VOLID "01",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_VOLID "02",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_VOLID "03",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_VOLID "04",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_VOLID "05",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_VOLID "06",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_VOLID "07",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_VOLID "08",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_VOLID "09",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_VOLID "10",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_VOLID "11",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_VOLID "12",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_VOLID "13",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_VOLID "14",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_VOLID "15",
  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX  HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_VOLID "16",
/* *INDENT-ON* */
  0x00
};

#define BUILD_HIDDEN_INDEX_COL_IDX(mode, level)  ((((mode) -1) * 17) + (level))

#define GET_HIDDEN_INDEX_COL_NAME(mode, level)   (st_hidden_index_col_name[BUILD_HIDDEN_INDEX_COL_IDX((mode), (level))])
#define MK_HIDDEN_INDEX_COL_ATTR_ID(mode, level) (HIDDEN_INDEX_COL_ATTR_ID_BASE - ((mode) | ((level) << 4)))
#define GET_HIDDEN_INDEX_COL_MODE(attid)         ((HIDDEN_INDEX_COL_ATTR_ID_BASE - (attid)) & 0x0000000F)
#define GET_HIDDEN_INDEX_COL_LEVEL(attid)        ((HIDDEN_INDEX_COL_ATTR_ID_BASE - (attid)) >> 4)
// *INDENT-OFF*
#define GET_HIDDEN_INDEX_COL_MODE_LEVEL_FROM_NAME(name, mode, level)  do {                                         \
        char chx, ch_mode;                                                                                         \
        if(sscanf ((name) + HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_LEN, "%c_%02d%c", &(ch_mode), &(level), &chx) != 2)  \
          {  assert(false); }                                                                                      \
        if(ch_mode == HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_OID[0])         (mode) = DUP_MODE_OID;                     \
        else if(ch_mode == HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_PAGEID[0]) (mode) = DUP_MODE_PAGEID;                  \
        else if(ch_mode == HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_SLOTID[0]) (mode) = DUP_MODE_SLOTID;                  \
        else if(ch_mode == HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_VOLID[0])  (mode) = DUP_MODE_VOLID;                   \
        else assert (false);                                                                                       \
 } while(0)
 // *INDENT-ON*

#if defined(SUPPORT_KEY_DUP_LEVEL)
#define IS_HIDDEN_INDEX_COL_ID(id)      ((id) <= HIDDEN_INDEX_COL_ATTR_ID_BASE)
#define IS_HIDDEN_INDEX_COL_NAME(name)  ((name[0] == '_') && memcmp ((name), HIDDEN_INDEX_COL_ATTR_NAME_PREFIX, HIDDEN_INDEX_COL_ATTR_NAME_PREFIX_LEN) == 0)
#else
#define IS_HIDDEN_INDEX_COL_ID(id)      (false)
#define IS_HIDDEN_INDEX_COL_NAME(name)
#endif


extern DB_DOMAIN *dk_get_hidden_attr_domain_type (int mode, int level);
extern void dk_hidden_attribute_initialized ();
extern void dk_hidden_attribute_finalized ();

#if !defined(SERVER_MODE)
#include "class_object.h"

extern SM_ATTRIBUTE *dk_find_sm_hidden_attribute (int att_id, const char *att_name);
#endif

#if defined(SERVER_MODE) || defined(SA_MODE)
extern int dk_heap_midxkey_get_hidden_value (int att_id, OID * rec_oid, DB_VALUE * value);
// The actual return type is OR_ATTRIBUTE*.
// Here it is treated as void* due to collision with C++. (error: template with C linkage)
extern void *dk_find_or_hidden_attribute (int att_id);
#endif


#endif /* _DUP_KEY_H_ */
