
#line 3 "/home/valentinp/work/cubrid/src/executables/loader_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer loader_yy_create_buffer
#define yy_delete_buffer loader_yy_delete_buffer
#define yy_flex_debug loader_yy_flex_debug
#define yy_init_buffer loader_yy_init_buffer
#define yy_flush_buffer loader_yy_flush_buffer
#define yy_load_buffer_state loader_yy_load_buffer_state
#define yy_switch_to_buffer loader_yy_switch_to_buffer
#define yyin loader_yyin
#define yyleng loader_yyleng
#define yylex loader_yylex
#define yylineno loader_yylineno
#define yyout loader_yyout
#define yyrestart loader_yyrestart
#define yytext loader_yytext
#define yywrap loader_yywrap
#define yyalloc loader_yyalloc
#define yyrealloc loader_yyrealloc
#define yyfree loader_yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE loader_yyrestart(loader_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t loader_yyleng;

extern FILE *loader_yyin, *loader_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up loader_yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up loader_yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via loader_yyrestart()), so that the user can continue scanning by
	 * just pointing loader_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when loader_yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t loader_yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow loader_yywrap()'s to do buffer switches
 * instead of setting up a fresh loader_yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void loader_yyrestart (FILE *input_file  );
void loader_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE loader_yy_create_buffer (FILE *file,int size  );
void loader_yy_delete_buffer (YY_BUFFER_STATE b  );
void loader_yy_flush_buffer (YY_BUFFER_STATE b  );
void loader_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void loader_yypop_buffer_state (void );

static void loader_yyensure_buffer_stack (void );
static void loader_yy_load_buffer_state (void );
static void loader_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER loader_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE loader_yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE loader_yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE loader_yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *loader_yyalloc (yy_size_t  );
void *loader_yyrealloc (void *,yy_size_t  );
void loader_yyfree (void *  );

#define yy_new_buffer loader_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        loader_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            loader_yy_create_buffer(loader_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        loader_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            loader_yy_create_buffer(loader_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *loader_yyin = (FILE *) 0, *loader_yyout = (FILE *) 0;

typedef int yy_state_type;

extern int loader_yylineno;

int loader_yylineno = 1;

extern char *loader_yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr loader_yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up loader_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	loader_yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 102
#define YY_END_OF_BUFFER 103
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[275] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  103,  102,    1,    2,  102,   73,   68,   66,
       68,   69,   27,   28,  102,   76,  102,  102,  102,   30,
       23,   68,   68,   68,   68,   68,   68,   68,   68,   74,
       65,  102,   25,   24,   26,  102,  102,  102,  102,   86,
       87,   84,   85,   94,   96,   94,   98,  101,   80,   81,
       80,    1,    2,   68,    0,   68,   68,   68,    0,   30,
        0,   29,   79,    0,   29,    0,   30,   31,    0,   71,
       68,   68,   68,   70,   68,   68,   68,   68,   72,   75,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   22,   20,   19,
       21,   68,   39,   42,   83,   92,   90,   88,   91,   89,
        0,  100,   97,    0,   82,   68,   68,   68,   16,    0,
       78,    0,    0,   29,    0,   77,    0,   29,    0,   29,
        0,   35,    0,   29,   68,   68,   68,   68,   68,   68,
       68,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   43,    0,    0,    0,   92,   93,    0,    0,
        0,   68,   68,    0,   29,    0,   29,    0,   29,    0,
       35,    0,    0,   29,   68,    7,   68,    3,   68,    8,

       68,   50,   58,   52,   51,   55,   47,   60,   56,   54,
       45,   63,   48,   40,   46,   41,   57,   61,   53,   64,
       49,   62,   44,   67,   59,   92,   93,    0,   99,   68,
       68,    0,   29,   38,   33,   34,    4,   68,   68,   68,
       68,    9,   17,   68,   33,    0,   68,   68,    5,   68,
       68,   32,   68,    6,   68,   68,   13,   68,   68,   68,
       68,   10,   68,   68,   15,   68,   68,   68,   14,   68,
       12,   18,   11,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    7,    8,    1,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   19,   19,   20,    1,    1,
        1,    1,    1,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
        6,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   48,   49,   50,    6,    1,   51,   52,   53,   54,

       55,   56,    6,   57,   58,    6,    6,   59,   34,   60,
       61,   62,    6,   63,   64,   65,   66,    6,    6,   67,
        6,   68,   69,   70,   71,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   72,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       73,   74,   75,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,

       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   76,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   77,   78,
       78,   78,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,    1
    } ;

static yyconst YY_CHAR yy_meta[79] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    2,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    1,
        1,    3,    3,    3,    3,    3,    3,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1,
        1,    2,    2,    2,    2,    2,    2,    2
    } ;

static yyconst flex_uint16_t yy_base[285] =
    {   0,
        0,    0,  616,  615,  658,  656,   74,   75,  644,  639,
       78,   79,  647,  694,  642,  694,  634,  694,   11,  694,
       62,  694,  694,  694,   69,  694,   78,   80,   83,   85,
      694,   80,   73,   86,   98,   90,   84,   78,  100,  694,
      171,  190,  694,  694,  694,   51,   91,  102,  108,  694,
      694,  694,  627,  694,  694,  169,  694,  108,  694,  694,
      608,  622,  694,   58,  164,  177,  185,  205,  130,  172,
      151,  242,  694,  157,  247,  186,  265,  204,  274,  694,
      245,  239,  243,  694,  255,  249,  190,  265,  694,  694,
      582,  179,  297,  590,  580,  586,  570,  556,  550,  190,

      540,  540,   97,  545,  272,  529,  481,  694,  694,  694,
      694,  235,  694,  252,  694,  486,  694,  694,  694,  694,
        0,  694,  694,  327,  694,  261,  291,  300,  267,  341,
      694,  491,  333,  694,  346,  694,  480,  335,  352,  694,
      338,  356,  361,  365,  338,  333,  344,  353,  359,  373,
      347,  449,  432,  411,  405,  396,  364,  371,  364,  349,
      348,  337,  309,  296,  298,  266,  262,  255,  251,  251,
      249,  232,  694,  202,  210,  190,  174,    0,  411,  224,
      186,  365,  369,  382,  416,  435,  694,  421,  433,  437,
      425,  439,  135,  694,  397,  423,  418,  392,  442,  434,

      445,  694,  694,  694,  694,  694,  694,  694,  694,  694,
      694,  694,  694,  694,  694,  694,  694,  694,  694,  694,
      694,  694,  694,  694,  694,  694,  694,  380,  694,  438,
      440,  460,  501,  463,  507,  694,  413,  463,  468,  478,
      482,  451,  458,  470,  537,  110,  465,  505,  476,  524,
      520,  694,  530,  480,  528,  541,  539,  543,  555,  566,
      561,  577,  582,  573,  491,  586,  584,  597,  494,  594,
      509,  511,  517,  694,  670,  673,  676,  679,  682,  684,
      687,  690,  113,  110
    } ;

static yyconst flex_int16_t yy_def[285] =
    {   0,
      274,    1,  275,  275,  276,  276,  277,  277,  278,  278,
      279,  279,  274,  274,  274,  274,  274,  274,  280,  274,
      280,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  280,  280,  280,  280,  280,  280,  280,  280,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  280,  274,  280,  280,  280,  274,  274,
      281,  274,  274,  282,  274,  274,  274,  274,  274,  274,
      280,  280,  280,  274,  280,  280,  280,  280,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,

      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  280,  274,  280,  274,  274,  274,  274,  274,  274,
      283,  274,  274,  274,  274,  280,  280,  280,  280,  281,
      274,  274,  274,  274,  282,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  280,  280,  280,  280,  280,  280,
      280,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  284,  274,  274,
      274,  280,  280,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  280,  280,  280,  280,  280,  280,

      280,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  280,
      280,  274,  274,  274,  274,  274,  280,  280,  280,  280,
      280,  280,  280,  280,  274,  274,  280,  280,  280,  280,
      280,  274,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,    0,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274
    } ;

static yyconst flex_uint16_t yy_nxt[773] =
    {   0,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   14,   25,   26,   27,   28,   29,   30,   30,   14,
       31,   19,   32,   33,   34,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   35,   19,   19,   19,   36,   37,
       38,   19,   19,   39,   19,   19,   40,   41,   14,   42,
       19,   32,   33,   34,   19,   19,   19,   19,   19,   35,
       19,   19,   19,   36,   37,   38,   39,   19,   43,   44,
       45,   46,   47,   48,   49,   48,   48,   48,   55,   55,
       60,   60,   65,   66,   69,   67,   70,   70,   80,   61,
       61,   68,   71,   69,   73,   70,   70,   72,   72,   74,

       75,   76,   77,   77,   78,   81,   84,   82,   89,  122,
       79,   83,  227,   87,   67,  178,  123,   88,   86,   68,
      124,   56,   56,  112,  112,  112,  112,  112,  112,   65,
       66,   81,  169,   65,   66,  170,   82,  171,   85,   79,
       83,   87,   88,  252,   65,   66,   86,   72,   72,   65,
       66,   65,   66,  131,  132,   65,   66,   65,   66,  136,
      137,   65,   66,   85,  112,  112,  112,  113,  236,   65,
       66,   65,   66,   90,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  114,  112,  112,  116,   75,  180,   70,
       70,  226,   91,   92,   93,   94,   95,   79,   96,   97,

       98,   99,  100,  141,  141,  101,  153,  102,  103,  104,
      105,  106,  107,  108,  225,  109,  154,  127,  165,  110,
      128,  142,  142,  150,  117,  228,   79,  166,  118,  129,
      111,  119,  229,  120,  224,  121,   64,   64,   64,   64,
       64,   64,  108,  127,  109,  128,  223,  110,   65,   66,
      126,  126,  126,  126,  126,  111,   65,   66,  129,   72,
       72,   65,   66,  222,  138,  138,  145,  133,  134,  147,
      149,  221,  139,  140,  134,  220,   65,   66,  146,  140,
       75,   76,   77,   77,   78,  219,  143,  148,  143,  218,
       79,  144,  144,  217,  151,  145,  133,  134,  147,  149,

      134,  139,  140,  146,  173,  140,   65,   66,  216,  174,
       65,   66,  182,  148,   65,   66,   65,   66,  155,   79,
       65,   66,  151,   65,   66,  156,   65,   66,  179,  180,
      181,  157,   65,   66,  183,  215,   65,   66,   65,   66,
      214,  182,  158,  131,  132,  184,  213,  184,  136,  137,
      185,  185,  138,  138,  190,  141,  141,  191,  196,  183,
      186,  187,   65,   66,  188,  197,  188,  187,  212,  189,
      189,   65,   66,  142,  142,  192,  195,  193,  144,  144,
      201,  228,  144,  144,  211,  198,  210,  196,  229,  186,
      187,  194,  193,  187,  197,  209,  199,  194,  200,  185,

      185,  195,  208,  230,   65,   66,  193,  231,  207,   65,
       66,  198,  179,  180,  181,   65,   66,  193,   65,   66,
      194,  199,  206,  194,   65,   66,  191,  200,  230,  205,
       65,   66,  231,  185,  185,  237,   65,   66,  189,  189,
       65,   66,  134,  204,   65,   66,  193,  232,  134,  232,
      189,  189,  233,  233,  234,  234,  235,  235,  239,  140,
      237,  193,  238,   65,   66,  140,  203,  240,   65,   66,
      242,  134,  241,  202,  134,  193,  243,  233,  233,  244,
      234,  234,  136,  239,   65,   66,  193,  238,  140,   65,
       66,  140,  247,  131,   65,   66,  240,  241,  253,  242,

      248,  243,  249,  177,  244,   65,   66,  251,  245,   65,
       66,   65,   66,   65,   66,  176,   65,   66,  233,  233,
      247,  250,   65,   66,  235,  235,  248,  187,  246,   65,
       66,  249,  251,  187,   65,   66,   65,   66,  245,   65,
       66,   65,   66,  246,  254,  255,  250,   65,   66,   65,
       66,   65,   66,   65,   66,  257,  187,  246,  246,  187,
      256,  258,   65,   66,  259,   65,   66,  175,  246,  254,
      172,  260,  168,  246,  255,  167,   65,   66,  261,  262,
       65,   66,   65,   66,  257,  256,  164,  246,   65,   66,
      163,   65,   66,  259,  263,   65,   66,  260,  246,   65,

       66,   65,   66,  261,  262,  264,  265,  162,  161,  266,
       65,   66,   65,   66,   65,   66,  267,  268,  269,  263,
      160,  159,  152,   62,  125,  270,   65,   66,  265,  271,
      264,  115,   65,   66,  272,  266,   63,   65,   66,  273,
      269,  267,  268,   62,   65,   66,  274,   58,   65,   66,
      270,  271,   58,   65,   66,   65,   66,   65,   66,  272,
       53,  273,   53,   51,   51,   65,   66,  274,   65,   66,
       50,   50,   50,   52,   52,   52,   54,   54,   54,   57,
       57,   57,   59,   59,   59,   64,   64,  130,  130,  130,
      135,  135,  135,   13,  274,  274,  274,  274,  274,  274,

      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274
    } ;

static yyconst flex_int16_t yy_chk[773] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    7,    8,
       11,   12,   19,   19,   25,   21,   25,   25,   32,   11,
       12,   21,   27,   27,   29,   27,   27,   28,   28,   29,

       30,   30,   30,   30,   30,   33,   35,   34,   39,   58,
       30,   34,  284,   37,   21,  283,   58,   38,   36,   21,
       58,    7,    8,   46,   46,   46,   46,   46,   46,   64,
       64,   33,  103,   21,   21,  103,   34,  103,   35,   30,
       34,   37,   38,  246,   33,   33,   36,   69,   69,   38,
       38,   32,   32,   71,   71,   37,   37,   34,   34,   74,
       74,   36,   36,   35,   47,   47,   47,   47,  193,   35,
       35,   39,   39,   41,   48,   48,   48,   48,   48,   48,
       49,   49,   49,   49,   49,   49,   56,   70,  181,   70,
       70,  177,   41,   41,   41,   41,   41,   70,   41,   41,

       41,   41,   41,   76,   76,   41,   92,   41,   41,   41,
       41,   41,   41,   42,  176,   42,   92,   67,  100,   42,
       67,   78,   78,   87,   56,  180,   70,  100,   56,   68,
       42,   56,  180,   56,  175,   56,   65,   65,   65,   65,
       65,   65,   42,   67,   42,   67,  174,   42,   66,   66,
       66,   66,   66,   66,   66,   42,   67,   67,   68,   72,
       72,   87,   87,  172,   75,   75,   81,   72,   72,   83,
       86,  171,   75,   75,   72,  170,   68,   68,   82,   75,
       77,   77,   77,   77,   77,  169,   79,   85,   79,  168,
       77,   79,   79,  167,   88,   81,   72,   72,   83,   86,

       72,   75,   75,   82,  105,   75,  112,  112,  166,  105,
       82,   82,  127,   85,   83,   83,   81,   81,   93,   77,
       86,   86,   88,  114,  114,   93,   85,   85,  124,  124,
      124,   93,  126,  126,  128,  165,   88,   88,  129,  129,
      164,  127,   93,  130,  130,  133,  163,  133,  135,  135,
      133,  133,  138,  138,  141,  141,  141,  142,  146,  128,
      138,  138,  127,  127,  139,  147,  139,  138,  162,  139,
      139,  128,  128,  142,  142,  142,  145,  142,  143,  143,
      151,  228,  144,  144,  161,  148,  160,  146,  228,  138,
      138,  144,  142,  138,  147,  159,  149,  144,  150,  184,

      184,  145,  158,  182,  146,  146,  142,  183,  157,  145,
      145,  148,  179,  179,  179,  147,  147,  142,  151,  151,
      144,  149,  156,  144,  148,  148,  191,  150,  182,  155,
      149,  149,  183,  185,  185,  195,  182,  182,  188,  188,
      183,  183,  185,  154,  150,  150,  191,  186,  185,  186,
      189,  189,  186,  186,  190,  190,  192,  192,  197,  189,
      195,  191,  196,  198,  198,  189,  153,  199,  195,  195,
      201,  185,  200,  152,  185,  191,  230,  232,  232,  231,
      234,  234,  137,  197,  237,  237,  191,  196,  189,  197,
      197,  189,  238,  132,  196,  196,  199,  200,  247,  201,

      239,  230,  240,  116,  231,  200,  200,  244,  235,  230,
      230,  231,  231,  199,  199,  107,  201,  201,  233,  233,
      238,  241,  242,  242,  235,  235,  239,  233,  235,  243,
      243,  240,  244,  233,  238,  238,  247,  247,  245,  239,
      239,  244,  244,  235,  248,  250,  241,  249,  249,  240,
      240,  254,  254,  241,  241,  253,  233,  235,  245,  233,
      251,  255,  265,  265,  256,  269,  269,  106,  235,  248,
      104,  257,  102,  245,  250,  101,  248,  248,  257,  258,
      271,  271,  272,  272,  253,  251,   99,  245,  273,  273,
       98,  251,  251,  256,  259,  250,  250,  257,  245,  255,

      255,  253,  253,  257,  258,  260,  261,   97,   96,  262,
      257,  257,  256,  256,  258,  258,  262,  263,  264,  259,
       95,   94,   91,   62,   61,  266,  259,  259,  261,  267,
      260,   53,  261,  261,  268,  262,   17,  260,  260,  270,
      264,  262,  263,   15,  264,  264,   13,   10,  262,  262,
      266,  267,    9,  263,  263,  267,  267,  266,  266,  268,
        6,  270,    5,    4,    3,  270,  270,    0,  268,  268,
      275,  275,  275,  276,  276,  276,  277,  277,  277,  278,
      278,  278,  279,  279,  279,  280,  280,  281,  281,  281,
      282,  282,  282,  274,  274,  274,  274,  274,  274,  274,

      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int loader_yy_flex_debug;
int loader_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *loader_yytext;
/*
 * Copyright (C) 2008 Search Solution Corporation. All rights reserved by Search Solution.
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or 
 *   (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 *
 */
/*
 * loader_lexer.l - loader lexer file
 */
#include "loader.h"
#include "loader_grammar.h"

#include "message_catalog.h"
#include "error_manager.h"
#include "memory_alloc.h"
#include "utility.h"
#include "intl_support.h"
#include "language_support.h"

/*#define LEXER_DEBUG*/

#ifdef LEXER_DEBUG
#define PRINT printf("lex: ");printf
#else
#define PRINT(a, b)
#endif

#define STRING_POOL_SIZE (1024)
#define COPY_BUF_POOL_SIZE (512)
#define QUOTED_STR_BUF_POOL_SIZE (512)
#define MAX_QUOTED_STR_BUF_SIZE (32 * 1024)
#define MAX_COPY_BUF_SIZE (256)

/*
 *  The default behavior of ECHO is fprintf(loader_yyout, "%s", loader_yytext).
 *  Therefore, we have redefined ECHO.
 */
#define ECHO do{load_fail_flag = true;}while(0)

bool loader_In_instance_line = true;

extern void loader_yyerror (const char *s);
extern void loader_reset_string_pool (void);
extern void loader_initialize_lexer (void);
extern void loader_load_fail (void);

/* pool for string assigned to yyval */
static LDR_STRING string_Pool[STRING_POOL_SIZE];
static int string_Pool_idx = 0;

/* buffer pool for copying loader_yytext and qstr_Malloc_buffer */
static char copy_Buf_pool[COPY_BUF_POOL_SIZE][MAX_COPY_BUF_SIZE];
static int copy_Buf_pool_idx = 0;

/* quoted string buffer pool */
static char qstr_Buf_pool[QUOTED_STR_BUF_POOL_SIZE][MAX_QUOTED_STR_BUF_SIZE];
static int qstr_Buf_pool_idx = 0;
static char *qstr_Malloc_buffer = NULL; /* using when pool overflow */
static int qstr_Malloc_buffer_size = 0;
static bool use_Qstr_malloc_buffer = false;
static char *qstr_Buf_p = NULL;
static int qstr_Buf_idx = 0;

static void loader_set_quoted_string_buffer (void);
static void loader_append_string (char c);
static LDR_STRING *loader_get_string_container (void);
static LDR_STRING *loader_make_string_by_yytext (void);
static LDR_STRING *loader_make_string_by_buffer (void);

static bool load_fail_flag = false;

extern int loader_yyline;

#define INITIAL 0
#define BRACKET_ID 1
#define DELIMITED_ID 2
#define DQS 3
#define SQS 4
#define COMMENT 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int loader_yylex_destroy (void );

int loader_yyget_debug (void );

void loader_yyset_debug (int debug_flag  );

YY_EXTRA_TYPE loader_yyget_extra (void );

void loader_yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *loader_yyget_in (void );

void loader_yyset_in  (FILE * _in_str  );

FILE *loader_yyget_out (void );

void loader_yyset_out  (FILE * _out_str  );

yy_size_t loader_yyget_leng (void );

char *loader_yyget_text (void );

int loader_yyget_lineno (void );

void loader_yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int loader_yywrap (void );
#else
extern int loader_yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( loader_yytext, loader_yyleng, 1, loader_yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( loader_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( loader_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, loader_yyin))==0 && ferror(loader_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(loader_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int loader_yylex (void);

#define YY_DECL int loader_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after loader_yytext and loader_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! loader_yyin )
			loader_yyin = stdin;

		if ( ! loader_yyout )
			loader_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			loader_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				loader_yy_create_buffer(loader_yyin,YY_BUF_SIZE );
		}

		loader_yy_load_buffer_state( );
		}

	{

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of loader_yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 275 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 694 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
{
    loader_yylineno = loader_yyline++;
    if (load_fail_flag)
      {
        load_fail_flag = false;              
        loader_load_fail ();
      }
    return NL;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
{
    PRINT ("NULL_ %s\n", loader_yytext);
    return NULL_;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
{
    PRINT ("CLASS %s\n", loader_yytext);
    return CLASS;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
{
    PRINT ("SHARED %s\n", loader_yytext);
    return SHARED;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
{
    PRINT ("DEFAULT%s\n", loader_yytext);
    return DEFAULT;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
{
    PRINT ("DATE %s\n", loader_yytext);
    return DATE_;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
{
    PRINT ("TIME %s\n", loader_yytext);
    return TIME;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
{
    PRINT ("UTIME %s\n", loader_yytext);
    return UTIME;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
{
    PRINT ("TIMESTAMP %s\n", loader_yytext);
    return TIMESTAMP;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
{
    PRINT ("TIMESTAMPLTZ %s\n", loader_yytext);
    return TIMESTAMPLTZ;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
{
    PRINT ("TIMESTAMPTZ %s\n", loader_yytext);
    return TIMESTAMPTZ;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
{
    PRINT ("DATETIME %s\n", loader_yytext);
    return DATETIME;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
{
    PRINT ("DATETIMELTZ %s\n", loader_yytext);
    return DATETIMELTZ;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
{
    PRINT ("DATETIMETZ %s\n", loader_yytext);
    return DATETIMETZ;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
{
    PRINT ("CMD_ID %s\n", loader_yytext);
    loader_In_instance_line = false;
    return CMD_ID;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
{
    PRINT ("CMD_CLASS %s\n", loader_yytext);
    loader_In_instance_line = false;
    return CMD_CLASS;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
{
    PRINT ("CMD_CONSTRUCTOR %s\n", loader_yytext);
    return CMD_CONSTRUCTOR;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
{
    PRINT ("REF_ELO_INT %s\n", loader_yytext);
    return REF_ELO_INT;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
{
    PRINT ("REF_ELO_EXT %s\n", loader_yytext);
    return REF_ELO_EXT;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
{
    PRINT ("REF_USER %s\n", loader_yytext);
    return REF_USER;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
{
    PRINT ("REF_CLASS %s\n", loader_yytext);
    return REF_CLASS;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
{
    PRINT ("OBJECT_REFERENCE %s\n", loader_yytext);
    return OBJECT_REFERENCE;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
{
    PRINT ("OID_DELIMETER %s\n", loader_yytext);
    return OID_DELIMETER;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
{
    PRINT ("SET_START_BRACE %s\n", loader_yytext);
    return SET_START_BRACE;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
{
    PRINT ("SET_END_BRACE %s\n", loader_yytext);
    return SET_END_BRACE;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
{
    PRINT ("START_PAREN %s\n", loader_yytext);
    return START_PAREN;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
{
    PRINT ("END_PAREN %s\n", loader_yytext);
    return END_PAREN;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
{
    PRINT ("REAL_LIT %s\n", loader_yytext);
    loader_yylval.string = loader_make_string_by_yytext ();
    return REAL_LIT;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
{
    PRINT ("INT_LIT %s\n", loader_yytext);
    loader_yylval.string = loader_make_string_by_yytext ();
    return INT_LIT;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
{
    PRINT ("OID %s\n", loader_yytext);
    loader_yylval.intval = atoi (loader_yytext);
    return OID_;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
{
    PRINT ("TIME_LIT4 %s\n", loader_yytext);
    loader_yylval.string = loader_make_string_by_yytext ();
    return TIME_LIT4;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
{
    PRINT ("TIME_LIT42 %s\n", loader_yytext);
    loader_yylval.string = loader_make_string_by_yytext ();
    return TIME_LIT42;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
{
    PRINT ("TIME_LIT3 %s\n", loader_yytext);
    loader_yylval.string = loader_make_string_by_yytext ();
    return TIME_LIT3;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
{
    PRINT ("TIME_LIT31 %s\n", loader_yytext);
    loader_yylval.string = loader_make_string_by_yytext ();
    return TIME_LIT31;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
{
    PRINT ("TIME_LIT2 %s\n", loader_yytext);
    loader_yylval.string = loader_make_string_by_yytext ();
    return TIME_LIT2;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
{
    PRINT ("TIME_LIT1 %s\n", loader_yytext);
    loader_yylval.string = loader_make_string_by_yytext ();
    return TIME_LIT1;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
{
    PRINT ("DATE_LIT2 %s\n", loader_yytext);
    loader_yylval.string = loader_make_string_by_yytext ();
    return DATE_LIT2;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
{
    PRINT ("YEN_SYMBOL %s\n", loader_yytext);
    return YEN_SYMBOL;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
{
    PRINT ("YEN_SYMBOL %s\n", loader_yytext);
    return YEN_SYMBOL;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
{
    PRINT ("WON_SYMBOL %s\n", loader_yytext);
    return WON_SYMBOL;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
{
    PRINT ("WON_SYMBOL %s\n", loader_yytext);
    return WON_SYMBOL;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
{
    PRINT ("TURKISH_LIRA_CURRENCY %s\n", loader_yytext);
    return TURKISH_LIRA_CURRENCY;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
{
    PRINT ("TURKISH_LIRA_CURRENCY %s\n", loader_yytext);
    return TURKISH_LIRA_CURRENCY;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
{
    PRINT ("BRITISH_POUND_SYMBOL %s\n", loader_yytext);
    return BRITISH_POUND_SYMBOL;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
{
    PRINT ("CAMBODIAN_RIEL_SYMBOL %s\n", loader_yytext);
    return CAMBODIAN_RIEL_SYMBOL;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
{
    PRINT ("CHINESE_RENMINBI_SYMBOL %s\n", loader_yytext);
    return CHINESE_RENMINBI_SYMBOL;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
{
    PRINT ("INDIAN_RUPEE_SYMBOL %s\n", loader_yytext);
    return INDIAN_RUPEE_SYMBOL;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
{
    PRINT ("RUSSIAN_RUBLE_SYMBOL %s\n", loader_yytext);
    return RUSSIAN_RUBLE_SYMBOL;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
{
    PRINT ("AUSTRALIAN_DOLLAR_SYMBOL %s\n", loader_yytext);
    return AUSTRALIAN_DOLLAR_SYMBOL;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
{
    PRINT ("CANADIAN_DOLLAR_SYMBOL %s\n", loader_yytext);
    return CANADIAN_DOLLAR_SYMBOL;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
{
    PRINT ("BRASILIAN_REAL_SYMBOL %s\n", loader_yytext);
    return BRASILIAN_REAL_SYMBOL;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
{
    PRINT ("ROMANIAN_LEU_SYMBOL %s\n", loader_yytext);
    return ROMANIAN_LEU_SYMBOL;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
{
    PRINT ("EURO_SYMBOL %s\n", loader_yytext);
    return EURO_SYMBOL;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
{
    PRINT ("SWISS_FRANC_SYMBOL %s\n", loader_yytext);
    return SWISS_FRANC_SYMBOL;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
{
    PRINT ("DANISH_KRONE_SYMBOL %s\n", loader_yytext);
    return DANISH_KRONE_SYMBOL;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
{
    PRINT ("NORWEGIAN_KRONE_SYMBOL %s\n", loader_yytext);
    return NORWEGIAN_KRONE_SYMBOL;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
{
    PRINT ("BULGARIAN_LEV_SYMBOL %s\n", loader_yytext);
    return BULGARIAN_LEV_SYMBOL;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
{
    PRINT ("VIETNAMESE_DONG_SYMBOL %s\n", loader_yytext);
    return VIETNAMESE_DONG_SYMBOL;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
{
    PRINT ("CZECH_KORUNA_SYMBOL %s\n", loader_yytext);
    return CZECH_KORUNA_SYMBOL;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
{
    PRINT ("POLISH_ZLOTY_SYMBOL %s\n", loader_yytext);
    return POLISH_ZLOTY_SYMBOL;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
{
    PRINT ("SWEDISH_KRONA_SYMBOL %s\n", loader_yytext);
    return SWEDISH_KRONA_SYMBOL;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
{
    PRINT ("CROATIAN_KUNA_SYMBOL %s\n", loader_yytext);
    return CROATIAN_KUNA_SYMBOL;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
{
    PRINT ("SERBIAN_DINAR_SYMBOL %s\n", loader_yytext);
    return SERBIAN_DINAR_SYMBOL;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
{
    PRINT ("BACKSLASH %s\n", loader_yytext);
    return BACKSLASH;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
{
    PRINT ("DOLLAR_SYMBOL %s\n", loader_yytext);
    return DOLLAR_SYMBOL;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
{
    PRINT ("DOLLAR_SYMBOL %s\n", loader_yytext);
    return DOLLAR_SYMBOL;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
{
    PRINT ("IDENTIFIER %s\n", loader_yytext);
    loader_yylval.string = loader_make_string_by_yytext ();
    return IDENTIFIER;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
{
    PRINT ("Quote %s\n", loader_yytext);
    BEGIN SQS;
    loader_set_quoted_string_buffer ();
    return Quote;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
{
    PRINT ("NQuote %s\n", loader_yytext);
    BEGIN SQS;
    loader_set_quoted_string_buffer ();
    return NQuote;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
{
    PRINT ("BQuote %s\n", loader_yytext);
    BEGIN SQS;
    loader_set_quoted_string_buffer ();
    return BQuote;
}
	YY_BREAK
case 72:
YY_RULE_SETUP
{
    PRINT ("XQuote %s\n", loader_yytext);
    BEGIN SQS;
    loader_set_quoted_string_buffer ();
    return XQuote;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
{
    loader_set_quoted_string_buffer ();
    if (loader_In_instance_line == true)
      {
        BEGIN DQS;
        return DQuote;
      }
    else
      {
        BEGIN DELIMITED_ID;
      }
}
	YY_BREAK
case 74:
YY_RULE_SETUP
{
    loader_set_quoted_string_buffer ();
    BEGIN BRACKET_ID;
}
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
{
    loader_yylineno = loader_yyline++;
    /* continue line */ ; 
}
	YY_BREAK
case 76:
YY_RULE_SETUP
{
    PRINT ("COMMA %s\n", loader_yytext);
    return COMMA;
}
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
{
    loader_yylineno = loader_yyline++;
    /* C++ comments */
}
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
{
    loader_yylineno = loader_yyline++;
    /* SQL comments */
}
	YY_BREAK
case 79:
YY_RULE_SETUP
{
    BEGIN COMMENT;	/* C comments */
}
	YY_BREAK
case 80:
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
{
    loader_yylineno = loader_yyline++;
}
	YY_BREAK
case 82:
YY_RULE_SETUP
{
    BEGIN INITIAL;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
{
    loader_append_string ('"');
}
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
{
    loader_append_string (loader_yytext[0]);
}
	YY_BREAK
case 85:
YY_RULE_SETUP
{
    loader_append_string ('\0');
    PRINT ("IDENTIFIER %s\n", qstr_Buf_p);
    loader_yylval.string = loader_make_string_by_buffer ();
    BEGIN INITIAL;
    return IDENTIFIER;
}
	YY_BREAK
case 86:
/* rule 86 can match eol */
YY_RULE_SETUP
{
    loader_append_string (loader_yytext[0]);
}
	YY_BREAK
case 87:
YY_RULE_SETUP
{
    loader_append_string ('\0');
    PRINT ("IDENTIFIER %s\n", qstr_Buf_p);
    loader_yylval.string = loader_make_string_by_buffer ();
    BEGIN INITIAL;
    return IDENTIFIER;
}
	YY_BREAK
case 88:
YY_RULE_SETUP
{
    loader_append_string ('\n');
}
	YY_BREAK
case 89:
YY_RULE_SETUP
{
    loader_append_string ('\t');
}
	YY_BREAK
case 90:
YY_RULE_SETUP
{
    loader_append_string ('\f');
}
	YY_BREAK
case 91:
YY_RULE_SETUP
{
    loader_append_string ('\r');
}
	YY_BREAK
case 92:
YY_RULE_SETUP
{
    loader_append_string ((char) strtol (&loader_yytext[1], NULL, 8));
}
	YY_BREAK
case 93:
YY_RULE_SETUP
{
    loader_append_string ((char) strtol (&loader_yytext[2], NULL, 16));
}
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
{
    loader_append_string (loader_yytext[0]);
}
	YY_BREAK
case 95:
YY_RULE_SETUP
{
    /* ignore */ ;
}
	YY_BREAK
case 96:
YY_RULE_SETUP
{
    loader_append_string ('\0');
    PRINT ("DQS_String_Body %s\n", qstr_Buf_p);
    loader_yylval.string = loader_make_string_by_buffer ();
    BEGIN INITIAL;
    return DQS_String_Body;
}
	YY_BREAK
case 97:
YY_RULE_SETUP
{
    loader_append_string ('\'');
}
	YY_BREAK
case 98:
/* rule 98 can match eol */
YY_RULE_SETUP
{
    loader_append_string (loader_yytext[0]);
}
	YY_BREAK
case 99:
/* rule 99 can match eol */
YY_RULE_SETUP
{
    loader_yylineno = loader_yyline++;
}
	YY_BREAK
case 100:
YY_RULE_SETUP
{
    loader_append_string ('\0');
    PRINT ("String_Completion %s\n", qstr_Buf_p);
    loader_yylval.string = loader_make_string_by_buffer ();
    BEGIN INITIAL;
    return SQS_String_Body;
}
	YY_BREAK
case 101:
YY_RULE_SETUP
{
    loader_append_string ('\0');
    PRINT ("String_Completion2 %s\n", qstr_Buf_p);
    loader_yylval.string = loader_make_string_by_buffer ();
    BEGIN INITIAL;
    return SQS_String_Body;
}
	YY_BREAK
case 102:
YY_RULE_SETUP
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(BRACKET_ID):
case YY_STATE_EOF(DELIMITED_ID):
case YY_STATE_EOF(DQS):
case YY_STATE_EOF(SQS):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed loader_yyin at a new source and called
			 * loader_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = loader_yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( loader_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * loader_yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of loader_yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					loader_yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			loader_yyrestart(loader_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) loader_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 275 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 275 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 274);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up loader_yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					loader_yyrestart(loader_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( loader_yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve loader_yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void loader_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        loader_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            loader_yy_create_buffer(loader_yyin,YY_BUF_SIZE );
	}

	loader_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	loader_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void loader_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		loader_yypop_buffer_state();
	 *		loader_yypush_buffer_state(new_buffer);
     */
	loader_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	loader_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (loader_yywrap()) processing, but the only time this flag
	 * is looked at is after loader_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void loader_yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	loader_yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE loader_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) loader_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in loader_yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) loader_yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in loader_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	loader_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with loader_yy_create_buffer()
 * 
 */
    void loader_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		loader_yyfree((void *) b->yy_ch_buf  );

	loader_yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a loader_yyrestart() or at EOF.
 */
    static void loader_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	loader_yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then loader_yy_init_buffer was _probably_
     * called from loader_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void loader_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		loader_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void loader_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	loader_yyensure_buffer_stack();

	/* This block is copied from loader_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from loader_yy_switch_to_buffer. */
	loader_yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void loader_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	loader_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		loader_yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void loader_yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)loader_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in loader_yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)loader_yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in loader_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE loader_yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) loader_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in loader_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	loader_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to loader_yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       loader_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE loader_yy_scan_string (yyconst char * yystr )
{
    
	return loader_yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to loader_yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE loader_yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) loader_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in loader_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = loader_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in loader_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up loader_yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		loader_yytext[loader_yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = loader_yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		loader_yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int loader_yyget_lineno  (void)
{
        
    return loader_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *loader_yyget_in  (void)
{
        return loader_yyin;
}

/** Get the output stream.
 * 
 */
FILE *loader_yyget_out  (void)
{
        return loader_yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t loader_yyget_leng  (void)
{
        return loader_yyleng;
}

/** Get the current token.
 * 
 */

char *loader_yyget_text  (void)
{
        return loader_yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void loader_yyset_lineno (int  _line_number )
{
    
    loader_yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see loader_yy_switch_to_buffer
 */
void loader_yyset_in (FILE *  _in_str )
{
        loader_yyin = _in_str ;
}

void loader_yyset_out (FILE *  _out_str )
{
        loader_yyout = _out_str ;
}

int loader_yyget_debug  (void)
{
        return loader_yy_flex_debug;
}

void loader_yyset_debug (int  _bdebug )
{
        loader_yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from loader_yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    loader_yyin = stdin;
    loader_yyout = stdout;
#else
    loader_yyin = (FILE *) 0;
    loader_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * loader_yylex_init()
     */
    return 0;
}

/* loader_yylex_destroy is for both reentrant and non-reentrant scanners. */
int loader_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		loader_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		loader_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	loader_yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * loader_yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *loader_yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *loader_yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void loader_yyfree (void * ptr )
{
			free( (char *) ptr );	/* see loader_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

void loader_yyerror(const char *s)
{
  ldr_increment_err_total(ldr_Current_context);
  fprintf(stderr, 
          msgcat_message (MSGCAT_CATALOG_UTILS, MSGCAT_UTIL_SET_LOADDB,
                          LOADDB_MSG_SYNTAX_ERR),
          loader_yylineno, loader_yytext);
}

int
loader_yywrap ()
{
#ifdef LEXER_DEBUG
  printf ("Parsing done.....\n");
#endif
  return 1;
}

static void
loader_set_quoted_string_buffer (void)
{
  if (qstr_Buf_pool_idx < QUOTED_STR_BUF_POOL_SIZE)
    {
      qstr_Buf_p = &(qstr_Buf_pool[qstr_Buf_pool_idx][0]);
      qstr_Buf_pool_idx++;
      use_Qstr_malloc_buffer = false;
    }
  else
    {
      if (qstr_Malloc_buffer == NULL)
	{
	  qstr_Malloc_buffer_size = MAX_QUOTED_STR_BUF_SIZE;
	  qstr_Malloc_buffer = malloc (qstr_Malloc_buffer_size);
	  
	  if (qstr_Malloc_buffer == NULL)
	    {
	      er_set (ER_ERROR_SEVERITY, ARG_FILE_LINE,
	              ER_OUT_OF_VIRTUAL_MEMORY, 1,
	              (size_t) qstr_Malloc_buffer_size);
	      YY_FATAL_ERROR (er_msg());        
	      return;
	    }
	}

      qstr_Buf_p = qstr_Malloc_buffer;
      use_Qstr_malloc_buffer = true;
    }

  qstr_Buf_idx = 0;
}

static void
loader_append_string (char c)
{
  if (use_Qstr_malloc_buffer == true)
    {
      if (qstr_Buf_idx >= qstr_Malloc_buffer_size)
	{
	  qstr_Malloc_buffer_size *= 2;
	  qstr_Malloc_buffer = realloc (qstr_Malloc_buffer,
	                                qstr_Malloc_buffer_size);
	                                
	  if (qstr_Malloc_buffer == NULL)
	    {
	      er_set (ER_ERROR_SEVERITY, ARG_FILE_LINE,
	              ER_OUT_OF_VIRTUAL_MEMORY, 1,
	              (size_t) qstr_Malloc_buffer_size);
	      YY_FATAL_ERROR (er_msg());        
	      return;
	    }
	    
	  qstr_Buf_p = qstr_Malloc_buffer;
	}
    }
  else
    {
      if (qstr_Buf_idx >= MAX_QUOTED_STR_BUF_SIZE)
	{
	  if (qstr_Malloc_buffer != NULL
	      && qstr_Malloc_buffer_size <= MAX_QUOTED_STR_BUF_SIZE)
	    {
	      free_and_init (qstr_Malloc_buffer);
	      qstr_Malloc_buffer = NULL;
	    }

          if (qstr_Malloc_buffer == NULL)
            {
	      qstr_Malloc_buffer_size = MAX_QUOTED_STR_BUF_SIZE * 2;
	      qstr_Malloc_buffer = malloc (qstr_Malloc_buffer_size);
	  
	      if (qstr_Malloc_buffer == NULL)
	        {
	          er_set (ER_ERROR_SEVERITY, ARG_FILE_LINE,
	                  ER_OUT_OF_VIRTUAL_MEMORY, 1, 
	                  (size_t) qstr_Malloc_buffer_size);
	          YY_FATAL_ERROR (er_msg());        
	          return;
	        }
	    }
	    
	  memcpy (qstr_Malloc_buffer, qstr_Buf_p, qstr_Buf_idx);
	  qstr_Buf_p = qstr_Malloc_buffer;
	  qstr_Buf_pool_idx--;
	  use_Qstr_malloc_buffer = true;
	}
    }

  qstr_Buf_p[qstr_Buf_idx] = c;
  qstr_Buf_idx++;
}

static LDR_STRING *
loader_get_string_container (void)
{
  LDR_STRING *str;

  if (string_Pool_idx < STRING_POOL_SIZE)
    {
      str = &(string_Pool[string_Pool_idx]);
      str->need_free_self = false;
      string_Pool_idx++;
    }
  else
    {
      str = (LDR_STRING *) malloc (sizeof (LDR_STRING));

      if (str == NULL)
	{
	  er_set (ER_ERROR_SEVERITY, ARG_FILE_LINE,
	         ER_OUT_OF_VIRTUAL_MEMORY, 1, sizeof (LDR_STRING));
	  YY_FATAL_ERROR (er_msg());        
	  return NULL;
	}

      str->need_free_self = true;
    }

  return str;
}

static LDR_STRING *
loader_make_string_by_yytext (void)
{
  LDR_STRING *str;
  char *invalid_pos = NULL;

  str = loader_get_string_container ();
  if (str == NULL)
    {
      return NULL;
    }

  str->size = loader_yyleng;

  if (copy_Buf_pool_idx < COPY_BUF_POOL_SIZE 
      && str->size < MAX_COPY_BUF_SIZE)
    {
      str->val = &(copy_Buf_pool[copy_Buf_pool_idx][0]);
      memcpy (str->val, loader_yytext, str->size);
      str->val[str->size] = '\0';
      str->need_free_val = false;
      copy_Buf_pool_idx++;
    }
  else
    {
      str->val = malloc (str->size + 1);
      
      if (str->val == NULL)
        {
	  er_set (ER_ERROR_SEVERITY, ARG_FILE_LINE,
	          ER_OUT_OF_VIRTUAL_MEMORY, 1, (size_t) (str->size + 1));
	  YY_FATAL_ERROR (er_msg());        
	  return NULL;
        }
        
      memcpy (str->val, loader_yytext, str->size);
      str->val[str->size] = '\0';
      str->need_free_val = true;
    }

  if (intl_check_string (str->val, str->size, &invalid_pos,
			 LANG_SYS_CODESET) != 0)
    {
      er_set (ER_ERROR_SEVERITY, ARG_FILE_LINE, ER_INVALID_CHAR, 1,
	      invalid_pos - str->val);
      YY_FATAL_ERROR (er_msg());
      return NULL;
    }

  return str;
}

static LDR_STRING *
loader_make_string_by_buffer (void)
{
  LDR_STRING *str;
  char *invalid_pos = NULL;

  str = loader_get_string_container ();
  if (str == NULL)
    {
      return NULL;
    }

  str->size = qstr_Buf_idx - 1;

  if (use_Qstr_malloc_buffer == false)
    {
      str->val = qstr_Buf_p;
      str->need_free_val = false;
    }
  else
    {
      if (copy_Buf_pool_idx < COPY_BUF_POOL_SIZE 
          && str->size < MAX_COPY_BUF_SIZE)
	{
	  str->val = &(copy_Buf_pool[copy_Buf_pool_idx][0]);
	  memcpy (str->val, qstr_Buf_p, qstr_Buf_idx);
	  str->need_free_val = false;
	  copy_Buf_pool_idx++;
	}
      else
	{
	  str->val = (char *) malloc (qstr_Buf_idx);

	  if (str->val == NULL)
	    {
	      if (str->need_free_self)
		{
		  free_and_init (str);
		}
		
	      er_set (ER_ERROR_SEVERITY, ARG_FILE_LINE,
	              ER_OUT_OF_VIRTUAL_MEMORY, 1, (size_t) qstr_Buf_idx);
	      YY_FATAL_ERROR (er_msg());        
	      return NULL;
	    }

	  memcpy (str->val, qstr_Buf_p, qstr_Buf_idx);
	  str->need_free_val = true;
	}
    }
    
  if (intl_check_string (str->val, str->size, &invalid_pos,
			 LANG_SYS_CODESET) != 0)
    {
      er_set (ER_ERROR_SEVERITY, ARG_FILE_LINE, ER_INVALID_CHAR, 1,
	      invalid_pos - str->val);
      YY_FATAL_ERROR (er_msg());
      return NULL;
    }    

  return str;
}

void
loader_reset_string_pool (void)
{
  string_Pool_idx = 0;
  copy_Buf_pool_idx = 0;
  qstr_Buf_pool_idx = 0;
}

void
loader_initialize_lexer (void)
{
  string_Pool_idx = 0;
  copy_Buf_pool_idx = 0;
  qstr_Buf_pool_idx = 0;
  qstr_Malloc_buffer = NULL;
}

void
loader_load_fail ()
{
  ldr_load_failed_error ();
  ldr_increment_fails ();
}

