version: 2.1

# --------------------------------------------------
# Pipeline-level parameters (values passed from GitHub Actions)
# --------------------------------------------------
parameters:
  baseline:
    type: string
    default: ""
  run_shell_test:
    type: boolean
    default: true
  run_sql_test:
    type: boolean
    default: true
  run_medium_test:
    type: boolean
    default: false
  run_plcsql_test:
    type: boolean
    default: false
# --------------------------------------------------
# 1. Reusable commands
# --------------------------------------------------
commands:
  attach-and-run-tests:
    description: "Attach workspace and run test scripts"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          shell: /bin/bash
          no_output_timeout: 20m
          command: |
            # Limit core files
            ulimit -c 1

            # Check out testcases and testtools (uses custom entrypoint script)
            /entrypoint.sh checkout

            # Handle specific cases for TEST_SUITE
            if [ "$TEST_SUITE" = "none" ]; then
              echo "TEST_SUITE is none"
              exit 1
            elif [ "$TEST_SUITE" = "plcsql" ]; then
              # Hack: run plcsql test via sql suite
              TEST_SUITE="sql"
              file_ext="sql"
              base_dir="cubrid-testcases"
              glob_path="$base_dir/sql/{_05_plcsql,_35_fig_cake/plcsql}/**/cases/*.sql"
            elif [ "$TEST_SUITE" = "sql" ]; then
              file_ext="sql"
              base_dir="cubrid-testcases"
              rm -rf $base_dir/sql/_05_plcsql
              rm -rf $base_dir/sql/_35_fig_cake/plcsql
              glob_path="$base_dir/$TEST_SUITE/_01_object/**/cases/*.sql"
              # glob_path="$base_dir/$TEST_SUITE/_*/**/cases/*.sql"
            elif [ "$TEST_SUITE" = "shell" ]; then
              file_ext="sh"
              base_dir="cubrid-testcases-private-ex"
              rm -rf $base_dir/$TEST_SUITE/_25_unstable
              glob_path="$base_dir/$TEST_SUITE/_01_utility/**/cases/*.sh"
              # glob_path="$base_dir/$TEST_SUITE/_*/**/cases/*.sh"
            else
              file_ext="sql"
              base_dir="cubrid-testcases"
              glob_path="$base_dir/$TEST_SUITE/_*/**/cases/*.sql"
            fi

            circleci tests glob $glob_path | sed 's#^[^/]*/##' | circleci tests split | tee tc.list
            # circleci tests glob $glob_path | sed 's#^[^/]*/##' | circleci tests split --split-by=timings --timings-type=name | tee tc.list
            if [ -s tc.list ]; then
              sed -i "s|^|$base_dir/|" tc.list
              cat tc.list | xargs -n1 dirname > tc_dirs.list
              find $base_dir -name "*.$file_ext" -type f | grep -v -f tc_dirs.list | xargs -r rm -rf

              # Run the tests
              /entrypoint.sh test
            else
              echo "No tests to run"
              circleci-agent step halt
            fi
      - run:
          name: Collect Logs
          command: |
            mkdir -p /tmp/logs
            cp -f /tmp/tests/* /tmp/logs
            if [ "$TEST_SUITE" = "shell" ]; then
              mv -f cubrid-testtools/CTP/result/shell/current_runtime_logs /tmp/logs/ctp_log
            else
              mv -f CUBRID/log /tmp/logs/cubrid_log
              mv -f cubrid-testtools/CTP/sql/log /tmp/logs/ctp_log
            fi
            mv -f CUBRID/log/coredump /tmp/logs/coredump
            # find /home -name "core.*" | xargs -I{} mv -f {} /tmp/logs
          when: always
      - store_test_results:
          path: /tmp/tests
      - store_artifacts:
          path: /tmp/logs

  collect-build-logs:
    description: "Collect build logs and store them"
    steps:
      - run:
          name: Store Build Logs
          command: |
            mkdir -p /tmp/build_logs
            mv -f build.log /tmp/build_logs
      - run:
          name: Store Commits
          command: |
            mkdir -p /tmp/build_logs
            git log | head -n 1000 > commits.log || true
            mv -f commits.log /tmp/build_logs
      - store_artifacts:
          path: /tmp/build_logs

# --------------------------------------------------
# 2. Reusable executors
# --------------------------------------------------
executors:
  cubrid-default:
    docker:
      - image: cubridci/cubridci:develop
    working_directory: /home

  cubrid-test-shell:
    docker:
      # - image: cubridci/cubridci:test_shell
      - image: twkang3219/ctp_image_shell:latest
    working_directory: /home

# --------------------------------------------------
# 3. Jobs
# --------------------------------------------------
jobs:
  build:
    executor: cubrid-default
    resource_class: xlarge
    environment:
      MAKEFLAGS: -j 8
    steps:
      - checkout
      - run:
          name: Submodules
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Build
          command: |
            scl enable devtoolset-8 -- /entrypoint.sh build
      - collect-build-logs
      - persist_to_workspace:
          root: .
          paths:
            - CUBRID

  test_job:
    parameters:
      e:
        type: executor
        default: cubrid-default
      test_suite:
        type: string
        default: "none"
      parallel_num:
        type: integer
        default: 1
    executor: << parameters.e >>
    resource_class: medium
    parallelism: << parameters.parallel_num >>
    environment:
      BASELINE: << pipeline.parameters.baseline >>
      RUN_SHELL_TEST: << pipeline.parameters.run_shell_test >>
      RUN_SQL_TEST: << pipeline.parameters.run_sql_test >>
      RUN_MEDIUM_TEST: << pipeline.parameters.run_medium_test >>
      RUN_PLCSQL_TEST: << pipeline.parameters.run_plcsql_test >>
      TEST_SUITE: << parameters.test_suite >>
      GITHUB_TOKEN: $GHI_TOKEN
    steps:
      - run:
          name: Skip tests if not enabled
          command: |
            if [ "${TEST_SUITE}" = "shell" ] && [ "${RUN_SHELL_TEST}" != "true" ]; then
              echo "Skipping shell tests because RUN_SHELL_TEST is false"
              circleci-agent step halt
            elif [ "${TEST_SUITE}" = "sql" ] && [ "${RUN_SQL_TEST}" != "true" ]; then
              echo "Skipping sql tests because RUN_SQL_TEST is false"
              circleci-agent step halt
            elif [ "${TEST_SUITE}" = "medium" ] && [ "${RUN_MEDIUM_TEST}" != "true" ]; then
              echo "Skipping medium tests because RUN_MEDIUM_TEST is false"
              circleci-agent step halt
            elif [ "${TEST_SUITE}" = "plcsql" ] && [ "${RUN_PLCSQL_TEST}" != "true" ]; then
              echo "Skipping plcsql tests because RUN_PLCSQL_TEST is false"
              circleci-agent step halt
            fi
      - attach-and-run-tests

# --------------------------------------------------
# 4. Workflows
# --------------------------------------------------
workflows:
  build_test:
    jobs:
      - build
      - test_job:
          name: test_medium
          requires: 
            - build
          test_suite: "medium"
      - test_job:
          name: test_sql
          requires:
            - build
          test_suite: "sql"
          parallel_num: 8
      - test_job:
          name: test_plcsql
          requires: 
            - build
          test_suite: "plcsql"
      - test_job:
          name: test_shell
          requires: 
            - build
          test_suite: "shell"
          e: cubrid-test-shell
          parallel_num: 30
