version: 2.1

# --------------------------------------------------
# Pipeline-level parameters (values passed from GitHub Actions)
# --------------------------------------------------
parameters:
  baseline:
    type: string
    default: ""
  run_shell_test:
    type: boolean
    default: false

# --------------------------------------------------
# 1. Reusable commands
# --------------------------------------------------
commands:
  attach-and-run-tests:
    description: "Attach workspace and run test scripts"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          shell: /bin/bash
          no_output_timeout: 20m
          # environment:
          #   _JAVA_OPTIONS: -Xmx1g
          command: |
            # Limit core files
            ulimit -c 1

            # Check out testcases and testtools (uses custom entrypoint script)
            /entrypoint.sh checkout

            # Handle specific cases for TEST_SUITE
            if [ "$TEST_SUITE" = "none" ]; then
              echo "TEST_SUITE is none"
              exit 1
            elif [ "$TEST_SUITE" = "plcsql" ]; then
              # Hack: run plcsql test via sql suite
              TEST_SUITE="sql"
              file_ext="sql"
              base_dir="cubrid-testcases"
              # glob_path="$base_dir/sql/{_05_plcsql,_35_fig_cake/plcsql}/**/*.sql"
              glob_path="$base_dir/sql/_35_fig_cake/plcsql/**/*.sql"
            elif [ "$TEST_SUITE" = "sql" ]; then
              file_ext="sql"
              base_dir="cubrid-testcases"
              rm -rf $base_dir/sql/_05_plcsql
              rm -rf $base_dir/sql/_35_fig_cake/plcsql
              # glob_path="$base_dir/$TEST_SUITE/_*/**/*.sql"
              glob_path="$base_dir/$TEST_SUITE/_01_object/**/*.sql"
            elif [ "$TEST_SUITE" = "shell" ]; then
              file_ext="sh"
              base_dir="cubrid-testcases-private-ex"
              rm -rf $base_dir/$TEST_SUITE/_25_unstable
              # glob_path="$base_dir/$TEST_SUITE/_01_utility/_03_start_server/**/*.sh"
              glob_path="$base_dir/$TEST_SUITE/_*/**/*.sh"
            else
              file_ext="sql"
              base_dir="cubrid-testcases"
              glob_path="$base_dir/$TEST_SUITE/_*/**/*.sql"
            fi

            circleci tests glob $glob_path | sed 's#^[^/]*/##' | circleci tests split --split-by=timings --timings-type=testname | tee tc.list
            cat tc.list | sed "s|^|$base_dir/|" > keep_files.txt
            find $base_dir -name "*.$file_ext" -type f | grep -v -f keep_files.txt | xargs -r rm -rf

            # Original command that had issues:   
            # find $glob_path -maxdepth 0 -type d -print0 | grep -vzZ -f tc.list | xargs -0 rm -rf

            HOME=$WORKDIR /home/cubrid-testtools/CTP/common/script/run_cubrid_install https://ftp.cubrid.org/CUBRID_Engine/nightly/daily_build/11.4.0.1693-6d1e147/drop/CUBRID-11.4.0.1693-6d1e147-Linux.x86_64.sh
            
            # Run the tests
            /entrypoint.sh test
      - run:
          name: Collect Logs
          command: |
            mkdir -p /tmp/logs
            cp /tmp/tests/*.xml /tmp/logs
            if [ "$TEST_SUITE" = "shell" ]; then
              mv -f cubrid-testtools/CTP/result/shell/current_runtime_logs /tmp/logs/ctp_log
              mv -f /tmp/tests/*.csv /tmp/logs
            else
              mv -f CUBRID/log /tmp/logs/cubrid_log
              mv -f cubrid-testtools/CTP/sql/log /tmp/logs/ctp_log
            fi
            find /home -name "core.*" | xargs -I{} mv -f {} /tmp/logs
          when: on_fail
      - store_test_results:
          path: /tmp/tests
      - store_artifacts:
          path: /tmp/logs

  collect-build-logs:
    description: "Collect build logs and store them"
    steps:
      - run:
          name: Store Build Logs
          command: |
            mkdir -p /tmp/build_logs
            mv -f build.log /tmp/build_logs
      - run:
          name: Store Commits
          command: |
            mkdir -p /tmp/build_logs
            git log | head -n 1000 > commits.log || true
            mv -f commits.log /tmp/build_logs
      - store_artifacts:
          path: /tmp/build_logs

# --------------------------------------------------
# 2. Reusable executors
# --------------------------------------------------
executors:
  cubrid-default:
    docker:
      - image: cubridci/cubridci:develop
    working_directory: /home

  cubrid-test-shell:
    docker:
      # - image: cubridci/cubridci:test_shell
      - image: twkang3219/ctp_image_shell:latest
    working_directory: /home

# --------------------------------------------------
# 3. Jobs
# --------------------------------------------------
jobs:
  build:
    executor: cubrid-default
    resource_class: xlarge
    environment:
      MAKEFLAGS: -j 8
    steps:
      - checkout
      - run:
          name: Submodules
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Build
          command: |
            scl enable devtoolset-8 -- /entrypoint.sh build
      - collect-build-logs
      - persist_to_workspace:
          root: .
          paths:
            - CUBRID

  test_job:
    parameters:
      e:
        type: executor
        default: cubrid-default
      test_suite:
        type: string
        default: "none"
      parallel_num:
        type: integer
        default: 1
    executor: << parameters.e >>
    resource_class: medium
    parallelism: << parameters.parallel_num >>
    environment:
      BASELINE: << pipeline.parameters.baseline >>
      RUN_SHELL_TEST: << pipeline.parameters.run_shell_test >>
      TEST_SUITE: << parameters.test_suite >>
      GITHUB_TOKEN: $GHI_TOKEN
    steps:
      - run:
          name: Skip shell tests if not enabled
          command: |
            if [ "${TEST_SUITE}" = "shell" ] && [ "${RUN_SHELL_TEST}" != "true" ]; then
              echo "Skipping shell tests because RUN_SHELL_TEST is false"
              circleci-agent step halt
            fi
      - attach-and-run-tests

  build-windows:
    machine:
      image: "windows-server-2019"
      resource_class: windows.large
      shell: powershell.exe -ExecutionPolicy Bypass
    environment:
      CMAKE_GENERATOR: "Visual Studio 15 2017"
      CMAKE_BUILD_PARALLEL_LEVEL: 10
      WITH_CCI: true
    steps:
      - checkout
      - run:
          name: Submodules
          command: |
            git submodule update --init --recursive
            git rm -f cubridmanager
      - run:
          name: Install dependencies
          command: |
            choco upgrade chocolatey -y
            choco install openjdk8redhatbuild --no-progress -y
            choco install cmake --version=3.26.3 --installargs 'ADD_CMAKE_TO_PATH=System' --no-progress -y
            choco install winflexbison wixtoolset --no-progress -y
            choco install ant --ignore-dependencies --no-progress -y
            choco install visualstudio2017buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.ATLMFC --includeRecommended" --no-progress -y
      - run:
          name: CMake Configure
          command: |
            cmake -E make_directory build
            cmake -E chdir build cmake -G $env:CMAKE_GENERATOR -A x64 -DWITH_CCI=$env:WITH_CCI -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
      - run:
          name: CMake Build
          command: |
            cmake --build build --config RelWithDebInfo --parallel $env:CMAKE_BUILD_PARALLEL_LEVEL

# --------------------------------------------------
# 4. Workflows
# --------------------------------------------------
workflows:
  build_test:
    jobs:
      # - build
      # - test_job:
      #     name: test_medium
      #     requires: 
      #       - build
      #     test_suite: "medium"
      # - test_job:
      #     name: test_sql
      #     requires:
      #       - build
      #     test_suite: "sql"
      #     parallel_num: 8
      # - test_job:
      #     name: test_plcsql
      #     requires: 
      #       - build
      #     test_suite: "plcsql"
      - test_job:
          name: test_shell
          # requires: 
          #   - build
          test_suite: "shell"
          e: cubrid-test-shell
          parallel_num: 1
      # - build-windows:
      #     requires: 
      #       - build