#!/bin/bash
# 
# cubrid ha     This shell script takes care of starting and stopping
#               the CUBRID HA service
#
# chkconfig: 2345 98 05
# description: cubrid ha start/stop script  
#
# ts:4

### BEGIN INIT INFO
#
# Short-Description: CUBRID HA
# Provides: CUBRID      
# Default-Start: 3 5
# Default-Stop: 0 6
### END INIT INFO


# Source function library.
. /etc/init.d/functions

# return code
HA_SUCCESS=0
HA_FAILED=1

US=`uname -n`
WHOAMI=`whoami`
RETVAL=0
prog=cubrid-ha

### user specific environment ##################
CUBRID_USER=siwankim

if [ $WHOAMI = "root" ]; then
	CUBRID_DATABASES=`su - $CUBRID_USER -c 'printenv CUBRID_DATABASES'`
	CUBRID_HOME=`su - $CUBRID_USER -c 'printenv CUBRID'`
else
	CUBRID_USER=$WHOAMI
	CUBRID_HOME=$CUBRID
	export PATH=$PATH:$CUBRID_HOME/bin
fi

if [ -z $REPL_LOG_HOME ]; then
	REPL_LOG_HOME=$CUBRID_DATABASES
fi
################################################

sudo_cubrid_heartbeat () {
	[ "$#" -ne 1 ] && return

	if [ $WHOAMI = "root" ]; then
		su - $CUBRID_USER -c "cubrid heartbeat $1"
	else
		sh -c "cubrid heartbeat $1"
	fi

	if [ "$?" -eq 0 ]; then
		return 0
	else
		return 1
	fi
}

start() {
	if sudo_cubrid_heartbeat "start" &> /dev/null; then
		RETVAL=$HA_SUCCESS	
	else
		RETVAL=$HA_FAILED

	fi

	if [ $RETVAL -eq $HA_SUCCESS ]; then
		echo -n $"Starting $prog: "
		success
		echo
	else
		echo -n $"Starting $prog: "
		failure
		echo
	fi	

	[ $WHOAMI = "root" ] && touch /var/lock/subsys/$prog

	return $RETVAL
}

stop() {
	if sudo_cubrid_heartbeat "stop" &> /dev/null; then
		RETVAL=$HA_SUCCESS	
	else
		RETVAL=$HA_FAILED

	fi

	if [ $RETVAL -eq $HA_SUCCESS ]; then
		echo -n $"Stopping $prog: "
		success
		echo
	else
		echo -n $"Stopping $prog: "
		failure
		echo
	fi	

	return $RETVAL
}

status() {
	if sudo_cubrid_heartbeat "status"; then
		RETVAL=$HA_SUCCESS	
	else
		RETVAL=$HA_FAILED

	fi

	if [ $RETVAL -eq 0 ]; then
		echo -n $"Status $prog: "
		success
		echo
	else
		echo -n $"Status $prog: "
		failure
		echo
	fi	

	return $RETVAL
}

reload() {
	if sudo_cubrid_heartbeat "reload" &> /dev/null; then
		RETVAL=$HA_SUCCESS	
	else
		RETVAL=$HA_FAILED

	fi

	if [ $RETVAL -eq 0 ]; then
		echo -n $"Reloading $prog: "
		success
		echo
	else
		echo -n $"Reloading $prog: "
		failure
		echo
	fi	

	return $RETVAL
}

deactivate() {
	if sudo_cubrid_heartbeat "deact" &> /dev/null; then
		RETVAL=$HA_SUCCESS	
	else
		RETVAL=$HA_FAILED

	fi

	if [ $RETVAL -eq 0 ]; then
		echo -n $"deactivate $prog: "
		success
		echo
	else
		echo -n $"deactivate $prog: "
		failure
		echo
	fi	

	return $RETVAL
}

activate() {
	if sudo_cubrid_heartbeat "act" &> /dev/null; then
		RETVAL=$HA_SUCCESS	
	else
		RETVAL=$HA_FAILED

	fi


	if [ $RETVAL -eq 0 ]; then
		echo -n $"activate $prog: "
		success
		echo
	else
		echo -n $"activate $prog: "
		failure
		echo
	fi	

	return $RETVAL
}

if [ $CUBRID_DATABASES"x" = "x" ]; then
	echo -ne "$prog: CUBRID_DATABASES environment does not exist. \n"
	echo -n $"$prog: " 
	failure
	exit 0
fi

case "$1" in 
  start)
	start	
	;;
  stop)
	stop
	;;
  status)
	status
	;;	
  reload)
	reload
	;;
  deact)
	deactivate
	;;
  act)
	activate
	;;
  *)	
	echo $"Usage $0 {start|stop|status|reload|deact|act}"
	exit 1
esac

exit 0
