#!/bin/tcsh -f

set review_file = $1
if ($review_file == "") then
        exit
endif

set review_dir = $HOME/.code_review/$$
mkdir -p $review_dir

gzip -d -c $review_file > $review_dir/CODE_REVIEW.tar
cd $review_dir
tar xvf CODE_REVIEW.tar
cd CODE_REVIEW
meld old new
cd ..
/bin/rm -rf CODE_REVIEW CODE_REVIEW.tar
cd ..
rmdir $$
