#include "dbtype_def.h"
#include "dbtype_function.h"
#include "object_primitive.h"
#include <assert.h>

namespace Cast
{
  using Castfunc = void (*)(const DB_VALUE *, const DB_VALUE *);
  const Castfunc CastFunctionTable[static_cast < int >(DB_TYPE::DB_TYPE_LAST) + 1][static_cast <
										   int >(DB_TYPE::DB_TYPE_LAST) + 1] = {
    /* DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0 */
    {
     Self,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Error,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_INTEGER = 1 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Self,			// DB_TYPE_INTEGER = 1
     Error,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_FLOAT = 2 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_DOUBLE = 3 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_STRING, DB_TYPE_VARCHAR = 4 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_OBJECT = 5 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_SET = 6 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_MULTISET = 7 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_ELO = 9 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_TIME = 10 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_DATE = 12 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_MONETARY = 13 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_VARIABLE = 14 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_SUB = 15 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_POINTER = 16 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Error,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Self,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_ERROR = 17 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Self,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_VOBJ = 19 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_OID = 20 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_DB_VALUE = 21 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_NUMERIC = 22 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_BIT = 23 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_VARBIT = 24 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_CHAR = 25 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_NCHAR = 26 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_VARNCHAR = 27 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_RESULTSET = 28 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_MIDKEY = 29 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_TABLE = 30 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_BIGINT = 31 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_DATETIME = 32 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_BLOB = 33 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_CLOB = 34 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_ENUMERATION = 35 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_TIMESTAMPTZ = 36 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_TIMESTAMPLTZ = 37 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_DATETIMETZ = 38 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_DATETIMELTZ = 39 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
    /* DB_TYPE_JSON = 40 */
    {
     Error,			// DB_TYPE_FIRST, DB_TYPE_UNKNOWN, DB_TYPE_NULL = 0
     Error,			// DB_TYPE_INTEGER = 1
     Self,			// DB_TYPE_FLOAT = 2
     Error,			// DB_TYPE_DOUBLE = 3
     Error,			// DB_TYPE_STRING, DB_TYPE_VARCHAR = 4
     Error,			// DB_TYPE_OBJECT = 5
     Error,			// DB_TYPE_SET = 6
     Error,			// DB_TYPE_MULTISET = 7
     Error,			// DB_TYPE_SEQUENCE, DB_TYPE_LIST = 8
     Error,			// DB_TYPE_ELO = 9
     Error,			// DB_TYPE_TIME = 10
     Error,			// DB_TYPE_TIMESTAMP , DB_TYPE_UTIME = 11
     Error,			// DB_TYPE_DATE = 12
     Error,			// DB_TYPE_MONETARY = 13
     Error,			// DB_TYPE_VARIABLE = 14
     Error,			// DB_TYPE_SUB = 15
     Error,			// DB_TYPE_POINTER = 16
     Error,			// DB_TYPE_ERROR = 17
     Error,			// DB_TYPE_SHORT, DB_TYPE_SMALLINT = 18
     Error,			// DB_TYPE_VOBJ = 19
     Error,			// DB_TYPE_OID = 20
     Error,			// DB_TYPE_DB_VALUE = 21
     Error,			// DB_TYPE_NUMERIC = 22
     Error,			// DB_TYPE_BIT = 23
     Error,			// DB_TYPE_VARBIT = 24
     Error,			// DB_TYPE_CHAR = 25
     Error,			// DB_TYPE_NCHAR = 26
     Error,			// DB_TYPE_VARNCHAR = 27
     Error,			// DB_TYPE_RESULTSET = 28
     Error,			// DB_TYPE_MIDKEY = 29
     Error,			// DB_TYPE_TABLE = 30
     Error,			// DB_TYPE_BIGINT = 31
     Error,			// DB_TYPE_DATETIME = 32
     Error,			// DB_TYPE_BLOB = 33
     Error,			// DB_TYPE_CLOB = 34
     Error,			// DB_TYPE_ENUMERATION = 35
     Error,			// DB_TYPE_TIMESTAMPTZ = 36
     Error,			// DB_TYPE_TIMESTAMPLTZ = 37
     Error,			// DB_TYPE_DATETIMETZ = 38
     Error,			// DB_TYPE_DATETIMELTZ = 39
     Error,			// DB_TYPE_JSON = 40
     },
  }
}				// namespace Cast
