/*
 * Copyright (C) 2009 Search Solution Corporation. All rights reserved by Search
 * Solution.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met: -
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer. - Redistributions in binary
 * form must reproduce the above copyright notice, this list of conditions and
 * the following disclaimer in the documentation and/or other materials provided
 * with the distribution. - Neither the name of the <ORGANIZATION> nor the names
 * of its contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * 
 */
package com.cubrid.cubridmanager.ui.spi.model;

/**
 * 
 * This enum type provide all CUBRID node type
 * 
 * @author pangqiren
 * @version 1.0 - 2009-6-4 created by pangqiren
 */
public enum CubridNodeType {
	SERVER,
	DATABASE_FOLDER,
	DATABASE,
	USER_FOLDER,
	USER,
	JOB_FOLDER,
	BACKUP_PLAN_FOLDER,
	BACKUP_PLAN,
	QUERY_PLAN_FOLDER,
	QUERY_PLAN,
	DBSPACE_FOLDER,
	GENERIC_VOLUME_FOLDER,
	GENERIC_VOLUME,
	DATA_VOLUME_FOLDER,
	DATA_VOLUME,
	INDEX_VOLUME_FOLDER,
	INDEX_VOLUME,
	TEMP_VOLUME_FOLDER,
	TEMP_VOLUME,
	LOG_VOLUEM_FOLDER,
	ACTIVE_LOG_FOLDER,
	ACTIVE_LOG,
	ARCHIVE_LOG_FOLDER,
	ARCHIVE_LOG,	
	TABLE_FOLDER,
	VIEW_FOLDER,
	SYSTEM_TABLE_FOLDER,
	SYSTEM_TABLE,
	SYSTEM_VIEW_FOLDER,
	SYSTEM_VIEW,
	USER_TABLE_FOLDER,
	USER_TABLE,
	USER_VIEW_FOLDER,
	USER_VIEW,
	USER_PARTITIONED_TABLE_FOLDER,
	USER_PARTITIONED_TABLE,	
	STORED_PROCEDURE_FOLDER,
	STORED_PROCEDURE_FUNCTION_FOLDER,
	STORED_PROCEDURE_PROCEDURE_FOLDER,
	STORED_PROCEDURE_FUNCTION,
	STORED_PROCEDURE_PROCEDURE,
	TRIGGER_FOLDER,
	TRIGGER,
	SERIAL_FOLDER,
	SERIAL,
	BROKER_FOLDER,
	BROKER,
	BROKER_SQL_LOG_FOLDER,
	BROKER_SQL_LOG,
	STATUS_MONITOR_FOLDER,
	STATUS_MONITOR_TEMPLATE,
	LOGS_FOLDER,
	LOGS_BROKER_FOLDER,
	LOGS_BROKER_ACCESS_LOG_FOLDER,
	LOGS_BROKER_ACCESS_LOG,
	LOGS_BROKER_ERROR_LOG_FOLDER,
	LOGS_BROKER_ERROR_LOG,
	LOGS_BROKER_ADMIN_LOG_FOLDER,
	LOGS_BROKER_ADMIN_LOG,
	LOGS_MANAGER_FOLDER,
	LOGS_MANAGER_ACCESS_LOG,
	LOGS_MANAGER_ERROR_LOG,
	LOGS_SERVER_FOLDER,
	LOGS_SERVER_DATABASE_FOLDER,
	LOGS_SERVER_DATABASE_LOG

}
