#define RELEASE_STRING 9.1.0
#define MAJOR_RELEASE_STRING 9.1
#define BUILD_NUMBER 9.1.0.0092
#define MAJOR_VERSION 9
#define MINOR_VERSION 1
#define PATCH_VERSION 0
#define BUILD_SERIAL_NUMBER 0092
#define VERSION_STRING "9.1.0.0092"
#define PRODUCT_STRING "9.1"
#define PACKAGE_STRING "CUBRID 9.1"

