// ArchiveLog.h: interface for the CArchiveLog class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_ARCHIVELOG_H__D6623FA1_2F23_43EE_9FC0_E1B0D0E93125__INCLUDED_)
#define AFX_ARCHIVELOG_H__D6623FA1_2F23_43EE_9FC0_E1B0D0E93125__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

class CArchiveLog  
{
public:
	CArchiveLog();
	virtual ~CArchiveLog();

};

#endif // !defined(AFX_ARCHIVELOG_H__D6623FA1_2F23_43EE_9FC0_E1B0D0E93125__INCLUDED_)
