/*
 * Copyright 2008 Search Solution Corporation
 * Copyright 2016 CUBRID Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */
// ManageRegistry1.h: interface for the CManageRegistry class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_MANAGEREGISTRY1_H__B1E6E229_AFA1_42FC_950E_43FF6DE9554A__INCLUDED_)
#define AFX_MANAGEREGISTRY1_H__B1E6E229_AFA1_42FC_950E_43FF6DE9554A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

class CManageRegistry  
{
public:
	CManageRegistry();
	virtual ~CManageRegistry();

};

#endif // !defined(AFX_MANAGEREGISTRY1_H__B1E6E229_AFA1_42FC_950E_43FF6DE9554A__INCLUDED_)
