// ManageRegistry1.cpp: implementation of the CManageRegistry class.
//
//////////////////////////////////////////////////////////////////////

#include "stdafx.h"
#include "unitray.h"
#include "ManageRegistry1.h"

#ifdef _DEBUG
#undef THIS_FILE
static char THIS_FILE[]=__FILE__;
#define new DEBUG_NEW
#endif

//////////////////////////////////////////////////////////////////////
// Construction/Destruction
//////////////////////////////////////////////////////////////////////

CManageRegistry::CManageRegistry()
{

}

CManageRegistry::~CManageRegistry()
{

}
