// ManageRegistry1.h: interface for the CManageRegistry class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_MANAGEREGISTRY1_H__B1E6E229_AFA1_42FC_950E_43FF6DE9554A__INCLUDED_)
#define AFX_MANAGEREGISTRY1_H__B1E6E229_AFA1_42FC_950E_43FF6DE9554A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

class CManageRegistry  
{
public:
	CManageRegistry();
	virtual ~CManageRegistry();

};

#endif // !defined(AFX_MANAGEREGISTRY1_H__B1E6E229_AFA1_42FC_950E_43FF6DE9554A__INCLUDED_)
