//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by unitray.rc
//
#define ID_UCMD_ADD                     2
#define IDC_UCP_APPLY                   3
#define ID_UCMD_DROP                    3
#define ID_UCMD_RESTART                 5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_UNITRATYPE                  129
#define IDI_SMILE                       130
#define IDR_POPUP                       133
#define IDR_POPUP_KOREAN                133
#define IDD_STARTSERVER                 134
#define IDR_POPUP_ENGLISH               134
#define IDD_STOPSERVER                  135
#define IDD_PROPERTY                    136
#define IDD_SHOWRUNDB                   137
#define IDD_UC_PROPERTY                 140
#define IDD_UCP_DETAIL                  141
#define IDD_UCP_VAS                     143
#define IDD_UCP_WAS                     144
#define IDD_UC_MONITOR                  145
#define IDD_UCM_DETAIL                  148
#define IDD_DIALOG1                     151
#define IDD_STOP_TARGET_DB              153
#define IDR_STOP                        154
#define IDD_START_TARGET_DB             154
#define IDR_START                       155
#define IDR_ING                         156
#define IDD_OPTION_DIALOG               157
#define IDD_FILEDIALOG                  158
#define IDD_DIALOG2                     159
#define IDD_DIALOG3                     160
#define IDC_CURSOR1                     162
#define IDI_ICON1                       163
#define IDB_BITMAP1                     164
#define IDI_ICON2                       171
#define ID_SU_OK                        1005
#define ID_SU_CANCEL                    1006
#define ID_SS_OK                        1011
#define ID_SS_CANCEL                    1012
#define ID_PRO_OK                       1014
#define ID_PRO_CANCEL                   1015
#define IDC_PRO_DBPATH                  1017
#define IDC__PRO_STATIC                 1018
#define IDC_PRO_TXT_DBPATH              1018
#define IDC_PRO_HOST                    1019
#define IDC__PRO_STATIC2                1020
#define IDC_PRO_TXT_HOST                1020
#define IDC_PRO_LOGPATH                 1021
#define IDC__PRO_STATIC3                1022
#define IDC_PRO_TXT_LOGPATH             1022
#define IDC_PRO_PERMANENT               1024
#define IDC_EDIT1                       1025
#define IDC_UCP_SMID                    1025
#define IDC_SRD_LIST                    1026
#define IDC_UCPD_BNAME                  1026
#define IDC_UCPD_PORT                   1027
#define IDC_UCPD_SMID                   1028
#define IDC_UCPD_MIN                    1029
#define IDC_UCPD_MAX                    1030
#define IDC_PRO_LIST                    1031
#define IDC_UCPD_SIZELIMIT              1031
#define IDC_VAS_SROOT                   1032
#define IDC_SRD_GPRO                    1033
#define IDC_VAS_FU                      1033
#define IDC_SRD_DPRO                    1034
#define IDC_VAS_CSIZE                   1034
#define IDC_SRD_IPRO                    1035
#define IDC_SU_LIST                     1035
#define IDC_VAS_PGAP                    1035
#define IDC_SRD_TPRO                    1036
#define IDC_SS_LISTDB                   1036
#define IDC_UCPD_TIMETOKILL             1036
#define IDC_CUBRID_VERSION              1037
#define IDC_UCPD_STIMEOUT               1037
#define IDC_UNICAS_VERSION              1038
#define IDC_UCP_LIST                    1038
#define IDC_UCPD_QUEUESIZE              1038
#define IDC_UCP_NEW                     1039
#define IDC_UCP_UPDATE                  1040
#define IDC_UCP_DELETE                  1041
#define IDC_UCP_CANCEL                  1042
#define IDC_VAS_ERRLOG                  1045
#define IDC_UCPD_AUTOADD                1046
#define IDC_UCPD_MORE                   1047
#define IDC_UCPD_S_ONOFF                1055
#define IDC_UCP_LOGFILE                 1056
#define IDC_UCPD_SECURITY_ONOFF         1056
#define IDC_VAS_SESSION                 1057
#define IDC_WAS_COOKIE                  1058
#define IDC_VAS_ENC_ONOFF               1058
#define IDC_WAS_TRIM                    1059
#define IDC_UCPD_STYPE                  1060
#define IDC_VAS_CHECKOID                1060
#define IDC_WAS_ENC_ONOFF               1060
#define IDC_UCPD_LOGDIR                 1061
#define IDC_UCPD_LOGBACKUP_ONOFF        1063
#define IDC_UCPD_SQLT_ONOFF             1064
#define IDC_UCPD_ALOG_ONOFF             1065
#define IDC_UCPD_SQLTIME                1066
#define IDC_UCPD_SECURIY_FILE           1067
#define IDC_UCPD_ENV_FILE               1068
#define IDC_WAS_SESSION                 1069
#define IDC_WAS_CHECKOID                1070
#define IDC_WAS_SROOT                   1071
#define IDC_WAS_FU                      1073
#define IDC_WAS_ERRLOG                  1075
#define IDC_WAS_DELIMITER               1076
#define IDC_UCPD_OK                     1077
#define IDC_UCPD_CANCEL                 1078
#define IDC_VAS_OK                      1079
#define IDC_VAS_CANCEL                  1080
#define ID_WAS_OK                       1081
#define IDC_WAS_CANCEL                  1082
#define IDC_UCM_LIST                    1083
#define ID_UCMD_END                     1085
#define ID_UCM_END                      1086
#define IDC_UCMD_LIST                   1087
#define IDC_ABT_MSG                     1088
#define ID_UCM_MONITOR                  1089
#define IDC_ABT_COPYRIGHTS              1089
#define ID_UCM_SERVICE_ONOFF            1090
#define IDC_SRD_TXT_GPRO                1093
#define IDC_ABT_COPYRIGHTS2             1093
#define IDC_SRD_TXT_DPRO                1094
#define IDC_SRD_TXT_IPRO                1095
#define IDC_SRD_TXT_TPRO                1096
#define IDC_UCP_MASTERINFO              1097
#define IDC_UCP_TXT_SMID                1098
#define IDC_UCP_TXT_LOGFILE             1099
#define IDC_UCPD_TXT_CP                 1100
#define IDC_UCPD_TXT_AS                 1101
#define IDC_UCPD_TXT_LI                 1102
#define IDC_UCPD_TXT_SC                 1103
#define IDC_UCPD_TXT_ETC                1104
#define IDC_UCPD_TXT_BNAME              1105
#define IDC_UCPD_TXT_STYPE              1106
#define IDC_UCPD_TXT_PORT               1107
#define IDC_UCPD_TXT_SMID               1108
#define IDC_UCPD_TXT_MIN                1109
#define IDC_UCPD_TXT_MAX                1110
#define IDC_UCPD_TXT_SIZELIMIT          1111
#define IDC_UCPD_TXT_LOGDIR             1112
#define IDC_UCPD_TXT_SQLTIME            1113
#define IDC_UCPD_TXT_SECURIY_FILE       1114
#define IDC_UCPD_TXT_ENV_FILE           1115
#define IDC_UCPD_TXT_TIMETOKILL         1116
#define IDC_UCPD_TXT_STIMEOUT           1117
#define IDC_UCPD_TXT_QUEUESIZE          1118
#define IDC_VAS_TXT_SROOT               1119
#define IDC_VAS_TXT_FU                  1120
#define IDC_VAS_TXT_ERRLOG              1121
#define IDC_VAS_TXT_CSIZE               1122
#define IDC_VAS_TXT_PGAP                1123
#define IDC_WAS_TXT_SROOT               1124
#define IDC_WAS_TXT_FU                  1125
#define IDC_WAS_TXT_ERRLOG              1126
#define IDC_WAS_TXT_DELIMITER           1127
#define IDC_BUTTON1                     1128
#define IDC_BUTTON2                     1129
#define IDC_LIST1                       1130
#define IDC_LIST2                       1131
#define IDC_BUTTON4                     1133
#define IDC_CHECK1                      1133
#define IDC_BUTTON5                     1134
#define IDC_CHECK2                      1134
#define IDC_BUTTON6                     1135
#define IDC_CHECK3                      1135
#define IDC_BUTTON7                     1136
#define IDC_BUTTON8                     1137
#define IDC_BUTTON9                     1138
#define IDC_FILE_TEXT                   1138
#define IDC_BUTTON10                    1139
#define IDC_REFRESH                     1139
#define IDC_BUTTON11                    1140
#define IDC_BUTTON12                    1141
#define IDC_HIDDEN_CMD                  1141
#define IDC_BUTTON13                    1142
#define IDC_ABOUT_UNITRAY               1142
#define IDC_BUTTON14                    1143
#define IDC_BUTTON15                    1144
#define IDC_BUTTON16                    1147
#define IDC_BUTTON17                    1148
#define IDC_BUTTON18                    1149
#define IDC_BUTTON19                    1150
#define PU_ABOUT                        32776
#define PU_STOP                         32780
#define PU_UNICAS_SHUTDOWN              32781
#define PU_STOPSERVER                   32782
#define PU_STARTSERVER                  32783
#define PU_PROPERTY                     32784
#define PU_UNICAS_STARTUP               32785
#define PU_UNICASPRO                    32786
#define PU_CREATEDB                     32795
#define PU_LISTRUNDB                    32796
#define PU_UNICAS_STARTNAMED            32800
#define PU_UNICAS_MONITOR               32801
#define PU_UNICAS_RESTARTUP             32803
#define PU_UNITOOL_VSQL                 32804
#define PU_UNITOOL_EMANAGER             32805
#define PU_EASY_STARTUP                 32807
#define PU_EASY_OPTION                  32809
#define ID_EMSAUTOSTARTLOG              32810
#define ID_EMSJSSTARTLOG                32811
#define PU_EASY_STOP                    32812
#define PU_LISTSERVER                   65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1143
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
