
$
$ Copyright (C) 2008 Search Solution Corporation. All rights reserved by Search Solution. 
$
$   This program is free software; you can redistribute it and/or modify 
$   it under the terms of the GNU General Public License as published by 
$   the Free Software Foundation; either version 2 of the License, or
$   (at your option) any later version.
$
$  This program is distributed in the hope that it will be useful, 
$  but WITHOUT ANY WARRANTY; without even the implied warranty of 
$  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
$  GNU General Public License for more details. 
$
$  You should have received a copy of the GNU General Public License 
$  along with this program; if not, write to the Free Software 
$  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
$

$
$ $Id$
$
$ cubrid.msg
$

$set 1 MSGCAT_SET_GENERAL
1 \n%1$s\n\n
2 Copyright (C) 2008 Search Solution Corporation. All rights reserved by Search Solution.\n
3 Telif Hakkı Bilgisi \n
5 tamsayı argüman değeri bulunmamaktadır "%1$s"\n
6 floating argüman değeri bulunmamaktadır "%1$s"\n
7 kayıp argüman %1$s\n
8 argüman çoğaltın `%1$s'
9 Argüman için kayıp değer `%1$s'
10 Bilinmeyen argüman `%1$s'
11 Beklenmeyen konumsal argüman`%1$s'
12 Verilen hiçbir argüman tanımlanmıyor
13 Argüman ayrıştırma için depolama ayıramadı
14 Argüman dize maksimum uzunluğu aşıyor: %1$s
15 Argüman ayrıştırma için katalog içindeki geçersiz ileti numarası %1$d.
16 [ayarlar]
17 Ayarlar:

$set 4 MSGCAT_SET_PARAMETER
2 %1$s rehber içinde bulunmamakta.  Oluşturma %2$s içinde ".".
3 Açılmıyor %1$s. Yapılandırma dosyası oluşturulamıyor.
4 Yapılandırma dosyası %2$s satır %1$d yazılamıyor.
6 Sistem yapılandırma dosyası "%1$s" erişilemiyor: %2$s
7 HOME ayarlanmadı
8 Gerekli parametre "%1$s" hiçbir değeri yoktur.
9 Konfigürasyon dosyası "%1$s" açılamıyor: %2$s
10 Dosya '%1$s' içinde '%3$s' parametresinde satır %2$d : 
11 Çevre değişkeni %1$s: 
12 Tanınmayan anahtar kelime.
13 Değer türü,parametresi türü ile eşleşmiyor.
14 Değeri saklamak için bellek ayrılamıyor.
15 Dize değeri Sonlandırılmamış.
16 Değer aralığı dışındadır.
17 UNIX hatası: %1$s
18 Görüntülenebilir mesaj yok.
19 Değer aralığı dışındadır.Varsayılan değere sıfırlama.
20 Anahtar = '%1$s' değeri = %2$d Varsayılan Değer = %3$d\n
21 Anahtar = '%1$s' değeri = %2$f varsayılan değer = %3$f\n
22 Reddedilen parametre
23 '%1$s' ve '%2$s' parametreler birlikte kullanılamaz.\n
31 '%1$s' parametresi:

$set 5 MSGCAT_SET_ERROR
1 Hata kodu %1$d eksik mesaj.
2 Dahili sistem hatası: daha fazla ayrıntılı bilgi mevcut bulunmamaktadır.
3 Sanal bellek harici: %1$lld bayt bellek ayıramadı.
4 Kesildi.
5 Anahtar = "%1$s" karma tablosu "%2$s" bulunamadı.
6 NULL bellek karma tablo bir karma tablo işlevi sağlanmıştır.
7 Sayfa sayısı için yanlış bir değer %2$d ile disk birimi "%1$s" biçimlendirmek için çalışıyorum.
8 Formatında disk birimi için açılamıyor "%1$s" %2$d sayfaları (%3$lld bayt).
9 Yeterli boş alan formatta disk birimi için açılamıyor "%1$s" %2$d sayfaları (%3$lld Kbyte). Kullanılabilir alanı %4$d sayfa (%5$lld Kbyte) olduğunu.
10 Disk birimi "%1$s" monte etmeye uygun değil.
11 Disk birimi "%1$s" monte etmeye uygun değil. Veritabanı "%2$s", hangi disk birimi ait, %6$s yılından bu yana ev sahibi %5$s süreci %4$d kullanıcı %3$s tarafından kullanılıyor.
12 Problem sökme değeri "%1$s".
13 I/O hatası oluştu %1$d sayfası degeri "%2$s" okunurken.
14 I/O hatası oluştu %1$d sayfası değeri "%2$s" yazılırken.
15 Sayfa yazmaya uygun değil %1$d değeri "%2$s" işletim sistemi cihazı için yeterli boş alan.
16 Disk birimini "%1$s" den "%2$s" yeniden adlandırmak uygun değil.
17 İç Hata: ayırmanın sayfa id %1$d "%2$s" hacim getiriliyor.
18 Tüm sayfa bufferlar onarıldı(LRU: %1$d).
19 İç hata: sayfa ptr = %1$p %2$d sayfanın hacimi "%3$s" onarılmadı.
20 İç hata: bilinmeyen sayfa ptr = %1$p.
21 İç hata: bilinmiyor sektörü %1$d hacim "%2$s".
22 İç hata: bilinmeyen sayfa %1$d hacim "%2$s".
23 İç hata: disk sistemi sayfa ayırması için çalışıyor %1$d "%2$s" değeri.
24 Alan dışı yoğunluklar "%1$s". toplam sayfa numarası = %2$d, toplam boş sayfa sayısı = %3$d.
25 Alan dışı yoğunluklar veri ile ana depolama amaçlı olarak. toplam sayfa sayısı = %1$d, toplam boş sayfa sayısı = %2$d.
26 Alan dışı yoğunluklar indeks ile ana depolama amaçlı olarak. toplam sayfa sayısı = %1$d, toplam boş sayfa sayısı = %2$d.
27 Alan dışı yoğunluklar genel depolama amaı ile. toplam sayfa sayısı = %1$d, toplam boş sayfa sayısı = %2$d.
28 Alan dışı yoğunluklar ana depolama amaçlı olarak geçici veri ile. toplam sayfa sayısı = %1$d, toplam boş sayfa sayısı = %2$d.
29 Yoğunluklar için yer bildirimi dışında sürecek "%1$s". toplam sayfa sayısı = %2$d, toplam boş sayfa sayısı = %3$d.
30 Yoğunluklar için yer bildirimi dışında sürecek ana depolama amaçlı olarak veri ile.. toplam sayfa sayısı = %1$d, toplam boş sayfa sayısı = %2$d.
31 Yoğunluklar için yer bildirimi dışında sürecek ana depolama amaçlı olarak indeks. toplam sayfa sayısı = %1$d, toplam boş sayfa sayısı = %2$d.
32 Yoğunluklar için yer bildirimi dışında sürecek genel depolama amacı ile. toplam sayfa sayısı = %1$d, toplam boş sayfa sayısı = %2$d.
33 Yoğunluklar için yer bildirimi dışında sürecek ana depolama amaçlı olarak geçici veri ile. toplam sayfa sayısı = %1$d, toplam boş sayfa sayısı = %2$d.
34 İç hata: %1$d nth sayfa dosyası %2$d yoğunluk "%3$s" için aralık dışında. Sayfa sayısı %4$d vardır.
35 İç hata: Bilinmeyen hacmi belirteç %1$d.
36 Veritabanı içinde alandışı disk alanı. İstenen sayfa(lar) sayısı = %1$d.
37 Yoğunluk içinde alandısşı disk alanı "%1$s". İstenen sayfa(lar) sayısı = %2$d.
38 İç hata: Bilinmeyen dosya VFID %1$d|%2$d.
39 İç hata: Page %1$d|%2$d(yoğunluk "%3$s") odosya VFID %4$d|%5$d(yoğunluk "%6$s") geçersiz/tahsisi haritaya göre ayrılmamış.
40 İç hata: %1$d beklenen sonuçlar, %2$d dosya için bulunan sayfaları VFID %3$d|%4$d(yoğunluk "%5$s").
41 İç hata: Page %1$d|%2$d(yoğunluk "%3$s") dosya VFID parçası değildir %4$d|%5$d(yoğunluk "%6$s").
42 Sayfasına bağlantılı kayıtları yenilenmez %1$d yoğunluğu "%2$s".
43 İç hata: %1$d sayfa hacmi "%2$s" bozuk olabilir. %3$d kayıtları %4$d beklenen zaman kuruldu.
44 Yerleşmiş sayfada uygun alan bulunmamakta %1$d yoğunluk "%2$s".
45 Yer %1$d safada %2$d yoğunluğu "%3$s" demirlemiş bir kayıt tahsis edilir. Yeni bir kayıt buraya işlenemez.
46 İç hata: yer %1$d sayfada %2$d yuğunluğu "%3$s" ayrılmamaktadır.
47 Yoğunluğunda bir yığın dosya oluşturulamıyor "%1$s".
48 Silinen nesneye erişim %1$d|%2$d|%3$d.
49 İç hata: nesne sınıfı %1$d|%2$d|%3$d bilinmeyen.
50 İç hata: nesne taşınma kaydı %1$d|%2$d|%3$d bozulmuş olabilir.
51 İç hata: nesne %1$d|%2$d|%3$d bozulmuş olabilir.
52 İç hata: nesne taşması adresi %1$d|%2$d|%3$d bozulmuş olabilir.
53 Nesne getiriliyor %1$d|%2$d|%3$d sadece kendi OID atanmıştır.
54 İç hata: %1$d sayfa uzunluğunda bir nesne işlemek için çalışıyor.Bir nesne için izin verilen maksimum boyutu %2$d sayfadır.
55 İç hata: Bir sayfa döngüsü başvuru sayfasında tespit edildi %1$d|%2$d yardım dosyası %3$d|%4$d|%5$d.
56 İç hata: bilinmeyen uzatılabilen karma dosyası (Yoğunluk id: %1$d Dosya id: %2$d) sayfa (Yoğunluk id: %3$d Sayfa id: %4$d) belirtildi.
57 Anahtar uzatılabilen karma yapısı mevcut değildir.
58 Dize "%1$s" yerleşmiş sayfaya sığmayacak kadar uzun.
59 İç hata: Belirtilen anahtar türü %1$d uzatılabilen karma yapısı için geçerli değildir.
60 İç hata: uzatılabilen karma yapısı bozulmuş olabilir.
61 İç hata: uzatılabilen karma yapının dizini kök sayfası(Yoğunluk id: %1$d Dosya id: %2$d Sayfa id: %3$d) bozulmuş olabilir.
62 İç hata: kayıt sıralama %1$d (boyut %2$d) sayfa içine uygun değil; izin verilen maksimum boyutu %3$d.
63 İç hata: geçici bir sayfa sıralama sırasında bozulmuş olabilir.
64 Bilinmeyen sınıf "%1$s".
65 Sınıf "%1$s" zaten bulunmakta.
66 İç hata: bilinmeyen bir güç operasyonu %1$d nese için %2$d|%3$d|%4$d.
67 İç hata: bir yığın dosya nesnesi depolamak için tahsis edilmemiştir %1$d|%2$d|%3$d.
68 İç hata: oid sınıf için farklı sınıf adları = %1$d|%2$d|%3$d bulundu. Bulunan sınıf adları "%4$s", "%5$s" sırasıyla, sınıf adını karma tablo ve yığın kullanarak.
69 İç hata: farklı sınıf nesne tanımlayıcıları ismi sınıf için bulundu "%1$s". Bulunan OID ler %2$d|%3$d|%4$d, %5$d|%6$d|%7$d sırasıyla, sınıf adını karma tablo ve yığın kullanarak.
70 İç hata: Adında sınıf "%1$s" ve oid = %2$d|%3$d|%4$d sınıf adı karma tabloda bulunmamamktadır.
71 İç hata: adında sınıf "%1$s" ve oid = %2$d|%3$d|%4$d kendi yığınında bulunmamaktadır.
72 İşleminiz (index %1$d, %2$s@%3$s|%4$d) tek taraflı sistem tarafından iptal edildi.
73 İşleminiz (index %1$d, %2$s@%3$s|%4$d) üzerinde beklerken zaman aşımına uğradı %5$s nesne üzerinde kilit %6$d|%7$d|%8$d. Bu kullanıcı için bekliyor(s) %9$s bitirmek için.
74 İşleminiz (index %1$d, %2$s@%3$s|%4$d) üzerinde beklerken zaman aşımına uğradı %5$s nesne üzerinde kilir %6$s. Bu kullanıcı için bekliyor(s) %7$s bitirmek için.
75 İşleminiz (index %1$d, %2$s@%3$s|%4$d) üzerinde beklerken zaman aşımına uğradı %5$s örneği üzerinde kilitlemek %6$d|%7$d|%8$d of class %9$s. Bu kullanıcı için bekliyor(s) %10$s bitirmek çin.
76 İşleminiz (index %1$d, %2$s@%3$s|%4$d) üzerinde beklerken zaman aşımına uğradı %5$s sayfa üzerinde %6$d|%7$d. Bu kullanıcı için bekliyor(s) %8$s sayfa kilidi serbest bırakmak için.
77 İç hata: tüm bufferlar onarıldı.
78 İç hata: an I/O mantıksal günlük sayfa okurken hata oluştu %1$lld (fiziksel sayfa %2$lld) nın "%3$s".
79 İç hata: an I/O mantıksal günlük sayfa yazarken hata oluştu %1$lld (fiziksel sayfa %2$lld) nın "%3$s".
80 Mantıksal günlük sayfa yazarken sistem aygıt işletim yeterli yer %1$lld (fiziksel sayfa %2$lld) nın "%3$s". %4$d bayt tan daha fazla yazılamaz.
81 İç hata: mantıksal log sayfa %1$lld bozulabilir.
82 Günlük disk biriminin yooğunluğu monte edilemiyor/dosya "%1$s".
83 Yol uzunluğu "%1$s" önek log adının artı uzunluğu "%2$s" çok uzun; Kombine uzunluğundan daha az olması gerekir %3$d.
84 Önek log adının uzunluğu "%1$s" çok uzun; uzunluğundan daha az olması gerekir %2$d.
85 Önek adı "%1$s" aynı değildir "%2$s" log diskte.Log veritabanı alanı dışında yeniden adlandırılmış olabilir.
86 Veritabanı akım ile uyumsuz "%1$s" serbest "%2$s".
87 Kullanılarak kurtarıldı gerekir kurtarma eylemleri vardır "%1$s" serbest "%2$s" yerine sürüm "%3$s". İyileştikten sonra veritabanı sürüm çalıştırılabilir "%4$s".
88 İç hata: Yayın dize "%1$s" geçemez %2$d. Başlığı değiştirmeniz gerekir log.
89 Log "%1$s" Verilen veritabanına ait değildir.
90 Yinele günlüğü her işlem için bir sayfa seviyesidir. Bir veri sayfası işaretçi adresinin bir parçası olarak verilmelidir.
91 Giriş Tecil her zaman bir sayfa düzeyinde günlük bir operasyondur. Bir veri sayfası işaretçi adresinin bir parçası olarak verilmelidir.
92 Telafi günlüğü her zaman işlem için bir sayfa seviyesidir. Bir veri sayfası işaretçi adresinin bir parçası olarak verilmelidir.
93 Uyarı: yenile günlüğü kokan kurtarma ve normal sadeleştirmek sırasında göz ardı edilir.
94 Uyarı: günlüğü erteleme yenileme kurtarma ve normal sadeleştirmek sırasında göz ardı edilir.
95 Uyarı: günlüğü geri kurtarma ve normal geri alma sırasında göz ardı edilir.
96 Medya kurtarma biriminde gerekli olabilir "%1$s".
97 İç hata: günlük sayfa bulamadı %1$lld günlük arşivlerinde.
98 Arşiv log oluşturulamıyor "%1$s" arşivleme sayfalarında %2$lld to %3$lld.
99 Yedekleme dizini bilgi dosyası oluşturulamıyor"%1$s".
100 Veritabanı yedekleme yapılamıyor"%1$s".
101 Bilinmeyen kullanıcı dosya "%1$s".
102 Dosya "%1$s" yeterli mesajı yok: %2$d girdileri beklenir.
103 Dosya "%1$s" girişleri sırasız gibi görünüyor. Giriş %2$d değerler ile birlikte: %3$d %4$s %5$s, beklenen %6$d %7$s değerler ile birlikte bulundu.
104 Dosya "%1$s" veritabanı adı yanlış bir giriş (ana birim) sahip görünüyor. Giriş %2$d değerler ile birlikte: %3$d %4$s %5$s, beklenen %6$d %7$s %8$s değerler ile birlikte bulundu .
105 Yedekleme dosyası erişemiyor "%1$s". Yeniden Depolandı veya Yedekleme iptal edildi.
106 Genel işlem tanımlayıcı ile cari işlem işlemek için hazırlayamaz %1$d Bu işlem tanımlayıcı başka bir işlem tarafından kullanımda olduğundan dolayı.
107 İşlem tanımlayıcı ile ilişkili hiçbir küresel dağıtılmış işlem yoktur. %1$d.
108 Geçerli işlem %1$d küresel tanımlayıcı ile dağıtılan işlem katılmaya çalışırken önce işlenen veya iptal edilmelidir %2$d.
109 İşleminiz %1$d tek taraflı sistem tarafından iptal edilmiştir çünki bir katılımcı (uzak) yere indi veya tek taraflı olarak iptal işlemi.
110 İzolasyon seviyesi değeri %1$d ve %2$d arasında olmalıdır.
111 İşleminiz sunucu hatası veya mod değişikliği nedeniyle sistem tarafından iptal edildi.
112 Host "%1$s" veritabanı çalıştırmak için yetkili değil.
113 Yeniden / veritabanı sunucusu başlatılamadı. %1$s
114 Yorumlamak için uygun değil "%1$s" bir veritabanı gibi. Veritabanı değeri /dosyalar yeniden adlandırılmış olmalı/veritabanı alanı dışında kopyalanmış.
115 Veritabanı "%1$s" zaten var.
116 Veritabanı "%1$s" bilinmiyor veya dosya "databases.txt" erişilemiyor.
117 Veritabanı için mutlak Pathadı çok uzun. Path in birleştirilmiş toplam uzunluğu "%1$s" artı adı "%2$s" is %3$d; Kombine uzunluğundan daha az olması gerekir %4$d.
118 Geçerli çalışma dizinini bulamadı.
119 Yerel hostadı bulunamıyor.
120 Yoğunlukların maksimum sayısı (%1$d) değerini aştı.
121 "%1$s" kaldırmak için çalışılıyor veritabanından kalıcı bir yoğunluk.
122 Sistem mesajı kataloguna erişilemiyor.
123 "%2$s" veri tabanı için %1$s oluşturulamıyor. Ek bilgi için lütfen "%3$s" bakınız.
124 Yoğunluk "%1$s" zaten bulunmakta.
125 Otomatik yoğunluk uzantısı "%1$s" nın %2$d sayfaları ve genel depolama amaçlı oluşturuldu.
126 Bilinmeyen amaç "%1$s" satırında verilen %2$d.
127 Doğru olmayan değer %1$d satırında verilen sayfa numaraları %2$d.
128 Satırında verilmeyen sayfaların numaraları %1$d.
129 Bilinmeyen simge "%1$s" satırında bulundu %2$d.
130 Sanal bellek dışında.
131 Veritabanı sistem hatası.
132 Mevcut sürümde özellik uygulanmadı: %1$s.
133 Sürekli iç içe ayar izin verilmedi.
134 Sınıf öznitelikleri her ikisini de kullanmak için izin verilmedi ve tek bir güncelleştirme olmayan sınıf öznitelikleri.
135 OİD sütunlar için geçersiz ifade : %1$s.
136 Uygulanmayan fonksiyon "%1$s".
137 Yetki nesneleri bozulmuş.
138 Yetkilendirme sınıfı "%1$s" bulunamadı.
139 Yetkilendirme öznitelik üzerinde erişim hatası "%2$s" ın sınıfı "%1$s".
140 İşlem "%1$s" sadece DBA veya bir DBA grubu üyesi tarafından gerçekleştirilebilir.
141 "%1$s" üyesi gibi "%2$s" eklenemez.
142 Üyesi ekleme kullanıcı hiyerarşisi döngüsel bir grafik haline neden olur.
143 Sahipli bir sınıf ile karşılaşılmadı.
144 Kullanıcı nesnesi erişilemiyor.
145 Sorun kabul edilemez/kendisi için komutları geri alamaz.
146 Sorun kabul edilemez/bir sınıf sahibi için geri alamaz.
147 Kabul Etme seçenekleri bulunmamakta.
148 Yetki nesne üzerinde yazma kilidi edinilemez.
149 Yetkilendirme nesne örneğini oluşturamaz.
150 Kendi kendine ayrıcalıkları geri alamaz.
151 Bir sınıfın sahibi ayrıcalıkları geri alamaz.
152 GRANT bulunamadı.
153 Veritabanı için geçerli yetkilendirme ayrıcalıkları bulunmamaktadır.
154 Eksik yetkilendirme kurulum - Veritabanı için geçerli yetkilendirme ayrıcalıkları bulunmamaktadır.
155 Çoklu yetkilendirme kökleri.
156 Yetkilendirme hatası.
157 SELECT yetkilendirme hatası.
158 ALTER yetkilendirme hatası.
159 UPDATE yetkilendirme hatası.
160 INSERT yetkilendirme hatası.
161 DELETE yetkilendirme hatası.
162 İNDEKS yetkilendirme hatası.
163 EXECUTE yetkilendirme hatası.
164 Kullanıcı "%1$s" zaten bulunmakta.
165 Kullanıcı "%1$s" geçersiz.
166 Geçersiz kullanıcı özelleştirmesi.
167 DBA, DBA grup ve sınıf sahibi üyeleri işlemi gerçekleştirebilirsiniz.
168 Üye bulunamadı.
169 %1$s veritabanından kullanıcı silinemiyor.
170 İçeride kullanıcı girişi bulunmamaktadır.
171 Yanlış veya kayıp şifre.
172 Şifre dize 31 bayt den fazla olmaz.
173 Veritabanı dosyası bulunamadı "%1$s".
174 Veritabanı dosyası yazma erişimi alamadı "%1$s".
175 Kötü biçimlendirilmiş veritabanı dosyası "%1$s".
176 Tarih biçiminde dönüşüm hatası.
177 Dahili depolama için büyük nesne oluşturulamıyor.
178 Geçici OID MOP olmadan karşılaştı.
179 "%1$s" Alanı "%2$s" etki alanı ile uyumlu değil.
180 "%1$s" Alanı "%2$s" verilen değerin hedef etki alanı ile uyumlu değil.
181 Etki değeri zorlanamaz "%1$s" alan için "%2$s".
182 Etki değeri zorlanamaz "%1$s" alan için "%2$s" taşmaksızın.
183 Alınan veri beklenmedik bir miktarı; %1$d beklenen, %2$d alınan.
184 İletişim buffer ayrılamadı.
185 İstemciden veri alma hatası.
186 Sunucudan veri alma hatası.
187 İletişim buffer kullanılmaz.
188 Bilinmeyen veritabanı "%1$s".
189 Geçersiz host adı "%1$s".
190 Sunucu host tespit edilememiştir.
191 Sunucuya bağlanamıyor "%1$s" üzerinde "%2$s".
192 Ağ yapılandırma dosyası yüklenemedi.
193 Sunucu istemciden kapatma komutu aldı.
194 Bilinmeyen sunucu isteği id %1$d.
195 Sunucu iletişim hatası: %1$s.
196 Sunucu adı tespit edilmemiştir.
197 Ana sunucu ile temas kurulamadı.
198 Kesilmiş çok küçük, verileri arabelleğe alma.
199 Sunucu yanıt vermemektedir.
200 Nesneden bağımsız olarak uygun şekilde kaldrıma ayarlanmamıştır.
201 Doğru olmayan UNIQUE tablo girişi kaldırıldı.
202 Öznitelik "%1$s" bulunamadı.
203 Öznitelik "%1$s" için değer mutlaka "%2$s" türü olamalı, türü değil "%3$s".
204 Fonksiyon eksik veya geçersiz argüman adı ile adlandırılır.
205 Öznitelik "%1$s" NULL yapamaz.
206 Öznitelik "%1$s" UNIQUE sınırlaması yoktur.
207 Sınıf "%1$s" bir sıfır-boyut nesne bulunmakta.
208 Yöntem "%1$s" bulunamadı.
209 "%1$s" adı ile hiçbir niteliği veya yöntem olduğu bulunamamıştır.
210 İç hata: nesne şablonu işleme.
211 Nesne şablonu oluşturma sırasında öznitelik silindi.
212 "%1$s" öznitelik UNIQUE sınırlaması ihlal ediyor.
213 Geçersiz UNIQUE tablo girişi karşılaştı.
214 "%1$s" öznitelik bir etki alanı çatışması bulunmakta.
215 id %1$d öznitelik bulunamadı.
216 Değeri üzerinde geçersiz nesne sahipliğini etiketi.
217 Operasyon sadece sınıf nesneleri üzerinde yapılabilir.
218 db_get path ifadesi içinde geçersiz nesne.
219 Geçersiz db_get path ifadesi.
220 Geçersiz ayar in db_get path ifadesi.
221 db_get path ifadesi içinde geçersiz ayar indeksi.
222 Dize değerini atamaya çalışırsanız  %2$d daha fazla karakter atanabilir "%1$s".
223 Değer %2$d çok fazla büyük küçük int niteliği "%1$s" için.
224 Bir veritabanı yeniden başlatılamadı.
225 Öznitelik eksik değeri "%1$s" NOT NULL kısıtlaması ile.
226 Sınıf ta boş bileşen listesi.
227 "%1$s" Öznitelik değerini birden fazla atamaya çalışırsanız.
228 Yöntem "%1$s" %2$d ile adlandırılan argümanlar. Sistem %3$d argümanların birden fazlasına izin verir.
229 Yöntem "%1$s" %2$d argüman gerektirir "%3$s" alan ile birlikte. Alanı "%4$s" geçersiz bir değer verildi.
230 Öznitelik "%1$s" uzunlukta bir dize atanamaz %2$d. İzin verilen maksimum dizi uzunluğu %3$d.
231 Geçersiz API işlemi geçici bir nesne üzerinde çalıştı.
232 Birden çok işlem üzerinden nesne şablonları kullanmak için izin verilmedi.
233 "%1$s" temel türü adı ile sınıfı oluşturulamıyor.
234 Yöntem dosyası "%1$s" bulunamadı.
235 %1$d bağladıktan sonra çözülmemiş yöntem fonksiyonları.
236 Çözülemeyen yöntem "%1$s".
237 Ciddi sorunlar dinamik bağlama sırasında karşılaşılan edildi.
238 Yöntem dosyalarına "%1$s" erişilemiyor.
239 Öznitelik "%1$s" bulunamadı.
240 Yöntem "%1$s" bulunamadı .
241 "%1$s" adında yöntem veya öznitelik bulunmamaktadır.
242 "%1$s" yöntem için %2$s için işaret bulunamadı .
243 Yöntem "%1$s" in %2$d argümanı tanımsız.
244 "%1$s" alan adı bir sınıf veya basit tür adı değildir.
245 "%1$s" adı zaten bir öznitelik adı olarak kullanılmıştır.
246 "%1$s" adı zaten bir yöntem adı olarak kullanılmıştır.
247 Şema yöneticisi iç fonksiyon için geçersiz argüman.
248 Öznitelik alanı "%1$s" %2$s kısıtlaması ile birlikte kullanmaya uygun değildir.
249 Sınıf üzerinde istenen işlem "%1$s" örnekleri yalnızca daha önce oluşturulan ile gerçekleştirilebilir.
250 "%1$s" özniteliği üzerinde indeks oluşturulamaz,paylaşılan bir değer ile tanımlanır.
251 Yöntem "%1$s" için zaten %2$s işarti bulunmaktadır.
252 Öznitelik "%1$s" işlemi için bir etki alanı olmalıdır.
253 Öznitelik "%1$s" iç içe bir dizi etki alanı ile tanımlanamaz.
254 "%1$s" özniteliğinden "%2$s" etki alanı kaldırılamıyor.
255 "%1$s" özniteliği bir değişken boyutlu etki değildir.
256 Süpersınıf zaten bulunmaktadır
257 Süpersınıf ek hiyerarşisinde döngülere neden olur.
258 Süpersınıf bulunamadı
259 "%1$s" yöntemi için çoklu imzalar uygundur.
260 "%1$s" yöntemin %2$d özniteliği alanın bir alan ayarı değildir.
261 "%1$s" için karar bulunamadı.
262 "%2$s" değer alanı "%1$s" öznitelik için uygun değildir.
263 Şema yöneticisi iç bozulma tespit edildi.
264 "%1$s" öznitelik/metod için "%2$s" takma adı benzersiz değildir.
265 "%2$s" alan ile çakışan "%1$s" öznitelik gölgeleme.
266 "%1$s" öznitelik üzerinde "%2$s" ve "%3$s" sınıflar ile adlar çatışmakta.
267 Çelişkili imza ile"%1$s" gölgeleme metodu .
268 "%1$s" metod üzerinde "%2$s" ve "%3$s" sınıflar ile ad çatışması.
269 "%1$s" alan üzerinde indeksi tanımlayamazsınız.
270 "%1$s" alan üzerinde BENZERSİZ sınırlaması tanımlayamazsınız.
271 Sınıf hiyerarşisinde algılama döngüsü; "%1$s" , "%2$s" ın süper sınıfıdır.
272 Sınıf "%1$s" için indeks "%2$s" zaten tanımlanmış .
273 İndeks "%1$s" bulunmamaktadır.
274 Ad içinde kural dışı karakter: "%1$s".
275 Öznitelik "%1$s" üzerinde kural dışı işlem, "%2$s" sınıfından arta kalan.
276 Metod "%1$s" üzerinde kural dışı işlem, "%2$s" sınıfından arta kalan.
277 "%1$s" üzerinde kural dışı işlem, "%2$s" sınıfından arta kalan.
278 "%4$s" sınıf "%1$s" için uyumsuz etki vardır, "%2$s" ve "%3$s" sınıflarından arta kalandır.
279 "%4$s" sınıf içinde, "%1$s" sınıf "%2$s" içinden arta kalan isteğe bağlı olarak kullanılamaz. "%3$s" sınıfında tanımlı daha belirli bir etki alanına sahiptir.
280 "%3$s" sınıf içinde, "%1$s" sınıf "%2$s" içinden arta kalamaz çünki uyumsuz bir etki alanı ile yerel bir tanımlama yoktur.
281 "%3$s" sınıf içinde, "%1$s" sınıf "%2$s" içinden arta kalana takma ad verilmiş ama başka bir kaynaktan yedek bulunamamıştır.
282 "%4$s" sınıf içinde, "%1$s" sınıf "%3$s" içinden arta kalan bir takma ad olarak sınıf "%2$s" yerine hizmet veremez. Etki alanı uyumsuzdur.
283 "%4$s" sınıf içinde, "%1$s" sınıf "%3$s" içinden arta kalan bir takma ad olarak sınıf "%2$s" yerine hizmet veremez. Daha az özellikli bir etki alanına sahiptir.
284 "%1$s" dan arta kalan kabul edemzler çünki because bu sınıfta yerel olarak tanımlanır.
285 Kalıtsal bileşen "%2$s" için takma ad gibi "%1$s" kullanılamaz çünki bu ada sahip bir yerel olarak tanımlanmış bileşeni zaten var.
286 "%3$s" nun "%2$s" için takma ad gibi "%1$s" kullanılamaz. Bu ada sahip bir bileşeni zaten "%4$s" arta kalan olarak alınır.
287 "%1$s" sınıf içinde, "%2$s" özniteliği tanımlayamazsınız çünki bu "%3$s" devralınan bir yöntem gölgesi olacaktır.
288 "%1$s" sınıf içinde, "%2$s" yöntemi tanımlayamazsınız çünki bu "%3$s" devralınan bir öznitelik gölgesi olacaktır.
289 "%1$s" alt sınıf "%2$s" yöntemi sınıf "%3$s" den devralamaz çünki bu isimde bir öznitelik zaten var.
290 "%1$s" alt sınıf "%2$s" öznitelik sınıf "%3$s" den devralamaz çünki bu isimde bir metod zaten var.
291 "%2$s" sınıf içinde "%1$s" öznitelik ve sınıf "%3$s" de olduğu gibi bir metod olarak tanımlıdır.
292 "%1$s" indeks ile şartname doldurma bulunmamaktadır.
293 İşlem bu sınıf türü için izin verilmiyor.
294 Tanımsız ortam değişkeni "%1$s" yöntem dosyasından başvurulmuştur.
295 "%1$s" sınıf değiştirilemedi. Sistem katalog alan dışında. Alanı geri almak için, CompactDB programı ile veritabanı sıkıştırmalı.
296 Geçersiz özellik listesi ile karşılaşıldı.
297 Takma ad "%1$s" birden fazla kullanılmıştır.
298 "%1$s" sınıf içinde, "%2$s" için "%3$s"' ın bir kararı onaylanmadı. Bu sınıf bir süper sınıf değildir.
299 "%1$s" ayrılmış bir sözcüktür ve bir öznitelik,metod veya sınıf adı gibi kullanılamaz.
300 Öznitelik "%1$s" VARSAYILAN ve BENZERSİZ kısıtlamaları ile birlikte tanımlanamaz.
301 Öznitelik "%1$s" %2$d un kısıtlama uzunluğu ile tanımlanamaz. En fazla kısıtlama uzunluk değeri %3$d tür.
302 Bir dizi elemanı eklenemiyor.
303 Değer kümesi içinde zaten var.
304 %1$d sınırları dışında indeksi ayarlayın.
305 Sıra indeksi %1$d sınırlar dışında.
306 İstenen işlem yalnızca dizileri üzerinde gerçekleştirilebilir.
307 İstenen işlem yalnızca setleri üzerinde yapılabilir.
308 Eleman değeri kümesi etki alanı içinde değildir.
309 Verilen yasadışı kümesi öğe indeksi: %1$d.
310 Öğe küme içinde bulunamadı.
311 Öğe sıra içinde bulunamadı.
312 "%1$s" geçerli bir dizi alanı değildir.
313 Nesne buffer yetersizlik okurken.
314 Nesne buffer yazarken taşması.
315 Yasadışı metaclass tanımı karşılaşıldı.
316 Dönüştürücü boyutu hesaplama uyumsuzluğu, kabul edilen %1$d hesaplanan %2$d.
317 Karşılaşılan "%1$s" sınıf için disk temsili geçersiz.
318 Nesne yükleme sırasında tekleme. Veritabanı tarihi olasılıkla bozuk veya alan dışında.
319 Bilinmeyen bir öznitelik uzantısı önemsemiyor.
320 Nesnenin karşılaştığı bozuk disk gösterimi.
321 Çalışma alanında olası bozulma tespit edildi.
322 MOP çalışma alanında bulunamadı.
323 Çalışma dışı geçici MOP yükseltmek için deneyin.
324 Çalışma alanında sınıf dışı nesne bulundu.
325 Kirli listesinde MOB çöp toplama girişimi.
326 Çalışma alanında bir nesne için sınıf gösterici değiştirme.
327 NULL OID ile MOP oluşturulamıyor.
328 Örnek sınıfı olmadan çalışma alanında karşılaştı.
329 Nesne listesi bağlantısını çalışma alanında ayrılmamış.
330 Çalışma Alanı pin ihlali.
331 Sanal bellek dışında, OS çalışma blok ayıramadı. İşlem iptal ediliyor.
332 Orijinal çalışma alanı büyüklüğü tahmini aştı. Otomatik bir uzantısı yapılmıştır.
333 Depolama alanı tahsisi sırasında bellek yetersiz. İşlem iptal ediliyor.
334 %1$d girişimi tahsisi d bayt maksimum çalışma blok boyutu daha büyüktür. max_block_size parametre değiştirmeyi deneyin. İşlem iptal edildi.
335 Ücretsiz nesneye girişimi görmezden gelerek çalışma alanı içinde ayrılmamış.
336 Bir kereden fazla bir nesne serbest girişimi önemsenmez.
337 Negatif boyut ile nesne tahsis etme girişiminde önemsenmez.
338 Harita giriş tanımlayıcı taşması.
339 Bu işlem  %1$d ait değilse bu yana, kritik bölüm çkamazsnz.
340 Çocuk süreç çatal olamaz.
341 Çocuk süreç çalışma olamaz.
342 Süreç grubu değiştirilemez.
343 Request_id zaten kullanılıyor.
344 %1$s.
345 Kalıpta bir kapatma mesajı okuma sırasında hata oluştu.
346 Kalıpta bir durak kapatma mesajı okuma sırasında hata oluştu.
347 Ana sunucuya bir kanal kurulamadı.
348 Servis veya port tanımlayıcı da belirtmeniz gerekir.
349 TCP için bilinmeyen hizmet: %1$s.
350 Hata "%1$s"  konağın adıyla yerel bilgisayardan alınıyor. Host bulunamadı.
351 TCP soketi oluşturulamıyor.
352 tcp_open: Ayrılmış bir TCP bağlantı noktası alınamıyor.
353 Ana sunucuya bağlantı yapamazsınız "%1$s".
354 Soketi için yeni süreç sahibi ayarlanamıyor.
355 Soket akımı oluşturulamıyor.
356 UNIX alan soketi için '%1$s' dosya mevcut.
357 Yerel adres bağlanamıyor ... durduruluyor.
358 Onaylama başarısız.
359 Datagram bağlama hatası.
360 Datagram onaylama hatası.
361 Datagram bağlantı hatası.
362 Datagram soket hatası.
363 Ana soketten Recvmsg başarısız oldu.
364 Sunucuya yeni bir istek gönderiliyor.
365 İstemciye bir yayın mesajı gönderme.
366 Sunucudan hata: %1$s
367 Sunucu %1$s zaten bulunmakta.
368 %1$s için bağlantı sırasında iletişim hatası.
369 Kullanılmayan hata kodu.
370 Kullanılmayan hata kodu.
371 Kullanılmayan hata kodu.
372 Kullanılmayan hata kodu.
373 Okuma esnasında erken EOF: %1$d.
374 Okuma esnasında erken EOF %1$d veya %2$d.
375 Dönüşüm hatası (0x%1$c%2$c) %3$d ve %4$d dönüştürülür %5$d.
376 Genel sınıf bulunamadı.
377 Hata %1$d: "%2$s" multimedya hiyerarşiye öznitelik eklemek için başarısız oldu.
378 Hata %1$d: "%3$s" multimedya hiyerarşiye "%2$s" olarak uygulanan metod eklemek için başarısız oldu .
379 Hata %1$d: multimedya hiyerarşi için bir üst sınıf eklemek için başarısız oldu.
380 Dinamik yükleyici zaten başlatıldı.
381 Dinamik yükleyici başlatılamadı.
382 Dinamik yükleyici yanlış başlatıldı.
383 "%1$s" bir nesne dosyasını veya bir arşiv değil.
384 "%1$s" için mutlak yol belirlenemiyor.
385 ld işlem %1$d kodu ile çıkıldı.
386 ld süreci %1$d sinyal nedeniyle çıkıldı.
387 ld süreci bilinmeyen 0x%1$x waitval ile çıkıldı.
388 "%1$s" için ilk görüntü erişilemiyor.
389 Sistem hatası: %1$s.
390 "%1$s" ile sorun : %2$s.
391 Diğer SIGPIPE işleyicisi ile çatışma.
392 Dinamik yükleyici daemon spawn için açılamıyor.
393 Dinamik yükleyici daemon kayboldu.
394 Aralık bitiş noktası 0 ile 256 arasında değildir.
395 Kural dışı alt ifade belirtildi.
396 Aralık dışından sekizli haneli dışarı kaçış bulunmaktadır.
397 Düzenli ifade düzgün ayrılmamış.
398 Metin arama ifadesi derleme önce çağrılır.
399 Bir eşsiz parantez normal ifadede bulunur.
400 Parantezler çok derinden normal ifadede iç içe.
401 Aralığında belirtilen ikiden fazla numara.
402 Bir eşsiz küme ayracı düzenli ifade bulunur.
403 Aralık ifadesindeki ilk sayı ikinciden daha büyüktür.
404 Bir benzersiz ayraç düzenli ifade bulunur.
405 Düzenli ifade derlemek için çok uzun oldu.
406 Geçersiz B+tree indeksi tanımlayıcı: (vfid = (%1$d, %2$d), rt_pgid: %3$d).
407 Başvurulan bilinmeyen anahtar %1$s B+tree index {vfid: (%2$d, %3$d), rt_pgid: %4$d, key_type: %5$s}.
408 Başvurulan bilinmeyen değeri (oid) %1$d|%2$d|%3$d.
409 Başvurulan yinelenen değer (oid) %1$d|%2$d|%3$d.
410 Başvurulan Null anahtar.
411 Geçersiz B+tree indeks anahtar türü "%1$s".
412 Geçersiz aralık arama özellikleri.
413 Bilinmeyen nitelik tanımlayıcısı: %1$d.
414 Bilinmeyen sınıf tanımlayıcısı: %1$d|%2$d|%3$d.
415 Geçersiz sınıf tanımlayıcısı: %1$d|%2$d|%3$d.
416 Bilinmeyen temsil tanımlayıcı: %1$d.
417 Geçersiz temsil tanımlayıcı: %1$d.
418 Kayıt tanıtıcı yeterli alan yok: %1$d.
419 Sınıf maksimum temsilleri sayısına ulaştı: %1$d.
420 Sınıf %1$d|%2$d|%3$d zaten temsilcilikleri bulunmakta.
421 Temsilcilikler Directory Sınıf Kataloğu için eksik: %1$d|%2$d|%3$d.
422 Katalog içinde Sınıf - Repr_Id için Temsil Bilgisi Kayıdı eksik: %1$d|%2$d|%3$d - %4$d.
423 Oturum Geçersiz.
424 Yürütmek hiç bir açıklama bulunmamakta.
425 Öznitelik için "%1$s" sınıfın "%2$s" uyumsuz veri tipi .
426 "%1$s" Öznitelik Uyumsuz veri türü.
427 "%1$s" Veri türüne veri taşması.
428 Bildirimi güncelleştirilebilir değil.
429 Bilinmeyen komut.
430 Bilinmeyen değişken"%1$s".
431 SQL/X te hata çevirmende ya da çözümleyicide.
432 Bilinmeyen sınıf "%1$s".
433 Bilinmeyen öznitelik "%1$s" sınıf "%2$s" içinde.
434 Sorgudan doğru sütun adlarını bulunamıyor.
435 Çoklu ifadeleri izin verilmez.
436 Bildirimi bir sorgu değil.
437 Geçersiz uzun nesne kimliği(%1$s,%2$d, %3$s, %4$s).
438 Uzun nesne tanımlayıcısında çatışma bulunmaktadır.
439 Uzantı %1$d %2$d uzun nesnenin uzunluğundan daha büyüktür.
440 Geçersiz imleç konumu.
441 Geçersiz imleç işlemi.
442 Bilinmeyen imleç durumu.
443 Tuple değer indeksi %1$d aralık dışında.
444 Geçersiz öznitelik adı: "%1$s".
445 Değer listesi endeksi %1$d aralık dışında.
446 Sorgu sonucu yapılar bulunmaktadır işlem yöneticisi tarafından kapatıldı ancak uygulama tarafından kapalı değildir.
447 Zaten kapalı bir sorgu sonucu yapı çalışması denendi.
448 Tuple boyutları bir sayfadan daha büyük olmaması ile sınırlıdır.
449 Bilinmeyen sorgu tanımlayıcı: %1$d.
450 Geçersiz set operatörü: %1$d.
451 Yığın dosyası ile örnek bulunmamaktadır.
452 Geçersiz XML ağaç düğümü içerik.
453 Daha fazla erişim özellikleri düğümleri bulunmamakta.
454 Başvurulan geçersiz veri türü.
455 Daha fazla sorgu dosyası sayfaları kalmamıştır.
456 Veri türü referanslar uyumsuzdur.
457 Geçersiz sorgu sonucu türü.
458 Taşma ek bağlamında oluştu.
459 Sorgu sonucu tek bir başlığın daha fazlasını içerir.
460 Çok az girdi ana değişkenler sağladı.
461 Daha fazla ana değişkenler sonucu sütunlarda verilir.
462 Sonuç değeri NULL, ama hiçbir gösterge değişkeni bulunmamaktadir.
463 İmleç deyimi henüz hazırlanmış değil.
464 İmleç bir SEÇ ifadesi olmalıdır.
465 İmleç henüz açılmamıştır.
466 İmleç yeniden açılması öncesinde kapatılmalıdır.
467 Sonuç için tek bir nesneyi döndürmek gerekir.
468 No positional markers are allowed in EXECUTE IMMEDIATE statements.
469 Invalid data type used.DERHAL YÜRÜTME ifadelerinde izin verilen hiçbir pozisyon işaretleri bulunmamaktadır.
470 Sorgu iyileştirici için çok fazla öğe içerir.
471 %2$s dosyanın %1$d satır içinde bellek tükendi.
472 '%2$s'yerel veritabanı için '%3$s' host üzerinde %1$s konektörü iptal olmuştur.
473 '%2$s' host üzerinde '%1$s' yerel veritabanından raporlar: %3$s.
474 %2$s sırasında hata %1$s tespit edildi.
475 %1$s indeksi ile hiçbir sorgu özellikleri bulunmamaktadır.
476 LDB %1$s zaten bulunmaktadır.
477 LDB %1$s giriş için %2$s host ana bağlantı kurulamadı.
478 Yerel veritabanı "%1$s" tescilli LDB değildir.
479 Yerel veritabanı "%1$s" diğer istemciler tarafından erişiliyor, değişiklik veya iptal etmeye izin verilmez.
480 Yerel veritabanı "%1$s" boş değil ve iptal edilemez.
481 "%1$s" bir proxy sanal sınıf değildir.
482 "%1$s" sanal sınıf değildir.
483 "%1$s", "%2$s" sınıfının bir özelliği değildir.
484 object_id "%1$s" Proxy sanal sınıf için zaten ayarlandı.
485 Bir veya birden fazla object_id "%1$s" proxy sınıfı örneği için öznitelikleri NULL dur .
486 Nesne güncelleştirilebilir bir sanal sınıf örneği değil.
487 Nesne bir örnek değildir.
488 Bir sınıfın bir özelliği sanal bir sınıf veya bir proxy sanal sınıf olmayabilir.
489 Bir proxy sanal sınıf bir özelliği bir sınıf, sanal sınıf veya nesne olmayabilir.
490 Süper sınıf "%1$s" gibi "%2$s" sınıfının aynı türden olması gerekir.
491 "%1$s" proxy sorgu özelliklerinden varlık adı ayıklanamaz.
492 %1$s
493 Syntax: %1$s %2$s
494 Anlamsal: %1$s %2$s
495 Yürütme: %1$s %2$s
496 Başvuruluna bilinmeyen anahtar.
497 %1$d|%2$d|%3$d başvurulan bilinmeyen değer (oid).
498 %1$d|%2$d|%3$d başvurulan yenilenen değer (oid).
499 Baçvurulan Null anahtar.
500 Başvurulan yenilenen anahtar.
501 Geçersiz tetikleyici önceliği.
502 Tetikleyicide kayıp hedef sınıf.
503 Tetikleyici "%1$s" bulunamadı.
504 İç hata: "%1$s" tetikleyici işlemi .
505 "%1$s" adı ile bir tetikleyici zaten bulunmakta.
506 Bir sanal sınıf olduğundan bir tetikleyici "%1$s" tanımlanamaz.
507 Sakıncalı tetikleyici hedef sınıf "%1$s".
508 Sakıncalı tetikleyici hedef öznitelik "%1$s".
509 Geçersiz tetikleyici durumu "%1$s".
510 Geçersiz tetikleyici hareketi "%1$s".
511 "%1$s" tetikleyici erişim yetkiniz yok.
512 "%1$s" tetikleyici silme yetkiniz yok.
513 "%1$s" tetikleyici güncelleme yetkiniz yok.
514 "%1$s" tetikleyici değiştirme yetkiniz yok.
515 Tetikleyici eylem yürütme zamanı %2$s durumu yürütme zamanı %1$s dan daha erken olamaz .
516 Maksimum tetikleyici derinliği %1$d tetikleyici "%2$s" den aşıldı.
517 İşlem tetikleyici "%1$s" tarafından reddedildi.
518 İç hata: "%1$s" tetikleyici işlemi .
519 Kuraldışı tetikleyici koşul türü.
520 REDDETME eylemi SONRASI veya ERTELENEN bir eylem süresi ile birlikte kullanılamaz.
521 REDDETME eylemi İPTALETME veya ZAMAN AŞIMI olayları ile kullanılamaz.
522 Tetikleyici durumu ifadesi verilmemiştir.
523 Tetikleyici eylemi ifadesi verilmemiştir.
524 Başka bir kullanıcı tarafından ait olduğundan belirtilen faaliyet kaldırılamaz.
525 "%1$s" için koşul derleme hatası: %2$s
526 "%1$s" için eylem derleme hatası, %2$s
527 "%1$s" için hata değerlendirilmesi koşulu: %2$s
528 "%1$s" için eylem değerlendiren hata, %2$s
529 İşlem tamamlanmış olamaz, bu "%1$s" tetikleyici tarafından geçersiz bırakıldı.
530 Düzenli ifade eksik.
531 Düzenli ifade çok uzun veya karmaşık.
532 Düzenli ifadede dengesiz parantez veya parantez.
533 Başvurulan düzenli ifadede aralık dışında.
534 Kuraldışı karakter veya düzenli ifade sözdizimi.
535 Düzenli ifade arama için metin verilmiştir.
536 Geçersiz işlem kodu normal ifadede bulundu.
537 Düzenli ifade derleyici için geçersiz arama komutu kodu.
538 Düzenli ifade çalışıyor buffer başlatılması gerekir.
539 Sıfıra bölme girişimi.
540 %1$s.
541 "%1$s" yoğunluk için boş sayfa sayısı tutarsız. %2$d ve %3$d sırasıyla, yoğunluk başlık ve bitmapa göre tespit edildi.
542 "%1$s" yoğunluk için serbest sektör sayısı tutarsız. %2$d ve %3$d sırasıyla, yoğunluk başlık ve bitmapa göre tespit edildi.
543 "%1$s" yoğunluk için disk başlığı tutarsız.
544 İç hata: İNDEKS %1$s SINIF ÜZERİNDE %2$s (CLASS_OID: %3$d|%4$d|%5$d). OİD nesne için B+tree anahtar %6$s girişi: B+tree üzerinde %7$d|%8$d|%9$d bulunamadı: %10$d|%11$d|%12$d.
545 İç hata: İNDEKS %1$s SINIF ÜZERİNDE %2$s (CLASS_OID: %3$d|%4$d|%5$d). Anahtar ve OİD: B+tree izerinde %6$d|%7$d|%8$d girişi : %9$d|%10$d|%11$d doğru değil. Nesne bulunmamaktadır.
546 İç hata: İNDEKS %1$s SINIF ÜZERİNDE %2$s (CLASS_OID: %3$d|%4$d|%5$d). Beklenilen %6$d OID giriş değerleri, ama B+tree izerinde %7$d bulundu: %8$d|%9$d|%10$d.
547 Sunucu sürümü %1$s istemci sürümü %2$s den farklı .
548 Proxy sınıfı "%1$s" için tanımlı hiçbir object_id yoktur.
549 Proxy örneği bulunamadı.
550 Bilinmeyen kayıt noktası adı %1$s
551 Yoğunluk bilgisinin path dosyası "%1$s" bulunamıyor. İç tablolardan okumaya devam edin.
552 Tarih aritmetiği yetersiz.
553 Zaman aritmetiği tetersizlik.
$ LOADDB
554 Yükleyici geçersiz bir durum girmiştir. Başka işlemler yapılabilir.
555 Veritabanı yükleme sırasında bellek ayırma hatası.
556 Çok fazla değer verilmiştir . %1$d beklemektir.
557 Öznitelik için %1$s of %2$s, tür %3$s is not allowed in the domain of the set.
558 Öznitelik için %1$s of %2$s, kabul edilen tür %3$s, got a set constant.
559 Öznitelik için %1$s of %2$s, kabul edilen tür %3$s, got %4$s.
560 Öznitelik için %1$s of %2$s, etki alanı desteklemek için kadar belirgin değildir\n niteliksiz nesne başvuruları.
561 İç içe kümeler izin verilmez.
562 Sistem sınıfı %1$s veritabanı yükleyici doldurulamaz.
563 %1$s dahili sınıf için başvuru NULL'a dönüştürülür.
564 %2$s in %1$s öznitelik için BENZERSİZ kısıtı aşılıyorsa.
565 %1$s kurucu yöntemi %2$s sınıfı üzerinde tanımlı değil.
566 Karakteristik düzeyini belirlenmemiş veya düzeyinde özelliği olmayan.
567 Çok fazla kurucu yöntemi argümanları sağlanmıştır. Tahmini %1$d.
568 Kurucu yöntemi parametresi eksik. Kabul edilen %1$d, bulunan %2$d.
569 Öznitelik değerleri eksik. Kabul edilen %1$d, bulunan %2$d.
570 "%1$s" Glo veri dosyasına erişilemiyor.
571 Örneğini daha önce ileriye doğru bir başvuru sonucu ortaya çıktı.\nBu kurucu yöntemler kullanılarak oluşturulmuş örnekleri için izin verilmiyor.
572 İç hata: Örneğinin diski gösterimi inşa edilemez.
573 İç hata: Veritabanındaki yeni örneği eklenemiyor.
574 İç hata: Veritabanındaki yeni örneği güncelleştiremez.
575 %1$d bağımsız değişken için kurucu %2$s ile, beklenen türü %3$s, %4$s.
576 Sınıf %3$sReferans %2$s %1$s alanı ile uyumlu değildir.
577 Kurucu %2$s bağımsız değişken %1$d için, etki alanı \n niteliksiz nesne kadar başvuruları desteklemek için belirgin değildir.
578 Sınıf %3$s başvurusu kurucu %2$s bağımsız değişken %1$d \n etki alanı uyumlu değildir.
579 Hedef etki alanı sınıfları için başvurular izin türü "nesne" içermelidir.
580 Özellik %1$s sınıf %2$s için tanımlı değil.
581 Güncelleştirmeler devre dışı bırakıldığında veritabanını güncelleştirmek için denendi.
582 Bilinmeyen depolama amacı %1$d. Geçerli aralık %2$d için %3$d uzaklıktadır.
583 Bir geçersiz sayfa numarası (%1$d) ayırmaya çalışılıyor.
584 İç hata: %1$d döngü dosyanın tablosu "%2$s" yoğunluğunda tespit edilmiştir. %3$d|%4$d döngü sayfasından kaynaklanıyor olabilir.
585 Bilinmeyen yığın %1$s|%2$d|%3$d
586 İç hata: "%4$s" yoğunluk içinde %3$d yığın için %1$d|%2$d VPID zinciri başlığı güncelleştirilemiyor.
587 Daimi birimlerin girişleri "%1$s" yoğunluk bilgileri dosyasında sıralanmamış olarak bulunur. Giriş %2$d: %3$d %4$s sırası dışındadır.
588 İç hata: '%1$s' Bildirim başarısız.
589 Geçersiz kullanıcı adı "%1$s".
590 Öznitelik etki alanı "%1$s" bir sınıf \n sanal sınıf veya proxy sanal sınıf olmayabilir.
591 Öznitelik etki alanı "%1$s" proxy sanal sınıf \n mutlaka proxy sanal sınıf olmslı.
592 Öznitelik etki alanı "%1$s" proxy sanal sınıf \n ve proxy sanal sınıf mutlaka aynı yerel veri tabanında olamlı.
593 Olmayan bir güncellenebilir sanal örnek iadesi edilmiş ve yeniden inşa edilemez.
594 Bir object_id maddesi yaklaşık veri türleri (float ya da double) özellikleri (%1$s) kullanmadan sağlanmalıdır.
595 Veritabanı adı "%1$s" cok fazla uzun. Veritabanı adı %2$d karakterden daha az olmalıdır.
596 Toplam geçici alanı sayfaları %1$d verilen izin aşılmıştır.
597 %1$d|%2$d|%3$d heap dosyaları için sayfaların sayısı tutarsızdır. \n%4$d ve %5$d sırasıyla, bir yığın zinciri ve dosya tablosuna göre tespit edildi.
598 Dosyaların sayısı tutarsız. %1$d beklenen, %2$d bulunulan
599 "%1$s" yoğunluk durumu eşitleme yaparken I/O hatası oluştu .
600 Fonksiyon "%1$s" PC'de uygulanamadı.
601 "%1$s".
602 dl hatası: "%1$s" bir kereden fazla tanımlanmış.
603 İç hata: VFID dosyasının sektör/sayfa tablosu %1$d|%2$d bozuk görünüyor.
604 İç hata: VFID için ayarlanmış bir ayırma dosyası %1$d|%2$d(yoğunluk "%3$s") %4$d işaretlenen veya silinen içinde tutarsız görünüyor sayfalar ve %5$d tablosunda sayfa delikleri silinmiş.
605 İç hata: %1$d|%2$d(yoğunluk "%3$s") VFID dosyası için işaretlenen silinen sayfaların tutarsız numarası. Tahmini %4$d, Bulunan %5$d.
606 "%1$s" path ile odbc.ini birlikte bulunmaz .
607 odbc.ini içinde veritabanı "%1$s" bulunamaz. 
608 odbc.ini içinde Veritabanı "%1$s" host özelliği yoktur.
609 Günlük kaydı yoksayıldığından beri işlem geri alınamaz. Veritabanınız bozulmuş olabilir.
610 Veritabanı bozulmuş olabilir, Veritabanı çöktüğünden beri günlük kaydı kapatılmış.
611 %1$s istemci / sunucu modunda yürütülemez.
612 Kurtarmak için beklemede olan eylemler var olduğu Logging şu anda devre dışı bırakılamıyor.
613 Sınıf "%3$s" içinde, "%1$s" yerel bileşeni "%2$s" sınıf için bir takma ad yerine hizmet veremez. Etki alanları uyumsuzdur.
614 Etkin günlük arşiv sayısı %1$d in max istenilen sayısı aşıldı.
615 Winsock arayüzü ile temas kurulamaz. Winsock hata: %1$d.
616 Winsock arabirimini kullanarak makine adını belirleyemiyor. Winsock hata: %1$d.
617 Winsock arabirimini kullanarak makine kimliği belirlenemiyor. Bu makine için ana bilgisayar adı tablo girdisi olmalıdır. Winsock hata: %1$d.
618 Öznitelik güncelleştirilebilir değil.
619 Kötü kaynak karakter kümesi.
620 Kötü hedef karakter kümesi.
621 Geçersiz veri türü. Bağımsız değişkenleri geçersiz veri türü içerir.
622 Tamamlanamayan karakter kümeleri. Bağımsız değişken kod kümeleri uyumsuzdur.
623 Geçersiz kaçış dizisi. Geçersiz bir kaçış dizisi düzenli ifade derleyici bir hataya neden oldu.
624 Geçersiz kaçış karakteri .Kaçış karakteri 1 den daha büyük bir uzunluğa sahip olmayan NULL olur.
625 Dahili hata. Örneğin bir nesne %4$d|%5$d|%6$d yanlış örneği nesne %1$d|%2$d|%3$d öznitelik bilgi şablonu güncellemek için çalışıyor.
626 Dahili hata. %1$d İstenen nitelikler bulunmamıştır.
627 Geçersiz kaplama işleneni. Kaplama işleneni 1'den büyük bir uzunluğa sahiptir.
628 Geçersiz Kur tipi: %1$d.
629 Sayfa boyutu %1$d 2 nin kuvveti değildir veya sayfa boyutu çok küçüktür. %2$d nin sayfa boyutu yerine kullanılmıştır.
630 Dönüşüm %1$s tarafından desteklenmiyor .
631 SQL ifadesi NULL kısıtlamasına aykırı.
632 %1$s bir yedekleme yoğunluğu değildir.
633 %1$s bir %2$s veritabanı yedeklemesi %3$s üzerinde oluşturulmuş yerine verilen veritabanı %4$s %5$s üzerinde oluşturulmuştur.
634 Bir veritabanı yoğunluğu/dosya yedekleme içinde beklenen.
635 UYARI: Log Buffer %1$d havuzunun arabellekleri güncel ortamı için çok küçük görünüyor.\n Bazı arabellekleri bir BİLİNMEYEN HATA nedeniyle sistem tarafından serbest bırakılmamış olması mümkündür.\n veya aynı zamanda iptal edilen çok sayıda eşzamanlı işlem bulunmakta. Log arabellek havuzundan %2$d daha arabellekleri ile genişletilir.
636 UYARI Num_buffers %1$d çok küçük. En az değer %2$d varsayıldı.
637 Sistem Hatası: bir log arabellek çok fazla boşaltma. Saptama sayısı sıfır olarak ayarlanır.
638 Uyarı: Güncellenemez log arşiv sayfası kimliği yıkama = %1$d
639 Sistem Hatası: Bir önceki log sıra sayfası %1$d geciktirilmiş yıkama sayfası %2$d değildir.
640 Sistem Hatası: işlem etkin olmadığında bir kayıt noktası eklenemez (örn., yada gerialma sırasında ).
641 Bir kayıt noktası için bir ad verilmelidir.
642 Sistem Hatası: geçerli işlem için aktif bir üst sistem çalışması yoktur.
643 Belki bir sistem hatası:  İşlem İşleniyor/İşlem İptal ediliyor = %1$d (indeks = %2$d) daimi işlemleri sahip olduğu \n ona bağlı. İşlem için sistem işlemler eklenecek.
644 LOG FATAL ERROR: %1$s
645 SİSTEM HATASI: Durum = %1$s İşlem = %2$d (index = %3$d) \n istemci geri alma / erteleme eylemleri uygulamak için doğru durumda değil... gözardı edildi.
646 SİSTEM HATASI: Bu bir dengeleme kaydı mantıksal bir günlük kaydı rcvindex eksik olduğunu görünüyor. = %1$s\n.Bu dengeleme kaydı olmadan hata kurtarma düzgün yapılmayacaktır.
647 Yedek "%1$s" verilen veritabanına ait değildir.
648 Yedekleme akımı ile uyumsuz "%1$s" serbest bırakma "%2$s".
649 Göz önüne alındığında hassas %1$d geçersiz; %2$d daha büyük olmalıdır ve %3$d daha büyük olmamalıdır.
650 'max_clients=%1$d'İçin yeterli konuları oluşturulamıyor.
651 %2$d 'nin her parçacıkları için %1$d tür arabellekleri ayrışım yapan sanal bellek bulunmamaktadır.
652 Hatalı offset %1$d yuvaya depolanan %2$d uzunluğu dair %3$d kayıtları bölünmüş verildi.
653 Hatalı offset %1$d veya %2$d uzunluk kaydın verilerinin bir kısım uzunluğu %3$d yuvaya %4$d depolanan kaldırmak için verildi.
654 Hatalı offset %1$d veya %2$d uzunluk kaydın verilerinin bir kısım uzunluğu %3$d yuvaya %4$d depolanan üzerine yazmak için verildi.
655 Olay işleyicisi yapılandırma dosyası açılamıyor, "%1$s".
656 Uyarı: Null id/adı "%1$s", satır %2$d olay işleyicisi yapılandırma dosyasında.
657 Uyarı: geçersiz eylem adı, "%1$s", "%2$s", satır %3$d olay işleyicisi yapılandırma dosyasında.
658 Uyarı: olay id %1$d, hatalı id kapsamında değil %2$d <> %3$d, dosya "%4$s", satır %5$d
659 Olay işleyicisi program erişemiyor, "%1$s".
660 Olay işleyicisi sürecine açılmıyor/bağlanamıyor, "%1$s".
661 Olay işleyici süreci yazma işleminde hata verdi, "%1$s".
662 Olay işleme mekanizması başlatılamadı.
663 Uyarı: olay işleyici yapılandırma dosyasında çok uzun satır, "%1$s", satır %2$d, kesiliyor
664 Olay işleme mekanizması başladı.
665 Olay işleyici pipe bozuk, "%1$s"
666 Olay işleme mekanizması durdu.
667 '%1$s' sınıf karşılık gelen C++ sınıfı ile eşleşemez.
668 İç hata: Bilinmeyen alan adı '%1$d'.
669 Sunucu istemci bağlantısını reddetti:maksimum istemci (%1$d), aşıldı.
670 İşletme nedeniyle görülecek olan bir ya da çok sayıda özel olan zorunlu düzensizlikler. %3$s%4$s düzeyini CLASS %1$s%2$s INDEX.Anahtar kelime: %5$s%6$s.
671 Bir ağ ile bağlantılı soket %1$d için okuma/yazma hatası meydana geldi işleminiz (indeks %2$d, %3$s@%4$s|%5$d)
672 İşleminiz Soket %1$d ilişkili (indeks %2$d, %3$s@%4$s|%5$d) kapalı.
673 Sunucu düşüşe geçtiğinden beri sunucu ile bağlantınız kapatılmıştır.
674 Geçerli sunucu yürütülmesine devam etmek için yeterince aktif konuları yoktur.Aktif konuları güncel %1$d numara. Bu yukarı Çalışma ortamınızda temiz sunucuya yürütülmesine %2$d konuları gerekebilir. İşlem İndeks %3$d sunucuya çalışmaya devam edebileceği zaman aşımına uğradı.
675 Veritabanı konumu dosyası okunamiyor, '%1$s'.
676 Veritabanı '%1$s', '%2$s' veritabanı konumu dosyasında bulunabilir değildir.
677 Veritabanı sunucusuna bağlantı kurulamadı, '%1$s',Aşağıdaki ana bilgisayar (lar): %2$s
678 Dahili hata. Müşteri yeniden başlatma modülü NULL veritabanı sunucusu adını aldı.
679 Bu C++ işlem çoktan başladı.
680 Aşması girişimi maksimum C++ iç içe geçmiş hareket düzeyi (%1$d).
681 %1$s işlem üzerinde denendi C++ işlem başlamamıştır .
682 %1$s C++ işlem tüm alt işlemler tamamlanıncaya kadar olmaz.
683 Geçersiz - %1$d uzunluğu ile dizesi oluşturmak için denendi
684 Metod dönüşü kullanıcı tanımlı hata kodu %1$d.
685 Sınıf "%1$s" geçersiz.
686 Bildirim: olay işleyici olarak başlangıç durumuna getirilir.
687 (%1$s *) için (%2$s *) atama için izin bulunmamakta.
688 Aralık dışında. öğesine %1$lld erişmek için deneyin. Toplama boyut = %2$lld.
689 Dahili hata. Yineleyici bozulmuş durum içerir.
690 Çözümlenmiş başlangıç değeri olmayan odb_Ref<> bir örneğini çalışıldı.
691 Geçersiz bir yineleyici kullanmaya çalışıldı.
692 İlişkisi olmayan bir koleksiyon ile bir yineleyici kullanmaya çalışıldı.
693 Sayısal veri türü üzerinde taşma meydana geldi.
694 SİSTEM HATA: B+tree yüklenemiyor.
695 Hatalı arayüz bir istemci iptal etmek için kullanılmıştır.
696 Bilinmeyen işlem(indeks %1$d, %2$s@%3$s|%4$d).
697 Verilen işlem indeksi(index %1$d, %2$s@%3$s|%4$d) (indeks %5$d, %6$s@%7$s|%8$d)geçerli işlem indeksi ile eşleşmiyor. Olasılıkla, verilen işlem tamamlandıktan ve işlem dizin başka bir işlem için yeniden atandı.
698 İç hata: İNDEKS %1$s SINIF ÜZERİNDE %2$s (CLASS_OID: %3$d|%4$d|%5$d). benzersiz hiyerarşisinde OIDs sayısı: %6$d OIDler sayısına eşit değildir: %7$d benzersiz B+tree artı NULL'ları sayısı bulundu: %8$d B+tree için benzersiz hiyerarşi içinde bulundu: %9$d|%10$d|%11$d.
699 İç hata: İNDEKS %1$s SINIF ÜZERİNDE %2$s (CLASS_OID: %3$d|%4$d|%5$d). benzersiz hiyerarşisinde OIDs sayısı: %6$d OIDler sayısına eşit değildir: %7$d B+tree için benzersiz B+tree kök istatistikleri bulundu: %8$d|%9$d|%10$d.
700 İç hata: İNDEKS %1$s SINIF ÜZERİNDE %2$s (CLASS_OID: %3$d|%4$d|%5$d). OIDs sayısı: %6$d NULL'ları sayısına eşit değildir: %7$d artı anahtar numarası: %8$d benzersiz B+tree: %9$d|%10$d|%11$d.
701 Hiçbir proxy üzerinde tanımlanmaktadır "%1$s" de ldb "%2$s".
702 İç hata: İNDEKS %1$s SINIF ÜZERİNDE %2$s (CLASS_OID: %3$d|%4$d|%5$d). benzersiz hiyerarşi içinde NULL'ları sayısı: %6$d NULL'ları sayısına eşit değildir: %7$d B+tree için benzersiz B+tree kök istatistikleri bulundu: %8$d|%9$d|%10$d.
703 İç hata: İNDEKS %1$s SINIF ÜZERİNDE %2$s (CLASS_OID: %3$d|%4$d|%5$d). OID: %6$d|%7$d|%8$d benzersiz B+tree içinde bulundu: %9$d|%10$d|%11$d benzersiz kısıtlama için sınıflar birine ait değil.
704 Genel sunucu fonksiyonlarının değerlendirilmesi başarısız oldu.
705 Tutarsız %1$d daimi yoğunlukları %2$d beklenen edildiğinde bulundu.
706 Daimi yoğunlukların arttırılamaz. Daimi yoğunluk amacı ile "%1$s" %2$s  verildi.
707 "%1$s" ile %2$d sayfaları geçici yoğunluk genişletmek için açılamıyor.
708 Geçici disk birimi genişletmek için açılamıyor "%1$s" ile %2$d sayfaları (%3$lld Kbytes) yeterli boş alan. Şu kullanılabilir alanı %4$d sayfaları ise (%5$lld Kbytes).
709 Kısıtlama "%1$s" bulunamadı.
710 Geçersiz kısıt.
711 Verilen öznitelik değeri olan bir nesne bulunmamaktadır.
712 Ksısıtlama " %1$s" zaten bulunmakta.
713 Bu öznitelik içerisinde bir indeks mevcut değildir.
714 Sorgu yetersiz geçici dosya alanı nedeniyle başarısız oldu.
715 Şema doğrulanma başarısız: %1$s
716 NOT NULL kısıtlamaları sanal ya da proxy sınıfları izin verilmez.
717 BENZERSİZ kısıtlamaları sanal ya da proxy sınıfları izin verilmez.
718 Gadget geçersiz.
719 Öznitelikleri (%1$d) ve değerler (%2$d) sayısı eşit değildir.
720 Sanal veya proxy sınıfı eklemek için bir gadget kullanamazsınız.
721 Sorgu verimleri birden fazla satır ekler.
722 NO NULL kısıtlaması özniteliklerinin numarası yanlış.
723 Mevcut bir öznitelik alanı değiştiremezsiniz.
724 Varsayılan kısıtlama adı üretimi için geçersiz parametre (ler).
725 İç hata: Geçici oid beklenen ve kalıcı oid karşılaştı.
726 UNIQUE sınırlaması ayrı bir alter ifadesi kullanılarak eklenmiş olması gerekir\tek olay için bulunmuş örnekleri yaratılmıştır. Örneğin, yerine:\n\talter table1 add attribute a int unique;\nuse:\n\talter table1 add attribute a int;\n\talter table1 add unique(a);
727 Geçersiz tetikleyici eylemi.
728 Geçici dosya vf id işlemi %1$d için geçersiz olduğundan sorgusu başarısız oldu.
729 Taşma çıkarma bağlamında oluştu.
730 Taşma çarpma bağlamında oluştu.
731 Taşma bölümü bağlamında oluştu.
732 Taşma tekil eksi bağlamında oluştu.
733 Taşma zorlama bağlamında oluştu.
734 İç hata: Dosya VFID başlığının %1$d|%2$d(Yoğunluk "%3$s") bozulmuş.
735 Bilinmeyen işlem indeksi %1$d.
736 Servis veya port tanımlayıcı da belirtmeniz gerekir. Winsock hata: %1$d.
737 TCP Bilinmeyen hizmet: %1$s. Winsock hata: %2$d.
738 Soket akımı oluşturulamıyor. Winsock hata: %1$d.
739 Yerel adres bağlanamıyor... yeniden deneniyor. Winsock hata: %1$d.
740 Yerel adres bağlanamıyor... durduruluyor. Winsock hata: %1$d.
741 Başarısız onaylama. Winsock hata: %1$d.
742 İstemciye bir yayın mesajı gönderme.Winsock hata: %1$d.
743 İstemci ile sunucu arasındaki karşılama başarısız oldu.(emsal host %1$s)
744 Rehashing Proxy / vclass MOP Hata .
745 Geçersiz çöp ​​toplama aşaması.
746 Geçersiz geri çöp ​​toplama.
747 Geçersiz atık toplama geri çağırma bileti.
748 Geçersiz nesne işaretçisi karşılaştı by db_gc_mark_object.
749 Getirilen örneklerin sayısı uymuyor: %1$d beklenen, %2$d alınan.
750 Getirilen örneklerin sayısı uymuyor: %1$d beklenen, %2$d alınan.
751 Yeni bir nesne OID INSERT tetikleyicisi ÖNCESİ mevcut değildir.
752 Yedekleme unit_num %1$d geri yükleme hatası.
753 Yedekleme unit_num %1$d, %2$d sayfa id geri yükleme hatası toplam sayfa sayısı %3$d volid için %4$d.
754 OO Proxy örneği olmayan dize tipi veya boş anahtar vardır.
755 %1$s stand-alone modu yürütülülemez.
756 Belirtilen dize arabellek bu nesne kodlamak için çok küçük.
757 İç hata: nesne kodlamak içinde sürekli OID atayamazsınız.
758 Belirtilen dize çözümleme nesnesi için geçerli değil.
759 Hedef nesne silindi.
760 İç hata: Proxy nesne örneği nesne kodlama sırasında NULL anahtar vardır.
761 İç hata: geçersiz bir gerçek örneği için vclass nesne örneğini haritalar.
762 Bir gerçek örneği için vclass örneğinin çözülmesinde iç hata oluştu.
763 Olmayan güncellenebilir nesne örneğini kodlama iç hata oluştu.
764 İç vobj formda nesnenin kodlama iç hatası oluştu.
765 Çıkış nesnesinin argümanı bir NULL adresi vardır.
766 Çözümleme nesnesi içinde iç hata oluştu.
767 İlk seviye %2$d yedekleme oluşturmadan %1$d düzeyi yedekleme oluşturulamıyor.
768 Yerel veritabanında "%1$s" bu oturumda erişilmiş, değişiklik veya bırakmaya izin verilmez.
769 Öznitelik "%1$s", sınıf "%2$s" geçerli bir sınıf ya da paylaşılan bir özniteliği değil.
770 Tablo fonksiyonları yoktur.
771 Fonksiyonu için geçersiz parametre.
772 db_serial sınıf bulunamadı.
773 Seri "%1$s" bulunamadı.
774 Seri "%1$s" zaten var.
775 Bir sonraki değeri MAX(MIN) değerini aşıyor.
776 Seri nesnesi alamaz.
777 Seri nesneyi güncelleştiremez.
778 Dosya "%2$s" dosyasına simgesel bir bağlantı "%1$s" oluşturulamıyor.
779 Sınırı aşan sonuç:Tarih içindeki Yıl, 1-9999 arasında olmalıdır.
780 Dahili sistem hatası: sistem zamanı alınamadı.
781 Format dizesi çok uzun. 16K dan daha kısa olmalıdır.
782 Boş dizeye burada izin verilmiyor.
783 Geçersiz biçim.
784 İki bağımsız değişken uyumsuzdur.
785 Birinci dizge çok uzun. 16K dan daha kısa olmalıdır.
786 Biçim yineleniyor.
787 Zaman biçiminde dönüştürme hatası.
788 Timestamp biçiminde dönüştürme hatası.
789 Yanlış numara.
790 Sorgu yürütme kullanıcı tarafından kesildi.
791 Geçersiz seri değeri.
792 Css için bellek ayrılamıyor.
793 pthread_attr_init() başarısız oldu.
794 pthread_attr_destroy() başarısız oldu.
795 pthread_attr_setdetachstate() başarısız oldu.
796 pthread_attr_setscope() başarısız oldu.
797 pthread_attr_setstacksize() başarısız oldu.
798 pthread_create() başarısız oldu.
799 pthread_join() başarısız oldu.
800 pthread_mutex_init() başarısız oldu.
801 pthread_mutex_destroy() başarısız oldu.
802 pthread_mutex_lock() başarısız oldu.
803 pthread_mutex_trylock() başarısız oldu.
804 pthread_mutex_unlock() başarısız oldu.
805 pthread_mutexattr_init() başarısız oldu.
806 pthread_mutexattr_destroy() başarısız oldu.
807 pthread_mutexattr_settype() başarısız oldu.
808 pthread_mutexattr_gettype() başarısız oldu.
809 pthread_cond_init() başarısız oldu.
810 pthread_cond_destroy() başarısız oldu.
811 pthread_cond_wait() başarısız oldu.
812 pthread_cond_timedwait() başarısız oldu.
813 pthread_cond_signal() başarısız oldu.
814 pthread_cond_broadcast() başarısız oldu.
815 pthread_key_create() başarısız oldu.
816 pthread_key_delete() başarısız oldu.
817 pthread_setspecific() başarısız oldu.
818 pthread_getspecific() başarısız oldu.
819 pthread_once() başarısız oldu.
820 Bağlantı başlatamıyor.
821 Bir bağlantı kapandı .
822 Sonraki istemci id alırken Mutex işlemi başarısız oldu.
823 Bağlantı listesi başlatılırken Mutex işlemi başarısız oldu.
824 Bağlantı listesi sonlandırılırken mutex yok edilemez.
825 pread işlevinin () çağrısı başarısız oldu.
826 pwrite işlevinin () çağrısı başarısız oldu.
827 Bağlantı listesi hareket fonksiyonu geçersiz bir değere döndürdü.
828 İndeksin geçersiz bir kritik kısmı verildi.
829 Mutex kilidi zaten kaldırılmıştır.
830 Sorgu girdi bir daha ayrılamıyor. Maksimum ayrılabilir girdileri %1$d vardır.
831 Tüm işlem tanımlayıcılar (%1$d) kullanılmaktadır. max_clients parametresini yukarı kaldırın.
832 Yedekleme zaten çalışıyor. Yedekleme iki süreç tarafından idare edilemez.
833 Dizin adı "%1$s" belirsiz. İndeksi sınıf adını belirtin.
834 Kaynak dizesi arasında bazı uyumsuzluklar "%1$s" ve verilen "%2$s" biçim dizesi vardır to_number() .
835 Tanımlanmamış istatistikler öğesi.
836 SAYFASINDA LATCH (%1$d|%2$d) ZAMAN AŞIMI.
837 Veritabanı nesneleri (sınıf / tetik / seri vs) sahibi olan kullanıcılara aittir iptal edemezsiniz.. 
838 Eşzamanlı olarak taranan indeksi %1$d den daha fazla açılamaz .
839 "%1$s": Bilinmeyen sistem parametresi veya bozuk bir değer.
840 Sistem parametresi değiştiremezsiniz "%1$s".
841 İstenen işlem yalnızca tek istemci (işlem) tarafından yürütülebilir.
842 Nesne kilit önbelleğe alamıyor %1$d|%2$d|%3$d.
843 %1$s yanlış argümanlar, %2$s bir geçmiş.
844 Bilinmeyen izolasyon (%1$d) bulunur. Işlem indeksi %2$d.
845 Geçersiz bir nesne türü (%1$d) bulunur.Kilitlenebilir nesne %2$d|%3$d|%4$d.
846 Tran (%2$d) %1$s bir nesnenin sahibi listesinde bulunmayan (%3$d|%4$d|%5$d).
847 %1$s üzerinde %2$s (%3$d|%4$d|%5$d) işlem (%6$d) beklemeye listede bulunmayan (cnt=%7$d).
848 İşlem (%5$d) non2pl listede bulunmaz. Bir %1$s üzerinde (%2$d|%3$d|%4$d).
849 İki kez iptal bir işlem (%1$d) çalışıyorum.
850 Tran (%1$d) bir nesnenin kilit sahibi, ne de kilit bekleyen ne olduğunu (%2$d|%3$d|%4$d).
851 Kilit kaynak (%1$s) ayrılamadı. 
852 Boş bir kilit sahibi listesinde Toplam sahipleri modu (%1$d) NULL_LOCK değildir.
853 Bir nesne için (%1$d|%2$d|%3$d), okuma kaydedilmemiş düzenlenen arıza kilidi (%5$s) tran (%4$d).
854 UYARI: kilit sahibi bulunmamaktadır, ama kilit bekleyenler mevcut. %1$s e başvurun.
855 UYARI: İki veya daha fazla iş parçacığı kilit bekleyen bir işlem (%1$d) içindir.
856 UYARI: Garip LOCKWAIT durumu (%1$d|%2$d), iplik (%3$d|%4$d) ve işlemler (%5$d).
857 Sayfa %1$d yoğunluk "%2$s" kesilmesi sırasında başka bir I/O hata oluştu.
858 Cilt "%1$s" sunucu yeniden başlatma sırasında bilinmiyor.
859 SAYFASINDA LATCH (%1$d|%2$d) BAŞARISISZLIĞA UĞRAMIŞ
860 Durumu '%1$s' olduğundan küresel bir işlemin bir parçası olarak geçerli işlemi yapamazsınız.
861 Bu işlemi bir küresel işlemin bir parçası olarak yapılamaması nedeniyle işlemin tanımlayıcısı %1$d ile geçerli işlem tamamlamaya hazırlayamaz.
862 Durumu '%2$s' olduğundan tanımlayıcı %1$d küresel işlemin kullanıcı bilgileri ayarlanamıyor.
863 Belirteç %1$d olarak ayarlayın çünkü küresel işlemin kullanıcı bilgileri alınamıyor.
864 backupdb/restoredb ayrıntılı dosya '%1$s' açılamıyor.
865 Bilinmeyen tip giriş işaretleri nedeniyle bildirimi yürütülemiyor.
866 Kullanılmayan hata kodu.
867 Kullanılmayan hata kodu.
868 Kullanılmayan hata kodu.
869 Kullanılmayan hata kodu.
870 Kullanılmayan hata kodu.
871 Kullanılmayan hata kodu.
872 Kullanılmayan hata kodu.
873 PKI kimlik doğrulama hatası "%1$s".
874 Bağımsız değişken gücü () aralık dışında.
875 Taşma gücü kapsamında gerçekleşti.
876 Kullanılmayan hata kodu.
877 Verilerin bellekten kaldırılacak biçimde bulunmamakta.
878 Geçersiz veritabanı konumu dosyası, '%1$s'.
879 İzni alınamıyor: '%1$s'.
880 İzni değiştirilemiyor '%1$s'.
881 Kilit dosyası alınamıyor '%1$s(FILE ID:%2$d)'.
882 Kilit dosyası serbest bırakılamıyor 'FILE ID:%1$d'.
883 '%1$s' dosya durumu alınamadı.
884 Volext-path adı '%1$s' yazmak için izin verilmez.
885 '%1$s' '%2$s' arasında geçiş yerine getirilmedi. Aynı aygıt (disk) kullanın.
886 "%1$s" benzersiz kısıtlama ihlaline neden oldu.
887 Saklı prosedür '%1$s' zaten var olur.
888 Parametre sayısı geçersiz. beklenen: %1$d, güncel: %2$d.
889 Saklı prosedür yürütme hatası: %1$s
890 Bölme başarısız oldu.
891 Uygun bir bölüm yok.
892 Birincil anahtar "%2$s" zaten "%1$s" sınıf için tanımlanmış.
893 Öznitelik '%1$s', birincil anahtarın bir üyesidir,iptal edilemedi.
894 Saklı procedure/function '%1$s' bulunmamaktadır .
895 Geçersiz saklı prosedür türü: '%1$s' olan '%2$s'.
896 Sıkıştırma başarısız oldu. Zip Yöntemi: %1$d (%2$s), Zip Seviyesi: %3$d (%4$s)
897 Sıkıştırmayı açma başarısız oldu.
898 Çoğaltma hatası: "%1$s"
899 Geçersiz bölüm talepleri.
900 Java VM kitaplığı bulunanadı: %1$s.
901 Java VM başlayan olamaz: %1$s.
902 Java VM çalışmıyor.
903 Java VM bağlanamıyor: %1$s
904 Geçersiz saklı prosedür adı.
905 JVM ile Ağ başarısız oldu: %1$d
906 Geçersiz java yöntem imzası.
907 DBA grubun sahibi ya da üye saklı prosedür iptal edebilirsiniz.
908 Saklı prosedürün çok fazla bağımsız değişkeni bulunmakta '%1$s'.
909 Eksik veya geçersiz katalog class/vclass bulunur.
910 Bölüm erişimine izin verilmez.
911 Geçersiz çağrı: Bu Resultset geri döndüremez.
912 ResultSet giriş parametresinde kullanılamaz.
913 Çok fazla iç içe stored procedure çağrısı.
914 Bir seri nesnesi önceden otomatik artış kısıtlaması olarak bulunmaktadır.
915 Otomatik artış kısıtlaması değeri artırım 0'dan büyük olmalıdır.
916 Aktif log yoğunluğa bu yedek yoğunluk dahil edilmemiştir(%1$s).
917 Aktif log yoğunluğu zaten var.
918 Yabancı anahtar tarafından yönlendirilen sınıf '%1$s' bulunmamaktadır.
919 Yabancı anahtarının tarafından yönlendirilen birincil anahtarın sınıf '%1$s' bulunmamaktadır.
920 Yabancı anahtar '%1$s' birincil anahtar üye '%2$s' içermez.
921 Yabancı anahtar üye '%1$s' alanı birincil anahtar üye '%2$s' farklıdır.
922 Dış anahtar kelime: '%1$s' değeri nedeniyle, '%2$s' sınırı geçersiz.
923 Birincil anahtar '%1$s' yabancı anahtar '%2$s' tarafından yönlendirilen iptal olması gerekmiyor.
924 Güncelle/Sil işlemleri yabancı anahtar '%1$s' tarafından kısıtlanmıştır.
925 Yabancı anahtar '%1$s' için kilit edinilmesi başarısız oldu.
926 Yabancı anahtar '%1$s' sahip olan örneğini iptal edemezsiniz.
927 Yabancı anahtar '%1$s' anahtar sayısı birincil anahtar '%2$s' farklıdır.
928 Bir kullanıcı değil ancak sistem özniteliği '%1$s' yabancı anahtar 'ON CACHE OBJECT' tarafından oluşturulan atayabilirsiniz.
929 Yabancı anahtar sanal sınıf içinde tanımlanamaz.
930 Bu özniteliği '%1$s' sadece yabancı anahtar kısıtlaması çıkardıktan sonra yabancı anahtar 'ON CACHE OBJECT' tarafından oluşturulan iptal edilebilir.
931 Otomatik artış kısıtlama değeri Başlat değeri max değeriden daha az olmalıdır.
932 Bu "%1$s" yoğunluk için ücretsiz sayfaların sayısını bir tutarsızlığı onarmak mümkün değildir.Etiketli yoğunluk başlığına elde edilen %2$d sayfaları bitmap %3$d sayfaları ile bağdaşmayan olduğundan.
933 Bu "%1$s" yoğunluk için ücretsiz sayfaların sayısını bir tutarsızlığı onarmak mümkün değildir.Etiketli yoğunluk başlığına elde edilen %2$d sektörlerde bitmap %3$d sektörler ile bağdaşmayan olduğundan.
934 Başvurulan Null etki alanı.
935 %1$s fonksiyonunun bağımsız değişkeni aralık dışındadır.
936 Taşma exp bağlamında oluştu.
937 Veritabanı hatası.
938 Geçersiz bağımsız değişkeni.
939 Çok fazla bağlantı vardır.
940 Tanıtıcı geçersiz.
941 İşlemi desteklenen değildir.
942 İşlemi kilitleri beklerken zaman aşımına uğradı.
943 Genel hata.
944 Açıklamada hazır değildir.
945 Açıklamasında herhangi bir sonuç kümesi bulunmamaktadır.
946 Açıklaması yürütülmez.
947 Daha fazla sonuç kümesi bulunmamaktadır.
948 Buffer boyutu yeterli değildir.
949 Mevcut herhangi bir bilgi bulunmamaktadır.
950 Ad geçersiz.
951 Resultset güncelleştirilebilir değil.
952 Satır silindi.
953 Parametrelerin hazırlanmış açıklaması ayarlı değil.
954 Açıklaması toplu açıklama değil.
955 Bu toplu açıklamasını temizleyemezsiniz.
956 Toplu yürütülemiyor.
957 Açıklama açıklaması hazırlanır.
958 Açıklama hazırlanımış açıklama değildir.
959 Açıklaması toplu açıklamadır.
960 Daha fazla hata bulunmamaktadır.
961 Daha fazla sonuç bulunmamaktadır.
962 Bellek yetersiz.
963 Broker Hatası.
964 Sonuç kümesindeki tanıtıcı kapalı.
965 Dizin anahtarı listesi yinelenen öznitelik adlarını kullanamazsınız. Öznitelik adı '%1$s' bir kereden fazla listelenmiştir.
966 İşleminiz (index %1$d, %2$s@%3$s|%4$d) %5$s üzerinde beklerken zaman aşımına uğradı %6$d|%7$d|%8$d nesne üzerinde kilitleyin çünki tıkanıklık var. Bu kullanıcı için bekliyor(s) %9$s bitirmek için.
967 İşleminiz (index %1$d, %2$s@%3$s|%4$d) %5$s üzerinde beklerken zaman aşımına uğradı %6$s sınıf üzerinde kilitleyin çünki tıkanıklık var. Bu kullanıcı için bekliyor(s) %7$s bitirmek için.
968 İşleminiz (index %1$d, %2$s@%3$s|%4$d) %5$s üzerinde beklerken zaman aşımına uğradı %9$s sınıf %6$d|%7$d|%8$d örneği üzerinde kilitleyin çünki tıkanıklık var. Bu kullanıcı için bekliyor(s) %10$s bitirmek için.
969 Sunucu bit platformu (%1$d) (%2$d) istemci bit platformundan farklıdır.
970 Sunucu HA modunda '%1$s' '%2$s' değiştirildi.
971 Programı'%1$s' (pid %2$d) host'%4$s' (port %5$d) veritabanı sunucusu '%3$s' bağlanmış).
972 Programı'%1$s' (pid %2$d) '%3$s'bir ana bilgisayardan bağlandı. (işlem indeksi %4$d)
973 Sunucu durumu %1$s.
974 Arşiv log "%1$s" gelen arşiv sayfaları için oluşturulur %2$lld dan %3$lld.
975 Çoğaltması şu anki sürümü BENZERSİZ sınırlamasına ihlal tek bir GÜNCELLEŞTİRME deyimi ile çoklu satır ayarlanmasına olanak sağlamaz.
976 İç hata: Dosya tablosu sayfa %3$d|%4$d(yoğunluk "%5$s") Tablo boyutu taşması (ayrılan boyutu:%1$d, erişilen boyutu:%2$d).
977 Kontrol noktası çalıştırma (önceki kontrol noktası page id: %1$lld, daha önce yeniden yapılan pageid: %2$lld).
978 Checkpoint finished (checkpoint page id: %1$lld, checkpoint redo page id: %2$lld, flushed page count: %3$d).
979 Kullanıcı verileri döngüsü ile Bağlanın.
980 Bir iş parçacığı %2$d msn %1$s den daha fazla bekleniliyor.
981 İşlem %1$d izleme istatistiklerine %2$s eşiğine ulaşmıştır.
982 İşlem %1$d ile kesme ayarlayın.
983 Yeniden kullanılabilir bir OID sınıfının örnekleri olmayan başvurulabilir . Bu işleme olmayan başvurulabilir örnekler üzerinde izin verilmez.
984 Bu yapılandırma dosyası "%1$s" "[%2$s]" bölümünde "%4$s" ayarlanır "[%5$s]" bölümde "%6$s"'ye %3$s ayarlayamazsınız.
985 Multi ana bilgisayar "databases.txt" olarak ayarlandığında veritabanı bağlantısının dizesinde ana bilgisayar adı belirtilmelidir.
986 CUBRID sinyal özelliği başladı.
987 CUBRID sinyal özelliği durdu.
988 Düğüm olayı: %1$s.
989 Süreç olayı: %1$s. %2$s
990 Komut yürütme: %1$s. %2$s
991 Sayfa buffer Flush mağdur adayları başlatıldı.
992 Sayfa buffer Flush mağdur adayları bitirdi (sayı:%1$d).
993 Taşma bit işletim bağlamında oldu.
994 Bu açıklama hazırlanmış bir açıklama olamaz.
995 %1$s adında hazırlanmış bir açıklama bulunmamaktadır.
996 Verilen değerlerin sayısı yanlış. %1$d değerleri verilmiştir ama %2$d değerleri gereklidir.
997 %2$s bölümlendirilmiş için yabancı anahtar kısıtlaması eklenemiyor %1$s . Başvurusal eylemler güncelleme özellikleri henüz bölümlendirilmiş sınıfları desteklenmiyor.
998 %2$s özniteliğinde yabancı anahtar kısıtlaması eklenemiyor %1$s . Tekrar SET NULL başvuru eylem eşleşecek şekilde çünkü özniteliği bir NOT NULL kısıtlaması olamaz.
999 '%2$s'tablo gibi '%1$s' tablo oluşturulamıyor çünki mevcut tablo (%3$s) çoğaltılamaz edilmeyecek özelliklere sahip.
1000 '%1$s' CLASS veya SHARED özniteliği fakat yalnızca normal özniteliklerini bu kapsamda izin verilir.
1001 Beklenmedik bir koşul ya da durum ulaşıldı. '%1$s'
1002 Geçerli işlem bu işleme devam etmek için gereken bir veri tabanı kilidi aquire bulunamamamıştır.
1003 Kısıtlaması '%1$s' var ama farklı bir türü vardır.
1004 TABLO DEĞİŞTİRME DROP FOREIGN KEY( değiştirebilir yabancı anahtar tablo iptal) kullanırken, CUBRID kısıtlaması ve ilişkili tüm indeksi iptal ediliyor unutmayın.
1005 Kullanılmayan hata kodu.
1006 Kullanılmayan hata kodu.
1007 Benzersiz, yabancı anahtar veya birincil anahtar kısıtlamaları üzerine önek uzunluğu dizin oluşturulamıyor.
1008 Bölümlendirilmiş sınıfı önek uzunluğu dizin oluşturulamıyor.
1009 COMPACTDB zaten başlamış durumda.
1010 Etki alanı "%1$s" önek uzunluğu indeksi tanımlayamazsınız.
1011 Paylaşılan özniteliği %2$s yabancı anahtar kısıtlaması %1$s eklenemiyor.
1012 NULL sütun türü ile tablo oluşturulamıyor.
1013 VARSAYILAN veya ORTAK ayarlayın veya %1$s yazılı sütun üzerindeizin verilmez.
1014 %1$s yazılı sütun üzerinde NOT NULL olarak ayarlamaya izin verilmez.
1015 Belirtilen dizin '%1$s' yok.
1016 %1$s harici veri depolama hatası: %2$s
1017 Harici veri depolama '%1$s' için path geçersiz.
1018 Depolama farklı tipte dış dosyaya kopyalanamıyor. (kaynak %1$s hedef %2$s)
1019 Path "databases.txt" belirlenen olmadığı için harici veri depolama başlatılmaz.
1020 Harici dosya "%1$s" bulunamadı.
1021 Bir deadlock döngüsü algılandı. %1$s.
1022 İndeksin önek uzunluğu için geçersiz değer "%1$d".
1023 HA hata kodu saklıdır.
1024 log writer: failed to get log page(s) starting from page id %1$lld.
1025 HA delay info: The replication delay (%1$d secs) has exceeded the limit (%2$d secs).
1026 HA delay info: The replication delay (%1$d secs) is decreased below the acceptable level (%2$d secs).
1027 uygulayıcı log: '%2$s' için '%1$s' durum onayı değiştirme başarısız oldu.
1028 uygulayıcı log: arşiv log beklenmedik EOF kaydı. LSA: %1$lld|%2$d.
1029 uygulayıcı log: geçersiz çoğaltma log page/offset. sayfa HDR: %1$1lld|%2$d, final: %3$lld|%4$d, ekleme LSA: %5$lld|%6$d, EOF LSA: %7$lld|%8$d, ha dosya durumu: %9$d, is end-of-log: %10$d.
1030 uygulayıcı log: geçersiz çoğaltma kayıt. LSA: %1$lld|%2$d, forw LSA: %3$lld|%4$d, backw LSA: %5$lld|%6$d, Trid: %7$d, önceki tran LSA: %8$lld|%9$d, tür: %10$d.
1031 uygulayıcı log: şema çoğaltma log uygulanması başarısız oldu. sınıfı: "%1$s", şema: "%2$s", İç hata: %3$d.
1032 uygulayıcı log: ekleme çoğaltma log uygulanması başarısız oldu. sınıfı: "%1$s", anahtar: "%2$s", İç hata: %3$d.
1033 uygulayıcı log: güncelleme çoğaltma log uygulanması başarısız oldu. sınıfı: "%1$s", anahtar: "%2$s", İç hata: %3$d.
1034 uygulayıcı log: silme çoğaltma log uygulanması başarısız oldu. sınıfı:  "%1$s", anahtar: "%2$s", İç hata: %3$d.
1035 uygulayıcı log: hafıza boyutu(%1$d MB) log uygulayıcısı max hafıza boyutu büyükse (%2$d MB) veya daha az 2 kat büyümesini edilmiştir (%3$d MB). gereken LSA: %4$lld|%5$d. son kararlı LSA: %6$lld|%7$d.
1036 uygulayıcı log: log uygulayıcısı sinyal kendini kapattı.
1037 yazıcı log: log yazar sinyal kendini kapattı.
1038 Landed kullanıcı: landed kullanıcının çalıştırılması. Gereksinimleri LSA: %1$lld|%2$d. son uygulama LSA: %3$lld|%4$d. son uygulama repl LSA: %5$lld|%6$d.
1039 log writer: log yazar başladı. modu: %1$d.
1040 HA genel: %1$s.
1041 Bir dize "%1$s" çerçevesinde eksik kalırdı.
1042 Izin verilen maksimum %2$d bayt iken, bellek %1$d byte gerektiren bir dize oluşturmak için çalışıyorum.
1043 "%1$s" özniteliği değiştirilemiyor. Sınıfın alt sınıfları varsa CUBRID istenen nitelik özelliklerini değiştiremezsiniz.
1044 "%1$s" özniteliği değiştirilemiyor. CUBRID anahtarları bölümleme öznitelikleri değiştiremezsiniz.
1045 "%1$s" özniteliği değiştirilemiyor. CUBRID (ya başvurulan veya başvuran) yabancı tuşları kullanılan niteliklerini değiştiremezsiniz.
1046 "%1$s" özniteliği değiştirilemiyor. CUBRID özniteliğin alanı değiştiremezsiniz. Alanı ile desteklenir bu değişiklik yoktur.
1047 "%1$s" özniteliği değiştirilemiyor. CUBRID öznitelikleri alanı değiştiremezsiniz.Yeni etki doğru tüm mevcut öznitelik değerleri temsil edemez.
1048 "%1$s" özniteliği değiştirilemiyor. CUBRID henüz bir özniteliğin auto_increment özniteliğin etki alanı da değiştirmesi durumunda değiştiremezsiniz.
1049 "%1$s" özniteliği değiştirilemiyor. CUBRID özniteliğin etki alanı henüz değiştiremezsiniz. Etki alanı dönüşüm mümkün ama bu özelliği yapılandırması tarafından izin verilmiyor.
1050 "%1$s" özniteliği değiştirilemiyor. CUBRID özniteliğin etki alanı henüz değiştiremezsiniz.Özniteliği üzerinde bir dizin vardır.
1051 "%1$s" özniteliği değiştirilemiyor. CUBRID kısıtlama eklemek için öznitelik henüz değiştiremezsiniz. Mevcut öznitelik değerleri kısıtlaması kontrol edilmeyebilir.
1052 Öznitelik "%1$s" değişmedi. CUBRID did not detect any effective changes in the attribute representation.
1053 Açıklamalar  REPLACE INTO... ve INSERT ... ON DUPLICATE KEY UPDATE bir intikal zinciri parçası olan sınıflar için izin verilmemiştir.
1054 Otomatik artış kısıtlama yeni değeri veya daha büyük mevcut değerine eşit olmalıdır.
1055 Otomatik artış kısıtlama yeni değeri maksimum değerden daha düşük olmalıdır.
1056 Karışıklığı önlemek için auto_increment tablosu seçeneğini tablo tam olarak bir tane AUTO_INCREMENT sütunu ve herhangi bir çekirdek/artırma özellikleri olması gerekir.
1057 VARSAYILAN değer içermeyen bir NOT NULL '%1$s' yazılmış özniteliği eklenemiyor.
1058 TABLO DEĞİŞTİRME .. DEĞİŞİM: Yeni bir etki alanı için değiştirme: döküm başarısız oldu, mevcut yapılandırma kesme veya taşmaya izin vermez.
1059 TABLO DEĞİŞTİRME .. DEĞİŞİM: Yeni bir etki alanı için değiştirme: döküm başarısız oldu, yeni bir etki alanının varsayılan değer kuruldu.
1060 TABLO DEĞİŞTİRME .. DEĞİŞİM: Yeni bir etki alanı için değiştirme: döküm başarısız oldu, yeni bir etki alanının minimum değeri ayarlandı.
1061 TABLO DEĞİŞTİRME .. DEĞİŞİM: Yeni bir etki alanı için değiştirme: döküm başarısız oldu, yeni bir etki alanının maksimum değeri ayarlandı.
1062 "%1$s" özniteliği değiştirilemiyor.Değişiklik tanımlanan birden fazla birincil anahtarları neden olacaktır.
1063 Öznitelik "%1$s" için NULL kısıtlaması eklenemiyor:Bu özellik için mevcut NULL değerleri vardır.
1064 TABLO DEĞİŞTİRME .. DEĞİŞİM: NOT NULL ekleme:Varolan tüm NULL değerleri etki alanı sabit varsayılan değiştirildi.
1065 "%1$s" özniteliği değiştirilemiyor. CUBRID NULL kısıtlaması ekleyemezsiniz:sert bir varsayılan değer yeni etki alanı için mevcut değil.
1066 Aktif kalma süresi dolmuş.
1067 Sütun '%1$s' bir NOT NULL kısıtlaması ve bir NULL değeri olamaz.
1068 Maksimum tetikleyici derinliği %1$d geçemez.
1069 Çok fazla sayıda hazırlanmış durum.
1070 Aktif kalma değişkeni '@%1$s' tanımlı değil.
1071 Çok fazla sayıda oturum değişkenleri bulunmakta.
1072 IP adresi (%1$s) yetkili değil.
1073 Dosya biçimi geçersiz (%1$s).
1074 Erişim listesi dosyası okunamıyor(%1$s).
1075 Azalan indeks taraması nedeniyle indeksi tanımlayıcısı ile B+tree üzerinde düşük öncelik iptal edildi:(vfid = (%1$d, %2$d), rt_pgid: %3$d).
1076 Sistem parametresi yüklenemedi.
1077 Dosya '%3$s' satır %2$d '%1$s' parametresi: Bilinmeyen parametre.
1078 Başlangıç yerideki %1$d özellikleri güncel kod ayarını geçersiz.
1079 Veri tabanı kod takımları (%1$s) ve sunucu konfigürasyonu (%2$s) uyumlu değildir.
1080 Fitre dizesi uzunluğu en fazla %1$d olmalıdır.
1081 Filtre veya fonksiyon indeksi özellikleri ile ilgili değişiklik yapılamaz.
1082 Tüm sayfa tamponlar kirlidir (LRU: %1$d).
1083 Bilgisayar çöker hakkında belirli koşullar.\n%1$s
1084 Kontrol noktasındaki geçersiz sayfa numasından atlamak. (page id: %1$d, "%2$s", oldest_unflush_lsa: %3$lld|%4$d, önceki kontrol redo lsa: %5$lld|%6$d)
1085 Düzenlenemez Konvansiyonel ifadesi: düzenlemesi : '%1$s'
1086 Konvansiyonel ifadesi gerçekleştiremiyor: '%1$s'
1087 Yedek inisiyatif günlükcü çalıştırımalı'%1$s'
1088 Yedek inisiyatif günlükcü'%1$s' tamamlanmıştır
1089 Kaynak ayırma hatası. Yüksetilmiş max_bestspace_entries=%1$d '.
1090 Konum ilklendimesi: %1$s.
1091 Konumun var olması: %1$s.
1092 Bigisayar değişken'%1$s' türünün ifadesi hazırlanmamalıdır.
1093 inet_aton'ın arg '%1$s, ipv4 adresinde ayarlanan geçerli dizesi değildir.
1094 inet_aton'ın arg '%1$lld, ipv4 adresinde ayarlananr geçerli dijital değildi.
1095 Kullanıcı adı çok uzun
1096 Ne zaman bölğm düzeyinde dış anahtar kelimeler referans için kullandığı zamanda, Değişiklik yapılmakta olan bölüm yapısına izin vermez.
1097 '%1$s'kapısitesinde bir ilk PRIMARY KEY kelimelerde bir sınırlama ile geçersiz NULL değeri olamaz. 
1098 Dil '%1$s' konumu karakter kümesindeki '%2$s' kullanılmaz.
1099 DDL açıklaması konfigürasyon tarafından izin verilmemiştir (block_ddl_statement=yes).\n SQL Text: %1$s
1100 Jümlelerde görülmeyen konumun ifadesi dış boyutlar tarafından izin verilmez(block_nowhere_statement=yes)
1101 Kullanılmayan hata kodu.
1102 Unknown system parameter or bad value.
1103 Cannot change system parameter.
1104 Yavaş sorgula (%1$d msec)\n%2$s.
1105 İç hata: kirli nesnenin temizlenmesi kısmi başarısız
1106 Kaynak tablosunda çoklu satırlar hedef tabloda aynı satır ile uyumlu.
1107 NTILE için geçersiz bellek bölümü numarası. Sıfırdan büyük ve 2,147,483,647 den küçük olmalıdır.
1108 WIDTH_BUCKET için geçersiz bellek bölümü numarası. Sıfırdan büyük ve 2,147,483,647 den küçük olmalıdır.
1109 Bölüm tanımlama için geçersiz değer.
1110 Btree yaprak sayfasında yetersiz alan. (key len: %1$d)\n%2$s
1111 Sonuç değeri kısaltıldı, çünkü hassasiyet (%1$d) uzunluğundan az(%2$d).
1112 Bir karakter '%1$s' dan '%2$s' a dönüştürülemedi.
1113 Aralık dışındaki eleman indeksi.
1114 Argüman '%1$s' aralık dışında.
1115 Güncelleştirme istatistikleri başladı (class "%1$s", oid : %2$d|%3$d|%4$d).
1116 Güncelleştirme istatistikleri tamamlandı(class "%1$s", oid : %2$d|%3$d|%4$d, error code : %5$d).
1117 Özellik "%1$s" değiştiremezsiniz. CUBRID bir SHARED ve tersi gibi, nitelik değiştiremezsiniz.
1118 "%1$s" argümanı istenen etki alanı "%2$s" zorlanamadığında edilemez.
1119 Dahili hata: Page id %1$d hacmi "%2$s" tahsisi haritasına göre tahsis edilir, ancak herhangi bir dosyaya ait değildir.
1120 Dahili hata: Page id %1$d hacmi "%2$s" ise şu anda kullanılmaktadır, ama ses tahsisi haritasına göre tahsis değildir.
1121 NOT NULL kısıtlamaları NULL değeri izin vermez.
1122 Veri alma zamanı.
1123 pthread_cond_timedwait() zaman aşımına uğradı.
1124 Sorgu yürütme hatası. ERROR_CODE = %1$d, /* SQL_ID: %2$s */ %3$s
1125 Taşma anahtar dosyası oluştur. INDEX %1$s%2$s ON CLASS %3$s%4$s. key: %5$s%6$s.
1126 Yeni bir taşma sayfası oluştur. INDEX %1$s%2$s ON CLASS %3$s%4$s. key: %5$s%6$s.
1127 Boş bir taşma sayfayı sil. INDEX %1$s%2$s ON CLASS %3$s%4$s. key: %5$s%6$s.
1128 Oturum kurtarma başlatılır. Uygulanacak günlük kayıt sayısı: %1$lld. Log page: %2$lld ~ %3$lld.
1129 Oturum kurtarma bitti.
1130 İşlem kilit sayıları %1$d aştığı için işlem iptal edilir.
1131 Dahili hata: Sayfa %1$d hacmi "%2$s"de bozulabilir.\n%3$s
1132 Şifreleme kitaplığı hatası: %1$s.
1133 %1$s için copylogdb bulunmaktadır.
1134 %1$s için applylogdb bulunmaktadır.
1135 B+tree(%1$s) bir önceki bağlantısı bozuk: vpid = (%2$d, %3$d).
1136 B+tree(%1$s) bir önceki bağlantısı onarıldı: vpid = (%2$d, %3$d).
1137 Sorgu izin verilen enbüyük yuvalama seviyesini (%1$d) geçmekten nedeniyle girişimi reddedilmektedir.
1138 Bağlantı kurma hatası (emsal host %1$s): uyumsuz kesinti. (kullanıcı: %2$s, sunucu: %3$s).
1139 Bağlantı kurma hatası (emsal host %1$s): uyumsuz okuma/yazma modu  (kullanıcı: %2$s, sunucu: %3$s).
1140 Bağlantı kurma hatası (emsal host %1$s): HA kopyalama gecikti.
1141 Bağlantı kurma hatası (emsal host %1$s): replica-only kullanıcıdan non-replica sunucuya.
1142 Bağlantı kurma hatası (emsal host %1$s): tanımlanamayan sunucu versiyonu.
1143 Bağlantı kurma hatası (emsal host %1$s): sunucuya uzaktan erişim yasaktır.
1144 %1$s bağlanmaya çalışırken zaman aşımına uğradı (zamanaşımı: %2$d sec(s)).
1145 Sistem sınıfı sahibini değiştirmekye yasaktır.
1146 %1$d hacım tanıtıcı bulunmamaktadır.
1147 (%1$d) nolu XASL ağaçın boyutu (%2$d) alt sınırı aşmaktadır. Çünkü tüm cache girişler kullanılmış hiç mağdur bilgi yoktur. Yeni bir giriş eklendi.
1148 (%1$d) nolu cache yüklem filtre boyutu (%2$d) alt sınırı aşmaktadır. Çünkü tüm cache girişler kullanılmış hiç mağdur bilgi yoktur. Yeni bir giriş eklendi.
1149 %2$d hacımın %1$d sayfa bulunmaktadır.
1150 İçerik uyumlu karşılaştırma gerektirmektedir.
1151 %2$d hacımın %1$d sayfa yuva donanımlı değildir.
1152 The owner or a member of DBA group is only allowed to kill the transaction (%1$d).
1153 Attempt to use 'zero date'.
1154 MVCC row %1$d|%2$d|%3$d does not satisfies reevaluation.
1155 MVCC invalid row for delete: %1$d|%2$d|%3$d.
1156 MVCC can't get snapshot
1157 Isolation level value in MVCC must be 'read committed', 'repeatable read' or 'serializable'.
1158 Serializable conflict due to concurent updates
1159 Son Hata

$set 6 MSGCAT_SET_INTERNAL
1 Alt Hata içinde hata (satır %1$d):
2 Uygun hata mesajı bulunmamakta.
3 %1$d byte tahsis edemez.
4 "%1$s" mesaj kataloğu bukunamıyor .
5 %1$d hata kodu için mesaj kayıp.
6 ... İPTAL ETMEK /DERHAL ÇIK ...\n
7 Çıkmak istiyor musunuz? 1/0
8 Bilinmeyen dosya.
9 Uygun mesaj bulunmamakta; Bu mesajı yanlışlıkla orijinal yerine biçimlendirilmiş.
10 er_init: *** doğru değil exit_ask değer = %1$d; %2$s yerine üstlenecek . ***\n
11 er_start: *** UYARI:Mesaj log açılamıyor "%1$s"; stderr yerine üstlenecek. ***\n
12 er_study_fmt: %1$d hata kodu için şüpheli mesaj.
13 er_estimate_size:bilinmeyen dönüşüm kodu (%1$d).
14 \n\n*** Mesaj log panaromik. Mesajlar dosyanın üstünde devam edecektir. ***\n\n
15 \nTime: %1$s - %2$s *** %3$s KOD = %4$d, Tran = %5$d%6$s\n%7$s\n
16 CUBRID (pid: %1$d) *** %2$s *** %3$s KOD = %4$d, Tran = %5$d %6$s
17 \nTime: %1$s - %2$s *** dosya %3$s, satır %4$d %5$s KOD = %6$d Tran = %7$d%8$s\n%9$s\n
18 CUBRID (pid: %1$d) *** %2$s *** dosya %3$s, satır %4$d, %5$s KOD = %6$d, Tran = %7$d. %8$s
19 \n*** Önceki hata mesajı sonuncusudur. ***\n\n
20 \nTime: %1$s - DEBUG *** dosya %2$s, satır %3$d\n
21 Mail -s "Sunucu Durduruldu"
22 --->>>\n Aşağıdaki hata kurulduğunda %1$s sizin isteğiniz üzerine durduruldu:\n errid = %2$d, %3$s\nKullanıcı: %4$s, pid: %5$d, host: %6$s, zaman: %7$s<<<---\n
23 %1$s ,errid = %2$d üzerine durduruldu. Kullanıcı: %3$s, pid: %4$d
24 er_init: "%1$s" olay işleyicisi yükleyemezsiniz \n

$set 7 MSGCAT_SET_PARSER_SYNTAX
1 Lütfen '%1$s' sözdizimi kısmını kontrol edin, beklenen %2$s.
2 Lütfen '%1$s' sözdizimi kısmını kontrol edin, %3$s içinde beklenen %2$s.
3 Lütfen '%1$s' belirteç doğruluğunu kontrol edin.
4 'kaydedilmemiş şema okuma' kabul edilemez, kullanarak \n'kaydedilmemiş şema okuma' yerine.
5 Maksimum karakter dize uzunluğu 16383.
6 %1$s, %2$s sınırını aşarsa.
7 En fazla bit dize uzunluğu %1$d bits.
8 Join koşulu yan tümcesinde bir alt sorgu kullanamazsınız.
9 Güncelleştirme ayrıcalığı maddesinin öznitelik "(%1$s)" belirlemek durumu grant/revoke edemezsiniz.
10 '%1$s' anahtar kelime kullanımı geçersiz , beklenen %2$s.
11 Token boyu çok uzun.
12 invalid data type
13 invalid attach statement\n  attach_statement: ATTACH unsigned_integer
14 invalid prepare statement\n  prepare_statement:  PREPARE {to} COMMIT unsigned_integer
15 invalid execute statement\n  execute_statement:  EXECUTE DEFERRED TRIGGER [identifier {, identifier}* | ALL TRIGGERS]
16 invalid scope statement\n  scope_statement: SCOPE trigger_action { FROM table_spec_list }
17 invalid set system parameter\n  set_system: SET SYSTEM PARAMETERS 'STRING' {, 'STRING_N'}*
18 invalid set transaction\n  set_transaction: SET TRANSACTION ISOLATION LEVEL expression {, expression}\n                 | SET TRANSACTION LOCK TIMEOUT timeout_spec
19 invalid set trigger trace\n  set_trigger: SET TRIGGER TRACE [ON|OFF|unsigned_integer|parameter|host_param]
20 invalid set trigger depth\n  set_trigger: SET TRIGGER {MAXIMUM} DEPTH [unsigned_integer|parameter|host_param]
21 invalid set optimization level\n  SET OPTIMIZATION LEVEL {=|to} [ON|OFF|unsigned_integer|parameter|host_param]
22 invalid set optimization cost\n  SET OPTIMIZATION COST {of} 'STRING' {=|to} literal_
23 invalid get optimization level\n  GET OPTIMIZATION LEVEL {[INTO|TO] [host_param|parameter|identifier]}
24 invalid get optimization cost\n  GET OPTIMIZATION COST {of} 'STRING' {[INTO|TO] [host_param|parameter|identifier]}
25 invalid get transaction isol\n  GET TRANSACTION ISOL LEVEL {[INTO|TO] [host_param|parameter|identifier]}
26 invalid get transaction lock\n  GET TRANSACTION LOCK TIMEOUT {[INTO|TO] [host_param|parameter|identifier]}
27 invalid get trigger trace\n  GET TRIGGER TRACE {[INTO|TO] [host_param|parameter|identifier]}
28 invalid get trigger depth\n  GET TRIGGER {MAXIMUM} DEPTH {[INTO|TO] [host_param|parameter|identifier]}
29 invalid get stat\n  GET STATISTICS 'STRING' {[INTO|TO] [host_param|parameter|identifier]}
30 invalid create index\n  CREATE {REVERSE} {UNIQUE} INDEX identifier ON {only} class_name index_column_name_list {WHERE where_clause}
31 invalid create user\n  CREATE USER identifier {PASSWORD 'STRING'} {GROUPS identifier {, identifier}* } {MEMBERS identifier {, identifier}* }
32 invalid create trigger\n  CREATE TRIGGER identifier {STATE [ACTIVE|INACTIVE]} {PRIORITY unsigned_real}\n    [BEFORE|AFTER|DEFERRED] event_spec {IF trigger_condition}\n    EXECUTE {AFTER|DEFERRED} trigger_action
33 invalid create serial\n  CREATE SERIAL identifier {START WITH integer} {INCREMENT BY integer}\n    serial_min_max {CYCLE|NOCYCLE} {CACHE unsigned_integer|NOCACHE}
34 invalid create procedure\n  CREATE PROCEDURE identifier '(' {sp_param_list} ')' {IS|AS} LANGUAGE JAVA NAME 'STRING'
35 invalid create function\n  CREATE FUNCTION identifier '(' {sp_param_list} ')' RETURN {data_type|CURSOR} {IS|AS} LANGUAGE JAVA NAME 'STRING'
36 invalid groups\n  groups spec: GROUPS identifier {, identifier}*
37 invalid members\n  member spec: MEMBERS identifier {, identifier}*
38 invalid password\n  password spec: PASSWORD 'STRING'
39 missing authorized command list\n  authorized command = SELECT, INSERT, INDEX, DELETE, UPDATE, ALTER, ADD, DROP, EXECUTE, REFERENCES, ALL PRIVILEGES, ALL 
40 missing class spec list
41 missing identifier list
42 missing expression
43 invalid identifier
44 invalid use of substring\n  SUBSTRING( expression FROM expression FOR expression )\n  SUBSTRING( expression FROM expression )
45 invalid use of trim\n  TRIM ( [LEADING|TRAILING|BOTH] expression FROM expression )\n  TRIM ( [LEADING|TRAILING|BOTH] FROM expression )\n  TRIM ( expression FROM expression )\n  TRIM ( expression )
46 invalid use of cast\n  CAST ( expression AS data_type )
47 function add_months needs two parameters
48 octet_length needs one parameter
49 bit_length needs one parameter
50 lower needs one parameter
51 upper needs one parameter
52 translate needs three parameters
53 replace needs two or three parameters
54 invalid use of to_number\n  TO_NUMBER ( expression , char_string )\n  TO_NUMBER ( expression )
55 string bind operator is not '|' but '||'
56 invalid alter statement
57 invalid drop statement
58 invalid create statement
59 invalid relational operator
60 equal operator is not '==' but '='
61 not equal operator is not '!=' but '<>'
62 invalid minus value (or minus value in list)
63 duplicated reference rule
64 SYS_CONNECT_BY_PATH needs two parameters and the second must be a string literal.
65 Invalid unsigned integer %1$s.
66 IF needs three parameters: the first must be a logical expression, the second and third must be expressions evaluating to either a numeric or a string type.
67 IFNULL needs two parameters which must be expressions evaluating to either a numeric or a string type.
68 invalid use of isnull\n  ISNULL ( expression )
69 invalid use of left\n  LEFT ( str , len )
70 invalid use of right\n  RIGHT ( str , len )
71 invalid use of mod\n MOD( expression, expression )
72 invalid use of adddate\n ADDDATE( expression, expression )
73 invalid use of date_add\n DATE_ADD( expression, INTERVAL expression unit)
74 invalid use of subdate\n SUBDATE( expression, expression )
75 invalid use of date_sub\n DATE_SUB( expression, INTERVAL expression unit)
76 invalid use of user / system_user\n USER() / SYSTEM_USER()
77 invalid use of timestamp\n TIMESTAMP( expression ), TIMESTAMP( expression, expression )
78 invalid use of database\n DATABASE()
79 invalid use of current_time\n CURRENT_TIME()
80 invalid use of current_date\n CURRENT_DATE()
81 invalid use of current_timestamp\n CURRENT_TIMESTAMP()
82 invalid use of now\n NOW()
83 invalid use of default\n DEFAULT(column_name)
84 invalid use of date\n DATE(expression)
85 invalid use of localtime\n LOCALTIME()
86 invalid use of localtimestamp\n LOCALTIMESTAMP()
87 invalid use of schema\n SCHEMA()
88 invalid use of truncate\n TRUNCATE( expression, expression )
89 invalid use of str_to_date\n STR_TO_DATE( expression, string_literal )
90 invalid use of current_datetime\n CURRENT_DATETIME()
91 invalid use of insert\n INSERT( expression, expression , expression, expression )
92 invalid use of elt\n ELT(expression [, expression]...)
93 invalid use of year\n YEAR( expression )
94 invalid use of month\n MONTH( expression )
95 invalid use of day\n DAY( expression )
96 invalid use of hour\n HOUR( expression )
97 invalid use of minute\n MINUTE( expression )
98 invalid use of second\n SECOND( expression )
99 invalid use of quarter\n QUARTER( expression )
100 invalid use of week\n WEEK( expression ), WEEK( expression, expression)
101 invalid use of time\n TIME(expression)
102 invalid use of group_concat\n GROUP_CONCAT (([DISTINCT] {col | expr} \n [ORDER BY {col | unsigned_int} [ASC | DESC] ] \n [SEPARATOR str_val])
103 Dizin ipuçlarının geçersiz kullanımı
104 Bit dizgesinin uzunluğu en fazla %1$d bittir.
105 Sözdizim hatası: unexpected
106 , expecting '{'
107 , expecting SELECT or '('
108 , expecting
109 unexpected
110 END OF STATEMENT
111 In line %1$d, column %2$d before '%3$c%4$s'\n
112 In line %1$d, column %2$d before %3$s\n
113 before ' %1$s'\n
114 before END OF STATEMENT\n
115 Geçersiz grup\n adı: SET NAMES charset [COLLATE collation]\n
116 invalid use of chr\n  CHR ( number [using charset] )\n
117 Karakter kümesi kullanımı geçersiz \n CHARSET ( expression )\n
118 derlemenin geçersiz kullanımı \n COLLATION ( expression )\n
119 clob_to_char geçersiz kullanımı\n CLOB_TO_CHAR ( expression [using charset] )\n
120 index_prefix geçersiz kullanımı\n INDEX_PREFIX ( expression, expression, expression )\n
121 UNION ve ORDER BY kullanımı hatalıdır.
122 ON beklemektir. Harici join için join durumu gereklidir.

$set 8 MSGCAT_SET_PARSER_SEMANTIC
1 Bellek yetersiz.
2 Function %1$s tanımsız.
3 ldb '%1$s' veritabında bulunamıyor.
4 Sütunların sayısı, %1$d, sol sorgulama içinde eşleşmiyor\nSütunların sayısı, %2$d, sağ sorgulama içinde.
5 '%1$s' ile uyumlu birleşme '%2$s' değil.
6 %1$s tanımlı değil.
7 %1$s etki alanı bir vclass olamaz.
8 %1$s etki alanı bir proxy vclass olamaz.
9 %1$s etki alanı bir class olamaz.
10 %2$s nin bir özniteliği '%1$s' değildir.
11 %1$s bu sınıftan değiştirilemez.\n %2$s dan bir artakalandır.
12 Class %1$s bulunmamaktadır.
13 %1$s bir %2$s değildir.
14 %1$s bir metod veya öznitelik %2$s değildir.
15 %1$s olmayan ve herhangi bir sorgu özellikleri olmamalıdır.
16 %1$s veritabanında tanımlı değildir.
17 %1$s bir %2$s süpersınıfı değildir.
18 Class %1$s non-class %2$s dan devralır.
19 VClass %1$s non-vclass %2$s dan devralır.
20 Proxy vclass %1$s non-proxy vclass %2$s dan devralır.
21 %1$s zaten bir %2$s süpersınıfı.
22 %1$s kendisinin bir süper sınıfı olamaz.
23 %1$s zaten bir %2$s altsınıfıdır.
24 %1$s tek değerli değildir. Naggregate sorgularında maruz kalan öznitelikler yan tümcesi tarafından grubunda yer almalıdır.
25 Sütünların sayısı(%1$d) ve into_names(%2$d) eşit değildir.
26 Class %1$s zaten bulunmakta.
27 Super class %1$s '%2$s' içinde bulunmamaktadır.
28 Yan tümcesi '%1$s' anlamlı bir INHERIT yapmak için bir SUBCLASS yan tümcesi beklemektir.
29 INHERIT yan tümcesi '%1$s' başvuruları SUBCLASS yan tümcesi '%2$s' bulunmayan bir sınıf.
30 Class bir sorgu özelliklerine sahip olamaz.
31 %1$s bir kayıtlı ldb değil.
32 Bir proxy varisi kendine ait object_id yan tümcesi olmayabilir. Kalıtımsal object_id öznitelik (ler) geçersiz yapılamaz.
33 Proxy vclass birden fazla sorgu özelliklerine sahiptir.
34 Özniteliklerin sayısı, %1$d, sütunların sayısı ile eşleşmemektedir,\n%2$d, sorgu özellikleri içinde.
35 %1$s için beklenen bir öznitelik adı eksik.
36 Öznitelik '%1$s' sütun '%2$s' sorgu özelliği ile uyumlu değildir.
37 %1$s sınıf değildir.
38 Endeksleri sanal sınıflar da oluşturulmuş olmayabilir.
39 Endeksleri, sadece tek bir özniteliği oluşturulabilir.
40 Yan tümcesi birden fazla sınıflar da geçersiz kullanımı.
41 Sistem hatası - Çözünürlük %1$s başarısız oldu.
42 Türetilmiş bir tablo silemeye bilirsiniz.
43 Kullanıcı %1$s veritabanında değil.
44 Güncelleme kümeleme içeremez.
45 Her sınıfta özniteliği adlarının benzersiz olması gerekir. Öznitelik adı '%1$s' sınıf '%2$s' bir kereden fazla belirtildi.
46 %1$s.%2$s birden fazla atama var..
47 Sıralama özellikleri sayısı bir tamsayı değildir.
48 Sıralama özellikleri %1$d aralık dışında.
49 Öğe tarafindan bir tamsayı değildir.
50 Sıralama özellikleri %1$s herhangi bir seçeneği sütununda eşleşmiyor.
51 Sütun %1$s için çelişkili sıralama yönü bulunmaktadır.
52 Sıralama özellikleri %1$s bir numarası, adı veya path anlatım değildir.
53 Ekleme anlatım sadece ekleme açıklamasında görünebilir.
54 Seçilen özniteliklerin (%1$d) ve sütunların (%2$d) sayısı eşit değildir.
55 Özniteliklerin (%1$d) ve değerlerin (%2$d) sayısı eşit değildir.
56 Veri türü %1$s üzerinde veri taşması.
57 Özniteliğin %1$s üzerinde uyumsuz veri türü.
58 %1$s\n tek bir sınıfında bir SELECT değildir.
59 `*' proxy vclass dizayn edilmiş sorgu belirleme geçerli bir seçim listesi değildir.
60 %1$s ne bir vclass ne de proxy vclass değildir.
61 Birden fazla yalıtım düzeyinde yan tümceleri vardır.
62 Birden fazla zaman aşımı yan tümceleri bulunmaktadır.
63 Hiçbir yalıtım düzeyine girilemedi.
64 Operatör BETWEEN türleri %1$s, %2$s ve %3$s tanımlı değildir.
65 '%1$s' operatör tiplerinin %2$s ve %3$s tanımlı değildir.
66 Fonksiyon argümanları olması gerekir: %1$s.
67 Uyumsuz işlenenler: %1$s(%2$s).
68 Toplama işlevi 1 argüman olması gerekir: %1$s.
69 Sıfıra bölme girişimi.
70 Veri taşması %1$s yazmak için %2$s zorluyor.
71 %1$s yazmak için %2$s zorlama olamaz.
72 '%1$s' tipi SET, MULTISET veya SEQUENCE olması gerekir.
73 '%1$s' tam olarak bir dizi öğe türü olmalıdır.
74 %1$s birden fazla türetilmiş sütun adı vardır.
75 %1$s türetilmiş sütun adı vardır.
76 %1$s sütunlar (%2$d) ve sütun adlarının (%3$d) karşılık gelen bir numarası bulunmamaktadır.
77 %1$s içinde herhangi bir öznitelikleri bulunmaktadır.
78 %1$s içinde tek bir tablo bekleniyor.
79 Açıkta kalan adı %1$s belirsiz.
80 Türetilmiş sütun adları '%1$s' basit sınıf özellikleri için izin verilmez.
81 Türetilmiş tablo '%1$s' bir ilişki adı olmalıdır.
82 Yetkilendirme hatası, %1$s sınıfı seçin.
83 Türetilmiş bir tablo adı için sınıf örneği başvurusu %1$s izin verilmez.
84 Path bağıntı (%1$s) içsel path dönem dışında görünür.
85 %1$s Referans belirsiz.
86 %1$s class özniteliği %2$s bulunmamaktadır.
87 Classes (%1$s) tüm öznitelik %2$s bulunmamakta.
88 Class (%1$s) %2$s özniteliği bulunmamaktadır.
89 %1$s %2$s türü değil, bir nesne türüdür.
90 Seçici {%1$s} gerekli içerik (%2$s) bir maruz sınıf özelliklerine gidermez.
91 Seçici {%1$s} olmayan sınıf özellikleri (%2$s) ifade eder.
92 Seçici {%1$s} kendisini tanımlayan path ifade kök olamaz.
93 Seçici {%1$s} dairesel seçici {%2$s} açısından tanımlanır.
94 Seçici {%1$s} %2$s olarak yeniden tanımlandı.
95 %1$s (etki alanı nesnesi) özniteliği %2$s bulunmamaktadır.
96 özellikleri HARİÇ %1$s alt sınıfı değildir.
97 ALL ... EXCEPT Listede sınıfındaki EVERYTHING kapsamaz .
98 '%1$s' path seçici '%2$s' başka bir kullanımı ile veya path kök '%3$s' tutarsız.
99 Tanımsız argüman.
100 Argüman bir nesne değildir.
101 %1$s bir sınıf yöntemi veya %2$s özniteliği değildir.
102 Sorgu özellikleri bir içinde-yan tümcesi olmamalıdır.
103 Proxy dizayn edilmiş sorgu belirleme, hiçbir toplama ifadesi bulunmalıdır,\nhiçbir gurup-tarafından-yan tümcesi, ve herhangi bir sahipolan-yan tümcesi.
104 Proxy dizayn edilmiş sorgu belirleme DISTINCT veya UNIQUE olmaması gerekir \nSeçim listesinde anahtar kelime.
105 Proxy dizayn edilmiş sorgu belirleme basit bir SELECT anlatımı olmalıdır.
106 Proxy sorgu özellikleri tek bir tabloya veya sınıfa başvurması gerekir \nlokal veri tabanından.
107 User '%1$s' %2$s sahibi değil.
108 Proxy '%1$s' zaten sınıf '%2$s' üzerinde ldb '%3$s' tanımlanır.
109 CUBRID türdeş olmayan setleri nesneleri ile proxy desteklemiyor.
110 Nerede-yan tümcesi mantıksal bir tür anlatımı olması gerekir.
111 Çıkış yan tümcesi gibi bir değişmez dize ya da bir ana değişken olmalıdır.
112 Geçersiz hassas birleşimi (%1$d) ve ölçek (%2$d).
113 %1$d göz önüne alındığında kesinlik geçersiz;%2$d den daha büyük olmalı ve %3$d den daha büyük olmamalıdır.
114 Hassas (%1$d) çok büyük. Maksimum kesinlik %2$d.
115 %1$s yöntemi bir dönüş türüne sahip olmalıdır.
116 Metodu ile birlikte bağımsız sayısı yöntemi için tanımlanan \n sayısına eşit değildir.
117 Yöntem çağrısı bir hedefi olmalıdır.
118 %1$s yöntemi verilen hedef için tanımsızdır.
119 Örnek yöntemleri sınıf nesneleri olarak adlandırılan olamaz.
120 Sınıf yöntemler örnek nesneler üzerinde çağrılamaz.
121 Sınıf metotları, hedef olarak bir sınıf nesnesi gerektirir.
122 Yöntem, hedef olarak bir nesne gerektirir.
123 %1$s yöntemi tam olarak yazılmış değil, sınıf şeması yöntemi tanımını kontrol edin.
124 Zaman aritmetiği alttan taşma.
125 Tarih aritmetiği alttan taşma.
126 Bir atama yan tümcesi sol tarafta geçersiz.
127 Yöntem bir dış kapsamı ile bağlantılıdır ayarlanmış türetilen tablolar çağrısında dizi bir alt sorgu ile sarılmış olmadıkça \n desteklenmez.
128 Karşılık gelen dizayn edilmiş sorgu belirleme sütununda \n paylaşılan özniteliği '%1$s' NULL veya NA olmalıdır.
129 Öznitelik tanımı atlanırsa bir NULL sütun görünümünde sorgu şartname seçim listesi üzerinde izin verilmez.
130 Setlerle Vclass nesneleri desteklenir.
131 Bir dize değeri bekleniyor.
132 Bir deyim ya da bir dize değeri bekleniyor.
133 Proxy object_id özniteliği '%1$s' \na dizayn edilmiş sorgu belirleme sütununda ifade eşleştirilir olmamalıdır.
134 %1$s kısıtlama gözardı edildi.
135 Kısıt bildirimleri bu bağlamda izin verilmez.
136 %1$s yazmak için %2$s çevrim desteklenmemektedir.
137 %1$s geçerli bir bit dizgesi değil.
138 '%1$s' operatör tipi %2$s tanımlı değildir.
139 '%1$s' operatör %3$s ve %4$s ile türleri %2$s tanımlı değildir.
140 Operatör '%1$s' işlenenler hem Dinamik Ana Bilgisayar değişkeni olamaz.
141 '%1$s' genel işlevlerde çok fazla argüman bulunmakta.\nSadece %2$d argümanları genel işlevler için izin verilir.
142 Seçici {%1$s} class '%2$s' '%3$s' bir alt sınıf değildir.
143 Türü %2$s '%1$s' alanından ayıklayamazsınız.
144 Sorgu özellikleri ORDER BY yan tümcesine sahip olmamalıdır.
145 Olgu durumu mantıksal bir tür anlatımı olması gerekir.
146 İfade türü %1$s olmalıdır.
147 Serial '%1$s' zaten var.
148 Serial '%1$s' tanımlı değil.
149 Increment değeri sıfır olmamalıdır.
150 Maximum değeri 1.0e37 aşıyor.
151 Minimum değeri geçersiz.
152 Increment değeri geçersiz.
153 Minimum değer -1.0e36 aşıyor.
154 Maximum değeri geçersiz.
155 Belirtilen değiştirebilir seri seçeneğini.
156 serial_next_value fonksiyonunun ikinci kez tartışması 0 den büyük olmalıdır.
157 Serial değerleri minimum veya maksimum aşan olamaz.
158 Serial için Dahili I/O hatası
159 İndeks '%1$s' bulunamıyor.
160 Nitelikli dizin adı '%1$s' bir sınıf için başvuruyor, ancak bu yan tümcesi belirtilen değildir.
161 İki veya daha fazla sınıfların aynı indeksi '%1$s' var.Nitelikli dizin adlarını kullanabilirsiniz.
162 %1$s geçersiz kullanımı.\n%2$s anlatımı öznitelik veya ilişkili alt sorgu kullanilamaz.
163 Güncel sürüm seçim listesinde ORDERBY_NUM() içeren bir anlatımı kısıtlar.
164 Path anlatımı '%1$s' birleştirme koşulu.
165 '%1$s' birleştirme koşulu tanımlı değil.
166 Güncel sürümü sağ dış birleştirme için ayarlanmış türetilmiş bir tablo kısıtlar.
167 Diğer ldb üzerindeki sorgusu ile eklenemiyor.
168 Alt sorgu EXISTS ile sunulan olmadığında yalnızca tek bir sütunu seçim listesinde belirtilebilir.
169 Sağ tarafta bir atama yan tümcesi geçersiz .Sorgu bağlam tek sütun olmasını gerektirir.
170 Join koşulu yan tümcesinde bir alt sorgu kullanamazsınız.
171 Geçersiz bölüm tanımı.
172 Bölüm sütununda belirtilmelidir.
173 Sadece tek bir sütununda bölüm sütun olarak belirtilebilir.
174 Desteklenmeyen bölüm sütun türü.
175 Bölüm tanımı yineleniyor.'%1$s'
176 Sabit tür uyuşmazlığı. '%1$s'
177 Geçersiz bölüm boyutu.
178 '%1$s' sınıf bölümlenmiş değil.
179 '%1$s' zaten sınıf bölümlenmiş.
180 Geçersiz bölüm istekleri.
181 %1$s bu sınıfa (bölüm anahtar sütun) ile değiştirilemez.
182 %1$s aktif bir tetikleyiciler kapsamında bölüm -yönetilen olarak ayarlanamaz.
183 %1$s bölümü yok.
184 Bölüm türü uyumsuzlukları. '%1$s'
185 Bölüm bilgileri geçersiz.
186 Bölüm yanı sıra mevcut daha büyük bir aralığı ile ayarlanmaktadır.
187 Bu veri kaybına neden olabilir, çünkü bölümleri tekrar düzenlenmesine izin verilmez.
188 Bölüm '%1$s' aralığı geçersiz.
189 A sınıfı özellik bir otomatik artış kısıtlaması olamaz.
190 Sanal sınıf bir özniteliği otomatik artış kısıtlamasına sahip olamaz.
191 Özniteliği '%1$s' bir otomatik artış kısıtlamasına sahip olmasının süreli etki alanı geçersiz.
192 Bir kullanıcı olmayan ancak sistem özniteliği '%1$s' yabancı anahtarın 'ON CACHE OBJECT' tarafından oluşturulmuş atayabilirsiniz.
193 Dizin anahtarı'nı listesinde içinde yinelenen öznitelik adları kullanamazsınız. Öznitelik adı '%1$s' bir kereden fazla listelenmiştir.
194 Fonksiyon %1$s tanımsızdır veya parametresi yanlış numara verilmiştir.
195 '%1$s' yalnızca hiyerarşik bir sorguları kullanılabilmektedir. Yan tümcesi CONNECT BY belirleyin.
196 '%1$s' buradan izin verilmez.
197 Sorgu yan tümcesi CONNECT BY NOCYCLE yoksa sadece CONNECT_BY_ISCYCLEne kullanılabilmesine izin verilir.
198 Tabloların hiçbiri kullanılmamaktadır.
199 ORDER BY NULL, GROUP BY gerektirir.
200 CACHE için bir numaralı döngüsü (%1$s) daha az olmalıdır.
201 '%1$s' LIMIT anlatımı içeren bir sorgu içinde izin verilmez.
202 WITH ROLLUP, GROUP BY gerektirir.
203 Bir sütun adı parametresi DEFAULT işlevine aktarılan olmalıdır. Path ifadeleri henüz desteklenmemektedir.
204 '%1$s' tablosu seçeneği Duplicate
205 Sınıf '%1$s' REUSE_OID olarak işaretlenmiş ve olmayan-başvurulabilir konumundadır . Olmayan- başvurulabilir sınıfların bir öznitelik süreli etki alanı olamaz ve bunların örneklerini 'OID'lere geri iade edilemez.
206 'seri bağlantı %1$s' seçeneğini çoğaltın.
207 Sıralama yan tümcesinde sütununda '%1$s' belirsiz.
208 Öznitelik '%1$s' varsayılan bir değeri yoktur.
209 SELECT DISTINCT belirtilmişse öğelerin ORDER BY seçim listesinde görünmesi gerekir.
210 Ana değişken sorgu özelliklerindeki sütunların izin verilmemektedir.
211 %1$s sütununda ORDER BY olamaz
212 %1$s sütununda GROUP BY olamaz
213 Bir sütun türü olarak '%2$s'lik %1$s' tanımlayamazsınız.
214 İndeksin önek uzunluğu için geçersiz değer "%1$s".
215 '%1$s' fonksiyonu türleri %2$s, %3$s, %4$s ve %5$s tanımlı değildir.
216 '%1$s' fonksiyonu türleri %2$s, %3$s ve %4$s tanımlı değildir.
217 '%1$s' fonksiyonu türleri %2$s ve %3$s tanımlı değildir.
218 '%1$s' fonksiyonu türleri %2$s tanımlı değildir.
219 '%1$s' fonksiyon türü %2$s bir indeks bağımsız değişkeni için tanımlı değildir.
220 DEĞİŞTİRME GÖRÜNÜMÜ '%1$s' SEÇ gibi alt sınıflara veya süper sınıf vardır görünümleri için izin verilmez. Yerine DEĞİŞİM SORGU DEĞİŞTİRME GÖRÜNÜMÜ kullanabilirsiniz.
221 Görünüm öznitelikleri bu açıklamayı kullanarak değişiklik yapılamaz. 'sorgu gibi DEĞİŞTİRME GÖRÜNÜMÜ adı' yerine yardımcı olabilir.
222 CUBRID öğesi ORDER BY group_concat bağımsız değişken veya bir tamsayıdır (bağımsız değişken konumu) aynı ifade olmasını gerektirir.
223 LIKE doğrulama bir çıkış karakteri belirlenen gerektirir.'%1$s' için belgelere başvurun ve '%2$s' yapılandırma parametrelerine bakın.
224 KEYLIMIT, INDEX NONE olarak kullanilamaz
225 Oturum değişkenine bu çerçevede izin verilmez.
226 '%1$s' ve '%2$s' arasındaki dizin ipucu tatışması.
227 '%1$s' fonksiyonu DEFAULT cümle içine kullanmamalıdır
228 Ekstre formunun güncelenmesine izin verilmez
229 Düzeyin özellikleri ve örnek özelliklerinin aynı ifadesini güncelemesine izin vermez. 
230 Sanal hiyerarşini güncelemeye izin verilmez
231 Sunucu değişkenleri DDL deyimini izin verilmez.
232 İndeks geçersiz filtre ifadesi için (%1$s)
233 Çeşitlilik veya yuvalanmış işlemleri fonksiyon dizini tanımlarında izin verilmez.
234 Geçersiz dizin özellikleri
235 SHARED, DEFAULT and AUTO_INCREMENT -büyüme arası tanımlanamaz.
236 Çok fazla sayım değeri (%1$d). Sayım tipindeki kopyalama değeri (%2$d).
237 Sayım tipindeki kopyalama değeri
238 MERGE ayıklamak için kombine edilemez.
239 MERGE ifadesindeki kaynak formu etkilememelidir
240 MERGE taşıyankombineye izin verilmez.
241 Kullanıcı adı çok uzun
242 Uzun süreli ifade fonksiyon dizini olarak kullanılamaz. 
243 Düzey adı veya takma adı listede özgü değildir: '%1$s'
244 Geçersiz DEFAULT cümle. '%1$s' yuvalanmış ifadede kullanılamaz
245 '%1$s' Bir eşleme onaylı tartışma gerektirir
246 Geçersiz özellik grubu
247 Gereksinimlerde bulunan özellik grubu ile onay eşlemeli değildir
248 Bilinmeyen onay '%1$s'.
249 Bağlamı onaylanmış kod grubuna gerektirir ve kontrol edilen eleman grupları
250 Ön dizini '%1$s' üzerinde izin vermez (Temel üzerindeki tontrolu genişletmek)
251 Başlangıç değeri geçersiz
252 Çok fonksiyonlu kapasite dizinine izinvermez
253 '%1$s' fonksiyonu talimat temeli üzerindeki fonksiyon için kullanılamaz
254 Geçersiz dizin kapasitesinin tanımlanması: %1$s
255 Dizin filtre ifadesindeki '%1$s' izinverilmez.
256 Aynı sorunlar içinde GROUPBY_NUM() ve WITH ROLLUP cümleleri kullanamaz.
257 ON cümlelerinde bir referans rolü oynayan ve MERGE UPDATE kapasitesinin %1$s kombine edilemez.
258 Kapasite sayısı, %1$d, ( %2$s ) içi\n kapasite sayısı ile eşleşmez, %3$d, in ( %4$s ).
259 Kapasite öneki fonksiyon dizin ifadesinde izinvermez.
260 %1$s kapasite komutunun PARTITION BY or ORDER BY 
261 Şüphe mutlaka tek bir değer\n(%1$s) üzerinde olmamalıdır
262 Yuvalanmış analız fonksiyonlarına izin verilmez.
263 Miras alan özellik bölünme için kullanılmaz.
264 Sayım elemanının toplam büyüklüğü
265 Kaynak numunelerinde hedef formu kullanılmayacak
266 COLLATE bu içerikte izin verilmemiştir.
267 COLLATE değiştirici kod kümesini değiştiremiyor (from '%1$s' to '%2$s'). Yerine CAST kullanın.
268 Bölme değeri için geçersiz kod takımı '%1$s'. Beklenene kod takımı '%2$s'.
269 Oturum değişkeni sistem harmanlamasından farklı bir harmanlamaya sahip olamaz ('%1$s').
270 Geçersiz fonksiyon indeks ifadesi.
271 %1$s sorgulama spesifikasyonu kendisine dönüşlü bir referansa sahiptir.
272 %1$s ifadesi bağlanma koşulunda izin verilmemiştir. 
273 ORDER BY fonksiyon izin verilmez MEDIAN.
274 Fonksiyon argümanları '%1$s' sabit olmalıdır.
275 Fonksiyon '%1$s' ORDER BY yan tümcesi olmalıdır.
276 Fonksiyon '%1$s' için, argüman sayısı sayısı sütun sayısı ORDER BY ile eşleşmiyor.
277 Fonksiyon '%1$s', ORDER BY yan tümcesinde geçersiz.
278 Bir görünüm içinde sadece bir tablo güncellenebilir.
279 Birden çok eklemek hedefler izin verilmiyor.
280 '%1$s' türü vclass olduğunu, iptal etme vclass ile kaskad kısıtlamaları yasaktır.
281 The FOR UPDATE clause cannot be used in subqueries, unions, with GROUP BY clause, DISTINCT operator, aggregate functions.
282 %1$s argüman pozisyonu %2$d bekliyor.
283 Belirtilen çok fazla argüman.
284 Çok az argüman, %1$d argümanlara ihtiyaç.
285 Argüman %2$s %1$s bekliyor.
286 Argüman %1$s eksik olduğunu.
287 Bilinmeyen argüman %1$s.
288 Tüm bölümleri kaldırmaktan yerine DROP TABLE kullanmaktadır.
289 Ifadesine dahil %1$s bu bağlamda yasaktır.
290 Transaction id is not an integer.
291 Subquery is not allowed in ORDER BY FOR clause.

$set 9 MSGCAT_SET_PARSER_RUNTIME
1 Sanal bellek yetersiz: %1$d bayt bölüm ayıramadı.
2 İşlemin yalıtım düzeyi 1, 2, 3, 4, 5 veya 6 olması gerekir.
3 Zaman aşımı değeri -1, 0, veya >0 olması gerekir .
4 Yalıtım düzeyi olarak ayarlandığında:\n
5          Unknown isolation.\n
6          Unknown isolation.\n
7          Unknown isolation.\n
8          READ COMMITTED\n
9          REPEATABLE READ\n
10 Güncellenebilir-olmayan sorgusu db_query_execute_oid çağrısı izin verilmemektedir.
11 İşlem kilitleri beklerken zaman aşımına uğradı.
12 Sadece %2$d giriş ana bilgisayar değişkenleri verildiğinde indeks %1$d sahip ana bilgisayar değişkenine erişilmeye çalışıldı.
13 Dönüştürme gerçekleşmemiş.
14 Dahili hata, tanımsız dönüştürme.
15 '%1$s' yields uygun sonuç bulunamad.
16 '%1$s' yields bir satırdan daha fazla.
17 Yorumlayıcısı değişkeni %1$s tanımlanmış değildir.
18 '%1$s'Değerlendiremiyor.
19 Bilinmeyen değişken %1$s.
20 Bilinmeyen ortak öznitelik %1$s.
21 '%1$s' yields birden fazla sütun.
22 Toplama fonksiyonu yuvalanmış veya kullanımı geçersiz.
23 Fonksiyon %1$s tanımlanmış değildir.
24 Bağlamda tek sütun için sorgu gerektirmektedir \n(%1$s).
25 Değerler çok fazla belirtildi.
26 Sanal atama hedefi (%1$s) ters çevrilebilir değildir.
27 %1$s sınıfı içinde özniteliklerinde sorgu özelliklerinden daha fazla sütun vardır.
28 Sorgusu özelliklerinde sütunlar dan %1$s sınıfı daha fazla öznitelikleri vardır.
29 Mevcut sürümde vclasses için kümeleme kısıtlamaktadır OLMADAN\nToplama sorgusu özellikleri.
30 Mevcut sürümde vclasses için kümeleme kısıtlamaktadır OLMADAN\nBirlik sorgusu özellikleri.
31 Bir bileşimin hiyerarşisindeki vclass kullanılması (%1$s) güncellenebilen olmasını gerektirir.\nBu gerçek bir sınıf %2$s açısından güncelleştirilemez .
32 Kullanılmamıştır.
33 '%1$s' path ifade özelliğinde geçersiz yapı.
34 Path ifadesi '%1$s' vclass %3$s, %2$s db sınırını geçiyor.
35 Path ifadesi '%1$s' %3$s sınıfı için, %2$s db sınırını geçiyor.
36 %1$s %2$s üzerinde yetkili değil.
37 Select %1$s üzerinde yetkili değil.
38 Vclass %1$s güncelleştirilebilir değil.
39 %1$s bir proxy vclass değildir.
40 Proxy vclass sorgu spec bir birleştirme olmamalıdır.
41 %1$s nesne kimliği belirledi.
42 Bir bileşimde birden fazla object_id alanlarıyla sınıfları (%1$s) \n hiyerarşisi desteklenmez.
43 %2$s nesne özniteliği %1$s ldb %3$s üzerinde bir vclass değildir.
44 Sorgu özellikleri tür özniteliği %1$s ile uyumsuzdur.
45 %1$s sorgusu özellikleri kendisi için bir döngüsel başvuru var.
46 Hiçbir ifade değerlendirmek için verilmemiştir.
47 Gerçek bir sınıf olmayan vclass %1$s bulundu.
48 Yürütme '%1$s' ldb '%2$s' \n döndürdü: %3$s.
49 Özniteliği '%2$s' içine değeri '%1$s' koyarak döndü: %3$s.
50 Ldb adı %1$s içinde null olmamalıdır.
51 Ana bilgisayar da ldb ad %1$s null olmamalıdır.
53 Host adı %1$s içinde null olmamalıdır.
54 Kullanıcı adı %1$s içinde null olmamalıdır.
55 Kullanıcı şifresi %1$s içinde null olmamalıdır.
56 Boş açıklamaya çeviri yerleştirin.
57 Boş açıklamaya çeviri güncelleyin.
58 Delete translates to empty statement.
59 Ingres 1 Ocak 1582 öncesi tarihleri ​​(%1$s) desteklemiyor.
60 Kaynaklar sorgu üretiminde bitmiş.
61 Sorgu verimi sonuçsuz, böylece değişken '%1$s' ayarlı değil.
62 YEREL ile kontrol seçeneği desteklenmiyor.
63 Görünümünde %1$s seçeneği dışında kontrol edin.
64 Geçersiz tarih: '%1$s'.
65 Geçersiz zaman: '%1$s'.
66 Geçersiz U zaman: '%1$s'.
67 Bir proxy sorgu belirtiminde alt sorgular desteklenmez.
68 Ldb fonksiyonu bağımsız değişken '%1$s' ldb ile uyumlu değildir.
69 Geçersiz bir sayısal: '%1$s'.
70 Harici join sorgu iyileştirme başarısız oldu.
71         SERIALIZABLE.\n
72 Vclass %1$s güncelleştirilebilir değil. Sadece güncellenebilir vsınıflar VIDs seçmesine izin verilir.
73 Bölümleme başarısız oldu.
74 Bölme bulunmamaktadır.
75 Bölümünün erişim izni bulunmamaktadır: '%1$s'.
76 Seri '%1$s' henüz tanımlanmamış.
77 Sahibi veya DBA yalnızca hedef seri tanımını değiştirebilir.
78 Kullanıcılar otomatik artış kısıtlaması tarafından oluşturulan seri nesneyi değiştirmek için izin verilmez.
79 Geçersiz yalıtım düzeyi: %1$s şema, %2$s örnekleri.
80 Isolation level value in MVCC must be 'read committed', 'repeatable read' or 'serializable'.

$set 11 MSGCAT_SET_AUTHORIZATION
1 *** geçersiz önbellek ***
2    sınıf %1$s
3 %1$s dan :
4 Kullanıcı Yetkilendirme %1$s\n
5 Tanımsız kullanıcı için Yetkilendirme \n
6 Kullanıcı : %1$s\n
7            id : %1$d\n
8       üye :
9       gurup :
10 Kullanıcı %1$s\n
11 Mevcut kullanıcı : %1$s\n
12 Kök yetkilendirme nesnesi :\n
13   kullanıcılar :
14 *** Kullanıcı için tüm bağışları sorunu bulunamadı "%1$s"*** \n
15 YETKİLENDİRME\n
16 direct_groups :

$set 12 MSGCAT_SET_HELP
1 Köksınıf
2 %1$s %2$s\n
3 Süper sınıflar :\n
4 Alt sınıflar :\n
5 Öznitelikler : \n
6 Yöntemler : \n
7 Sınıf öznitelikleri : \n
8 Sınıf yöntemleri : \n
9 Çatışma çözünürlükleri :\n
10 Yöntem dosyası :\n
11 Sorgu özelleştirme :\n
12 %1$s Nesnesi \n
13 \nTanım :\n
14 \nYapı :\n
15 \nÖrnek :\n
16 META CLASS Adı
17 Sınıf Adı
18 VSınıf Adı
$  Don't delete the space at the end of the next message
19 ldb izerinde VSınıf
20 GENERAL

$set 13 MSGCAT_SET_TRIGGER
1 İŞARET: Tetik için durum değerlendirilmesi '%1$s'.
2 İŞARET: Tetik için eylem yürütme '%1$s'.

$set 14 MSGCAT_SET_LOCK
1 \n
2 Hat (indeks %1$3d) işlemin (indeks %2$3d, %3$s, %4$s@%5$s|%6$d) askıya alındı.\n
3 Hat (indeks %1$3d) işleminin (indeks %2$3d, %3$s, %4$s@%5$s|%6$d) devam edilmiştir.\n
4 İşlem endeksi %1$3d nesne %2$s kilit ACQUIRED %3$d|%4$d|%5$d.\n
5 İşlem endeksi %1$3d sayfa %2$s kilit ACQUIRED %3$d|%4$d.\n
6 İşlem endeksi %1$3d nesne %2$s kilit, kilit CONVERTED %3$d|%4$d|%5$d.\n
7 İşlem endeksi %1$3d sayfa %2$s kilit, kilit CONVERTED %3$d|%4$d.\n
8 İşlem endeksi %1$3d nesne %2$s kilit WAIT FOR %3$d|%4$d|%5$d.\n
9 İşlem endeksi %1$3d sayfa %2$s kilit WAIT FOR %3$d|%4$d.\n
10 İşlem endeksi %1$3d nesne %2$s kilit RELEASE %3$d|%4$d|%5$d.\n
11 İşlem endeksi %1$3d sayfa %2$s kilit RELEASE %3$d|%4$d.\n
12 İşlem endeksi %1$3d nesne %2$s kilit DEMOTE %3$d|%4$d|%5$d.\n
13 İşlem endeksi %1$3d sayfa %2$s kilit DEMOTE %3$d|%4$d.\n
14 OID = %1$2d|%2$6d|%3$4d\n
15 Nesne türü: Kök sınıf.\n
16 Nesne türü: Sınıf = %1$s.\n
17 Nesne türü: Sınıfın bir örneği (%1$2d|%2$6d|%3$4d) = %4$s.\n
18 Nesne türü: Bilinmeyen.\n
19 Tutucular Toplam modu = %1$8s, Bekleyenler Toplam modu = %2$8s.\n
20 Num holders=%1$3d, Num blocked-holders=%2$3d, Num waiters=%3$3d\n
21 LOCK HOLDERS:\n
22 BLOCKED LOCK HOLDERS:\n
23 LOCK WAITERS:\n
24 NON_2PL_RELEASED:\n
25 %1$4sTran_index = %2$3d, Granted_mode =%3$8s, Count = %4$3d\n
26 %1$4sTran_index = %2$3d, Granted_mode =%3$8s, Count = %4$3d, Nsubgranules = %5$2d\n
27 %1$4sTran_index = %2$3d, Granted_mode =%3$8s, Count = %4$3d\n\t%5$13s Blocked_mode = %6$8s\n\t%7$17s Start_waiting_at = %8$-30s\n\t%9$17s Wait_for_secs = %10$.2f\n
28 %1$4sTran_index = %2$3d, Granted_mode =%3$8s, Count = %4$3d, Nsubgranules = %5$2d\n\t%6$13s Blocked_mode =%7$8s\n\t%8$13s Start_waiting_at = %9$-30s\n\t%10$13s Wait_for_secs = %11$.2f\n
29 %1$4sTran_index = %2$3d, Blocked_mode =%3$8s \n\t%4$13s Start_waiting_at = %5$-30s \n\t%6$13s Wait_for_secs = %7$.2f\n
30 %1$4sTran_index = %2$3d, Non_2_phase_lock =%3$8s\n
31 VPID (volid|pageid) = %1$3d|%2$6d.\n
32 *** Tablo Dökümü Kilit ***\n Yükseltme Kilidi = %1$d, Kilitlenme aralığı çalıştırın = %2$5.2f\n
33 İşlem (indeks %1$2d, %2$s, %3$s@%4$s|%5$d)\n
34 Ayırma %1$s\n
35 Durum %1$s\n
36 Timeout_period %1$s\n
37 İndeksleri ile tek taraflı olarak iptal işlemleri:\n
38 %1$d ,
39 Timed_out endeksleri ile işlemler:\n
40 %1$d ,
41 Bir işlem ve bir işlevi seçeneğini belirleyerek kilitlenme çözülmesi \n çıkmazdan kurtarmak için: %1$d %2$s
42 , %1$d %2$s
43 Hedef türü: Düzeyinin dizin anahtar cümlesi  (%1$2d|%2$6d|%3$4d) = %4$s.\n
44 Dizin adı: %1$s\n

$set 15 MSGCAT_SET_IO
1 \n*************************************************************************\n
2 Yedekleme = %1$s ihtiyaç var. \n Bu bağlanmış olmalıdır/devam etmek için yüklendi.\n Yedekleme sonra devam etmek için Tip 1 bağlanmış / yüklenir.\n Çıkmak için 0 yazın.\n
3 \n\n*** YEDEKLEME BAŞLIĞI BİLGİLERİ ***\n\n
4 Yedekleme Magic dosya tanımlama gerçekleştirmesi %1$s,\n
5           Serbest Bırakma: %1$s\n\
                 Disk Sürüm: %2$g\n
6            Veritabanı Adı: %1$s\n\
        DB Oluşturma Zamanı: %2$s\
               Sayfa boyutu: %3$d\n
7        Yedekleme Seviyesi: %1$d (%2$s)\n\
                  Start_lsa: %3$lld|%4$d\n\
                   Last_lsa: %5$lld|%6$d\n
8          Yedekleme Zamanı: %1$s\
  Yedekleme Birimi Numarası: %2$d\n
9   Veritabanı Yoğunluk Adı: %1$s\n\
       Yoğunluk Tanımlayıcı: %2$d, Boyut: %3$lld bytes (%4$d Sayfalar)\n
10           Veritabanı Adı: %1$s\n\
               Yoğunluk Adı: %2$s\n\
                  Birim Adı: %3$d\n\
         Yedekleme Seviyesi: %4$d (%5$s)\n\
Aşağıdaki seçeneklerden birini girin:\n
11 Tür\n \
  -  %1$d çıkmak için.\n \
  -  %2$d yoğunluğa sonra devam etmek için bağlanmış / yüklenir (yeniden deneyin) \n \
  -  %3$d birimdeki dizin veya cihaz değiştirdikten sonra devam etmek için.\n
12 Yedekleme birimi için yeni bir dizin veya aygıt girin.\n
13 Giriş hatası,%1$d ve %2$d arasında bir değer seçin.\n
14 ** UYARI ** Yanlış yedek yoğunluğu bağlanmış.\n
15 Yedekleme yoğunluğu %1$s başka bir yedekleme seviyesinden olan\n   (Seviye: %2$d, beklenen %3$d).\n\n
16 Yedekleme yoğunluğu %1$s yanlış sayfa ya da magic bir kimliğe sahiptir.\n\n
17 Yedekleme yoğunluğu %1$s başka bir veritabanından\n  (Ad: %2$s, beklenen %3$s).\n\n
18 Yedekleme yoğunluğu %1$s sırası dışında\n  (Unit Num: %2$d, beklenen %3$d).\n\n
19 Yedekleme yoğunluğu %1$s timestamp uyumsuzluğu\n  (Timestamp: %2$s, beklenen %3$s).\n\n
20 Yedekleme yoğunluğu bilgi dosyası hatası, satır %1$d.\n
21 Yedekleme yoğunluğu Label: Level: %1$d, Unit: %2$d, Database %3$s, Backup Time: %4$s\n
22                    Önceki Yedekleme düzeyi: %1$d Zaman: %2$s (start_lsa was %3$lld|%4$d)\n
23 Aşağıdaki Veritabanı yedekleme yoğunluğu geri döndürmeye devam etmek gerekmektedir:\n\n
24 Yedekleme hedefi dolu, yeni bir hedefe devam etmek için gereklidir:
25 Yedekleme yoğunluğu adı öncesindeki: %1$s\n
26     Sonraki yedekleme yoğunluğu adı: %1$s\n
27              Yedekleme Sayfa boyutu: %1$d\n
28                         Zip Yöntemi: %1$d (%2$s)\n\
                          Zip Seviyesi: %3$d (%4$s)\n
29                     Aktif Log Dahil: %1$s\n

$set 16 MSGCAT_SET_LOG
1 \n*************************************************************************\n
2 Arşiv log %1$s \n normal yürütülmesine devam etmek için gereklidir.   \n \
  Tür\n \
  -  0 çıkmak için.\n \
  -  1 mevcut arşiv olmadan devam etmek için. (Kısmi kurtarma)\n \
  -  2 arşivi sonra devam etmek için bağlanmış / yüklenir.       \n \
  -  3 konumu / arşivi adını değiştirildikten sonra devam etmek için.   \n
3 Yedekleme bilgi dosyası %1$s \n geri yükleme işlemine devam etmek gereklidir.\n \
  Tür\n \
  -  0 çıkmak için.\n \
  -  1 dosya bağlanmış / yüklendikten sonra devam etmek için.      \n \
  -  2 konumu / dosya adını değiştirildikten sonra devam etmek için.  \n
4 Enter yeni konum / adı.\n
5 YORUM: %2$s veritabanı için %1$s\n
6 YORUM: Bir veritabanı ortamı kilitlenme gerçekleşmediği sürece arşiv %1$s log artık gerekli değildir.\n
7 YORUM: Bir veritabanı ortamı kilitlenme oluşmadığı takdirde %1$s den %2$s log arşivleri artık gerekli değildir.\n
8 YORUM: yeniden adlandırılan veritabanından = %1$s\n
9 ARŞİV: %1$d %2$s %3$lld %4$lld\n
10 ARŞİV:
11 KALDIR: %1$d %2$s to \n \
       %3$d %4$s.\n \
       SEBEP: %5$s\n
12 AKTİF: %1$s %2$d sayfalar\n
13  Tranid = %2$d tran_index %1$d işlemeyi bitirin, Sadece LSA = %3$lld|%4$d öncesinde ve %5$s
14  Tranid = %2$d tran_index %1$d iptali bitirin, Sadece LSA = %3$lld|%4$d öncesinde ve %5$s
15  Eksik Ortam Kurtarma etkilidir.Veri tabanı Tamamlanmamış olacaktır\n \
 %1$lld|%2$d LSA noktası adresine kadar iyileşmiş. Son işleme / iptal \n \
 nokta süresi yaklaşık olarak %3$s konumundadır\n \
 veritabanında işlenen işlemlerin tüm bilgileri kaybetmiştir\n \
 bu zaman sonunda.\n
16 Tamamlanmamış kurtarma nedeniyle log sıfırlayın.
17 Veritabanı yedeklemesi alındı.
18 Ortam kilitlenme uygulaması için önemli değildir.
19 İçinde daha önceki bir yedeğe varmış gibi görünüyor dizini %1$s yedekleme. \n\
Bu yerde bu veritabanınızın kullanılmayan yedekleme yoğunlukları silinecektir,\n\
geçerli yedeğe düzeyi yüksek ve de dahil olmak üzere.\n
20 Devam etmek için 'y' veya iptal etmek için herhangi bir diğer tuşa basın.\n
21 Veritabanı yedeklemesi kullanıcı tarafından iptal edildi.\n
22 DELETE POSTPONED: Archives %1$d %2$s to\n \
        %3$d %4$s \n \
        are no longer needed unless a restore from current backup occurs.\n
23 Daha yeni bir yedeğini daha önceden DELETE POSTPONED işaretli arşivlerinde yayımladı.\n
24 YORUM: Log arşivi %1$s artık daha güncel bağlı DELETE POSTPONED değil\n \
   bir veritabanı ortamı kilitlenme gerçekleşmediği sürece bu yüzden yedekleme gerekli değildir.\n
25 YORUM: %1$s %2$s arşivlerinde Log bağlı artık DELETE POSTPONED değil\n \
   daha güncel yedeğini ve bu nedenle bir veritabanında ortam olmadıkça gerekli değildir\n \
   kilitlenme oluşuyor.\n
26 Bir veritabanına geri yükleme işlemi sırasında bir hata oluştu, \n\
     Yedekleme yoğunluğu: %1$s\n\
          Birim Numarası: %2$d\n\
    Veritabanı Yoğunluğu: %3$s\n\
  Veritabanı Yoğunluk id: %4$d\n\
** Uyarı: Bir hatasız geri yükleme elde edilinceye kadar veritabanı kullanmayın.\n
27 Girişte Hata, %1$d ve %2$d arasında bir değer seçin.\n
28 Belirtilen zaman (%1$s) Belirtilen yedekleme süresi (%2$s) dan sonra olmalıdır.\n
29 YORUM: Log arşivi %1$s yapın, önce %2$lld Log sayfaları içeren, herhangi HA programları tarafından artık gerekli değildir.\n
30 Aktif log arşivlerinde sayısı maksimum istenen sayısı aşıldı.
