#!/bin/sh

echo "processing nbd1"
csql -u nbd -p nbd -S nbd1 -c "RENAME CLASS NBD_COMMENT AS NBD_COMMENT2; \
CREATE TABLE NBD_COMMENT ( BOARD_ID INTEGER, ARTICLE_ID NUMERIC(20,0), COMMENT_NO INTEGER, COMMENT_TEXT VARCHAR(500), COMMENT_STATUS VARCHAR(10) NOT NULL, WRITER_ID VARCHAR(20) NOT NULL, WRITER_NICKNAME VARCHAR(50) NOT NULL, WRITER_INFO VARCHAR(200), POSTED_TIME TIMESTAMP NOT NULL, RECOMMENDED_COUNTER INTEGER NOT NULL, EXTRA_1 VARCHAR(10), EXTRA_2 VARCHAR(10), EXTRA_3 VARCHAR(10), EXTRA_4 VARCHAR(10)); \
ALTER TABLE NBD_COMMENT ADD PRIMARY KEY(ARTICLE_ID, COMMENT_NO); \
INSERT INTO NBD_COMMENT SELECT * FROM NBD_COMMENT2; \
CREATE INDEX ON NBD_COMMENT(ARTICLE_ID, POSTED_TIME DESC); \
ALTER TABLE NBD_COMMENT ADD COLUMN NEW_COL VARCHAR(100);"

echo "processing nbd2"
csql -u nbd -p nbd -S nbd2 -c "RENAME CLASS NBD_COMMENT AS NBD_COMMENT2; \
CREATE TABLE NBD_COMMENT ( BOARD_ID INTEGER, ARTICLE_ID NUMERIC(20,0), COMMENT_NO INTEGER, COMMENT_TEXT VARCHAR(500), COMMENT_STATUS VARCHAR(10) NOT NULL, WRITER_ID VARCHAR(20) NOT NULL, WRITER_NICKNAME VARCHAR(50) NOT NULL, WRITER_INFO VARCHAR(200), POSTED_TIME TIMESTAMP NOT NULL, RECOMMENDED_COUNTER INTEGER NOT NULL, EXTRA_1 VARCHAR(10), EXTRA_2 VARCHAR(10), EXTRA_3 VARCHAR(10), EXTRA_4 VARCHAR(10)); \
ALTER TABLE NBD_COMMENT ADD PRIMARY KEY(ARTICLE_ID, COMMENT_NO); \
INSERT INTO NBD_COMMENT SELECT * FROM NBD_COMMENT2; \
CREATE INDEX ON NBD_COMMENT(ARTICLE_ID, POSTED_TIME DESC); \
ALTER TABLE NBD_COMMENT ADD COLUMN NEW_COL VARCHAR(100);"

