/*
 * Copyright (C) 2008 NHN Corporation
 * Copyright (C) 2008 CUBRID Co., Ltd.
 *
 * pcadmin.h - Constants for the messages in pcadmin.msg.
 */

#ifndef _PCADMIN_H
#define _PCADMIN_H

#ident "$Id$"

#define PCMSG_CATALOG_NAME "pcadmin.msg"

/* sets */
#define MSGSET_PC_ADMIN 1
#define MSGSET_PC_USQLX 2

/* general */
#define PCMSG_NO_CUBRID  1

/* keyadd.c */
#define PCMSG_WRITE_ACCESS 2
#define PCMSG_HOSTID_PROMPT 3
#define PCMSG_HOSTKEY_PROMPT 4
#define PCMSG_HOSTID_LENGTH 5
#define PCMSG_HOSTID_HEX 6
#define PCMSG_HOSTKEY_INVALID 7
#define PCMSG_HOSTKEY_INCONSISTENT 8
#define PCMSG_HOSTKEY_TIMEOUT 9
#define PCMSG_HOSTID_UNKNOWN 10
#define PCMSG_HOSTID_INFO 11
#define PCMSG_KEYADD_FAILURE 12	/*
				 * $Revision: 1.3 $
				 *
				 *
				 */

#define PCMSG_KEYADD_SUCCESSFUL 13
#define PCMSG_HOSTID_IP_PROMPT 14
#define PCMSG_INVALID_IP_ADDRESS 15
#define PCMSG_INVALID_IP_NUMBER 16

/* file.c, also used in some other places */
#define PCMSG_OUTPUT_FILE_ERROR 17
#define PCMSG_INPUT_FILE_ERROR 18
#define PCMSG_LENGTH_FILE_ERROR 19
#define PCMSG_READ_FILE_ERROR 20
#define PCMSG_WRITE_FILE_ERROR 21
#define PCMSG_LENGTH_FILE_INFO 22
#define PCMSG_WRITING_FILE_INFO 23
#define PCMSG_MERGE_OVERFLOW 24
#define PCMSG_CREATE_DIR_INFO 25
#define PCMSG_CREATE_DIR_ERROR 26
#define PCMSG_ASKDISK_PROMPT 27
#define PCMSG_ASKDISK_OK 28

/* inifile.c */
#define PCMSG_MEMORY 29
#define PCMSG_TEMP_FILE_ERROR 30
#define PCMSG_SECTION_NOT_FOUND 31
#define PCMSG_SECTION_NOT_UPDATED 32
#define PCMSG_SECTION_KEYWORD 33

/* odbcfile.c */
#define PCMSG_WINDOWS_DIR_PROMPT 52
#define PCMSG_ODBCINST_MISSING 53
#define PCMSG_ODBCINST_ERROR 54
#define PCMSG_ODBC_ERROR 55
#define PCMSG_BACKUP_FILE_ERROR 56
#define PCMSG_ODBC_ENTRY_ADD_ERROR 57
#define PCMSG_ODBC_ENTRY_ADD_ERROR2 58
#define PCMSG_ODBC_SECTION_ADD_ERROR 59
#define PCMSG_ODBC_SECTION_ADD_ERROR2 60
#define PCMSG_ODBCINST_SUCCESS 61
#define PCMSG_ODBCINST_SAVE 62
#define PCMSG_NO_DATA_SOURCE 63
#define PCMSG_CUBRID_DATA_SOURCES 64
#define PCMSG_NO_ODBC_ENTRY 65
#define PCMSG_DATA_SOURCE_PROMPT 66
#define PCMSG_SERVER_ADDRESS_PROMPT 67
#define PCMSG_DATA_SOURCE_ADDED 68
#define PCMSG_ODBC_SAVE 69
#define PCMSG_DATA_SOURCE_DELETED 70

/* prompt.c */
#define PCMSG_DEFAULT 71

/* uniadmin.c */
#define PCMSG_CMD_LIST    72
#define PCMSG_CMD_ADD     73
#define PCMSG_CMD_DELETE  74
#define PCMSG_CMD_INSTALL 75
#define PCMSG_CMD_HOSTID  76
#define PCMSG_CMD_KEYADD  77
#define PCMSG_CMD_HELP    78
#define PCMSG_CMD_TEST    79
#define PCMSG_CMD_QUIT    80

#define PCMSG_INVALID_COMMAND_ARGS 81
#define PCMSG_COMMAND_PROMPT 82
#define PCMSG_UNKNOWN_COMMAND 83
#define PCMSG_ADMIN_HERALD 84

/* new messages for the connection tester */
#define PCMSG_WINSOCK_STARTUP 85
#define PCMSG_WINSOCK_HOSTNAME 86
#define PCMSG_WINSOCK_HOSTID 87
#define PCMSG_WINSOCK_PROBLEM 88
#define PCMSG_CONNECTION_SUCCESS 89
#define PCMSG_CONNECTION_FAILURE 90

/* USQLX MESSAGES */

#define USQLX_INVALID_NUMERIC_VARIABLE_VALUE 1
#define USQLX_INVALID_VARIABLE_NAME 2
#define USQLX_ALIASES_HEADER 3
#define USQLX_LOCAL_ALLOCATIONS_HEADER 4
#define USQLX_HANDLE_ERROR 5
#define USQLX_GLOBAL_ALLOCATIONS_HEADER 6
#define USQLX_YES_ANSWER 7
#define USQLX_STATISTICS_INFO 8
#define USQLX_ALLOC_DUMP_QUESTION 9
#define USQLX_SQLX_RETURNED_ERROR 10
#define USQLX_LOG_FILE_OPEN_ERROR 11
#define USQLX_LOG_HEADER 12
#define USQLX_LOG_MSG_ERROR 13
#define USQLX_CREATE_DIRECTORY_QUESTION 14
#define USQLX_CREATE_DIRECTORY_ERROR 15
#define USQLX_CREATE_DIRECTORY_SUCCESS 16
#define USQLX_FILE_ACCESS_ERROR 17
#define USQLX_EMPTY_FILE 18
#define USQLX_MISSING_VARIABLE 19
#define USQLX_MISSING_TEST 20
#define USQLX_TEST_FAILS 21
#define USQLX_BATCH_FILE_OPEN_ERROR 22
#define USQLX_UNKNOWN_TEST 23
#define USQLX_UNKNOWN_COMMAND 24
#define USQLX_NO_COMMAND_INFO 25
#define USQLX_COMMAND_INFO_HEADER 26
#define USQLX_LOADING_INIT_FILE 27
#define USQLX_ODBC_TEST_START 28
#define USQLX_ODBC_TEST_PASS 29
#define USQLX_ODBC_TEST_FAIL 30
#define USQLX_COMMAND_LOOP_HERALD 31

#endif /* _PCADMIN_H_ */
