/*
 * Copyright (C) 2008 Search Solution Corporation. All rights reserved by Search Solution.
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 *
 */

/*
 * tz_list.h : List of supported timezones and their IDs.
 *	       Timezones and countries, together with their associated IDs are
 *	       generated based on IANA's timezone database.
 * WARNING: The timezones and countries below are generated using the gen_tz
 *	    CUBRID tool, with respect to previous CUBRID versions of the
 *	    timezone data. The timezone data and associated IDs are very
 *	    sensitive, because IDs are used in CUBRID to identify a timezone.
 *	    The data below should NOT BE CHANGED MANUALLY, only replaced with
 *	    newer generated data, which prevents conflicts between timezones
 *	    or countries with the same IDs, same country or timezone with IDs
 *	    accidentally changed, or timezones/countries which may be removed.
 */

#ifndef _TZ_LIST_H_
#define _TZ_LIST_H_

#include "timezone_lib_common.h"

/* WARNING: Generated data! Do not edit! */
static const char *tz_timezone_names[] = {
  "Africa/Abidjan",
  "Africa/Accra",
  "Africa/Addis_Ababa",
  "Africa/Algiers",
  "Africa/Asmara",
  "Africa/Bamako",
  "Africa/Bangui",
  "Africa/Banjul",
  "Africa/Bissau",
  "Africa/Blantyre",
  "Africa/Brazzaville",
  "Africa/Bujumbura",
  "Africa/Cairo",
  "Africa/Casablanca",
  "Africa/Ceuta",
  "Africa/Conakry",
  "Africa/Dakar",
  "Africa/Dar_es_Salaam",
  "Africa/Djibouti",
  "Africa/Douala",
  "Africa/El_Aaiun",
  "Africa/Freetown",
  "Africa/Gaborone",
  "Africa/Harare",
  "Africa/Johannesburg",
  "Africa/Juba",
  "Africa/Kampala",
  "Africa/Khartoum",
  "Africa/Kigali",
  "Africa/Kinshasa",
  "Africa/Lagos",
  "Africa/Libreville",
  "Africa/Lome",
  "Africa/Luanda",
  "Africa/Lubumbashi",
  "Africa/Lusaka",
  "Africa/Malabo",
  "Africa/Maputo",
  "Africa/Maseru",
  "Africa/Mbabane",
  "Africa/Mogadishu",
  "Africa/Monrovia",
  "Africa/Nairobi",
  "Africa/Ndjamena",
  "Africa/Niamey",
  "Africa/Nouakchott",
  "Africa/Ouagadougou",
  "Africa/Porto-Novo",
  "Africa/Sao_Tome",
  "Africa/Tripoli",
  "Africa/Tunis",
  "Africa/Windhoek",
  "America/Adak",
  "America/Anchorage",
  "America/Anguilla",
  "America/Antigua",
  "America/Araguaina",
  "America/Argentina/Buenos_Aires",
  "America/Argentina/Catamarca",
  "America/Argentina/Cordoba",
  "America/Argentina/Jujuy",
  "America/Argentina/La_Rioja",
  "America/Argentina/Mendoza",
  "America/Argentina/Rio_Gallegos",
  "America/Argentina/Salta",
  "America/Argentina/San_Juan",
  "America/Argentina/San_Luis",
  "America/Argentina/Tucuman",
  "America/Argentina/Ushuaia",
  "America/Aruba",
  "America/Asuncion",
  "America/Atikokan",
  "America/Bahia",
  "America/Bahia_Banderas",
  "America/Barbados",
  "America/Belem",
  "America/Belize",
  "America/Blanc-Sablon",
  "America/Boa_Vista",
  "America/Bogota",
  "America/Boise",
  "America/Cambridge_Bay",
  "America/Campo_Grande",
  "America/Cancun",
  "America/Caracas",
  "America/Cayenne",
  "America/Cayman",
  "America/Chicago",
  "America/Chihuahua",
  "America/Costa_Rica",
  "America/Creston",
  "America/Cuiaba",
  "America/Curacao",
  "America/Danmarkshavn",
  "America/Dawson",
  "America/Dawson_Creek",
  "America/Denver",
  "America/Detroit",
  "America/Dominica",
  "America/Edmonton",
  "America/Eirunepe",
  "America/El_Salvador",
  "America/Fortaleza",
  "America/Glace_Bay",
  "America/Godthab",
  "America/Goose_Bay",
  "America/Grand_Turk",
  "America/Grenada",
  "America/Guadeloupe",
  "America/Guatemala",
  "America/Guayaquil",
  "America/Guyana",
  "America/Halifax",
  "America/Havana",
  "America/Hermosillo",
  "America/Indiana/Indianapolis",
  "America/Indiana/Knox",
  "America/Indiana/Marengo",
  "America/Indiana/Petersburg",
  "America/Indiana/Tell_City",
  "America/Indiana/Vevay",
  "America/Indiana/Vincennes",
  "America/Indiana/Winamac",
  "America/Inuvik",
  "America/Iqaluit",
  "America/Jamaica",
  "America/Juneau",
  "America/Kentucky/Louisville",
  "America/Kentucky/Monticello",
  "America/Kralendijk",
  "America/La_Paz",
  "America/Lima",
  "America/Los_Angeles",
  "America/Lower_Princes",
  "America/Maceio",
  "America/Managua",
  "America/Manaus",
  "America/Marigot",
  "America/Martinique",
  "America/Matamoros",
  "America/Mazatlan",
  "America/Menominee",
  "America/Merida",
  "America/Metlakatla",
  "America/Mexico_City",
  "America/Miquelon",
  "America/Moncton",
  "America/Monterrey",
  "America/Montevideo",
  "America/Montreal",
  "America/Montserrat",
  "America/Nassau",
  "America/New_York",
  "America/Nipigon",
  "America/Nome",
  "America/Noronha",
  "America/North_Dakota/Beulah",
  "America/North_Dakota/Center",
  "America/North_Dakota/New_Salem",
  "America/Ojinaga",
  "America/Panama",
  "America/Pangnirtung",
  "America/Paramaribo",
  "America/Phoenix",
  "America/Port-au-Prince",
  "America/Port_of_Spain",
  "America/Porto_Velho",
  "America/Puerto_Rico",
  "America/Rainy_River",
  "America/Rankin_Inlet",
  "America/Recife",
  "America/Regina",
  "America/Resolute",
  "America/Rio_Branco",
  "America/Santa_Isabel",
  "America/Santarem",
  "America/Santiago",
  "America/Santo_Domingo",
  "America/Sao_Paulo",
  "America/Scoresbysund",
  "America/Shiprock",
  "America/Sitka",
  "America/St_Barthelemy",
  "America/St_Johns",
  "America/St_Kitts",
  "America/St_Lucia",
  "America/St_Thomas",
  "America/St_Vincent",
  "America/Swift_Current",
  "America/Tegucigalpa",
  "America/Thule",
  "America/Thunder_Bay",
  "America/Tijuana",
  "America/Toronto",
  "America/Tortola",
  "America/Vancouver",
  "America/Whitehorse",
  "America/Winnipeg",
  "America/Yakutat",
  "America/Yellowknife",
  "Antarctica/Casey",
  "Antarctica/Davis",
  "Antarctica/DumontDUrville",
  "Antarctica/Macquarie",
  "Antarctica/Mawson",
  "Antarctica/McMurdo",
  "Antarctica/Palmer",
  "Antarctica/Rothera",
  "Antarctica/South_Pole",
  "Antarctica/Syowa",
  "Antarctica/Vostok",
  "Arctic/Longyearbyen",
  "Asia/Aden",
  "Asia/Almaty",
  "Asia/Amman",
  "Asia/Anadyr",
  "Asia/Aqtau",
  "Asia/Aqtobe",
  "Asia/Ashgabat",
  "Asia/Baghdad",
  "Asia/Bahrain",
  "Asia/Baku",
  "Asia/Bangkok",
  "Asia/Beirut",
  "Asia/Bishkek",
  "Asia/Brunei",
  "Asia/Choibalsan",
  "Asia/Chongqing",
  "Asia/Colombo",
  "Asia/Damascus",
  "Asia/Dhaka",
  "Asia/Dili",
  "Asia/Dubai",
  "Asia/Dushanbe",
  "Asia/Gaza",
  "Asia/Harbin",
  "Asia/Hebron",
  "Asia/Ho_Chi_Minh",
  "Asia/Hong_Kong",
  "Asia/Hovd",
  "Asia/Irkutsk",
  "Asia/Jakarta",
  "Asia/Jayapura",
  "Asia/Jerusalem",
  "Asia/Kabul",
  "Asia/Kamchatka",
  "Asia/Karachi",
  "Asia/Kashgar",
  "Asia/Kathmandu",
  "Asia/Khandyga",
  "Asia/Kolkata",
  "Asia/Krasnoyarsk",
  "Asia/Kuala_Lumpur",
  "Asia/Kuching",
  "Asia/Kuwait",
  "Asia/Macau",
  "Asia/Magadan",
  "Asia/Makassar",
  "Asia/Manila",
  "Asia/Muscat",
  "Asia/Nicosia",
  "Asia/Novokuznetsk",
  "Asia/Novosibirsk",
  "Asia/Omsk",
  "Asia/Oral",
  "Asia/Phnom_Penh",
  "Asia/Pontianak",
  "Asia/Pyongyang",
  "Asia/Qatar",
  "Asia/Qyzylorda",
  "Asia/Rangoon",
  "Asia/Riyadh",
  "Asia/Sakhalin",
  "Asia/Samarkand",
  "Asia/Seoul",
  "Asia/Shanghai",
  "Asia/Singapore",
  "Asia/Taipei",
  "Asia/Tashkent",
  "Asia/Tbilisi",
  "Asia/Tehran",
  "Asia/Thimphu",
  "Asia/Tokyo",
  "Asia/Ulaanbaatar",
  "Asia/Urumqi",
  "Asia/Ust-Nera",
  "Asia/Vientiane",
  "Asia/Vladivostok",
  "Asia/Yakutsk",
  "Asia/Yekaterinburg",
  "Asia/Yerevan",
  "Atlantic/Azores",
  "Atlantic/Bermuda",
  "Atlantic/Canary",
  "Atlantic/Cape_Verde",
  "Atlantic/Faroe",
  "Atlantic/Madeira",
  "Atlantic/Reykjavik",
  "Atlantic/South_Georgia",
  "Atlantic/St_Helena",
  "Atlantic/Stanley",
  "Australia/Adelaide",
  "Australia/Brisbane",
  "Australia/Broken_Hill",
  "Australia/Currie",
  "Australia/Darwin",
  "Australia/Eucla",
  "Australia/Hobart",
  "Australia/Lindeman",
  "Australia/Lord_Howe",
  "Australia/Melbourne",
  "Australia/Perth",
  "Australia/Sydney",
  "CET",
  "CST6CDT",
  "EET",
  "EST",
  "EST5EDT",
  "Etc/GMT",
  "Etc/GMT+1",
  "Etc/GMT+10",
  "Etc/GMT+11",
  "Etc/GMT+12",
  "Etc/GMT+2",
  "Etc/GMT+3",
  "Etc/GMT+4",
  "Etc/GMT+5",
  "Etc/GMT+6",
  "Etc/GMT+7",
  "Etc/GMT+8",
  "Etc/GMT+9",
  "Etc/GMT-1",
  "Etc/GMT-10",
  "Etc/GMT-11",
  "Etc/GMT-12",
  "Etc/GMT-13",
  "Etc/GMT-14",
  "Etc/GMT-2",
  "Etc/GMT-3",
  "Etc/GMT-4",
  "Etc/GMT-5",
  "Etc/GMT-6",
  "Etc/GMT-7",
  "Etc/GMT-8",
  "Etc/GMT-9",
  "Etc/UCT",
  "Etc/UTC",
  "Europe/Amsterdam",
  "Europe/Andorra",
  "Europe/Athens",
  "Europe/Belgrade",
  "Europe/Berlin",
  "Europe/Bratislava",
  "Europe/Brussels",
  "Europe/Bucharest",
  "Europe/Budapest",
  "Europe/Busingen",
  "Europe/Chisinau",
  "Europe/Copenhagen",
  "Europe/Dublin",
  "Europe/Gibraltar",
  "Europe/Guernsey",
  "Europe/Helsinki",
  "Europe/Isle_of_Man",
  "Europe/Istanbul",
  "Europe/Jersey",
  "Europe/Kaliningrad",
  "Europe/Kiev",
  "Europe/Lisbon",
  "Europe/Ljubljana",
  "Europe/London",
  "Europe/Luxembourg",
  "Europe/Madrid",
  "Europe/Malta",
  "Europe/Mariehamn",
  "Europe/Minsk",
  "Europe/Monaco",
  "Europe/Moscow",
  "Europe/Oslo",
  "Europe/Paris",
  "Europe/Podgorica",
  "Europe/Prague",
  "Europe/Riga",
  "Europe/Rome",
  "Europe/Samara",
  "Europe/San_Marino",
  "Europe/Sarajevo",
  "Europe/Simferopol",
  "Europe/Skopje",
  "Europe/Sofia",
  "Europe/Stockholm",
  "Europe/Tallinn",
  "Europe/Tirane",
  "Europe/Uzhgorod",
  "Europe/Vaduz",
  "Europe/Vatican",
  "Europe/Vienna",
  "Europe/Vilnius",
  "Europe/Volgograd",
  "Europe/Warsaw",
  "Europe/Zagreb",
  "Europe/Zaporozhye",
  "Europe/Zurich",
  "HST",
  "Indian/Antananarivo",
  "Indian/Chagos",
  "Indian/Christmas",
  "Indian/Cocos",
  "Indian/Comoro",
  "Indian/Kerguelen",
  "Indian/Mahe",
  "Indian/Maldives",
  "Indian/Mauritius",
  "Indian/Mayotte",
  "Indian/Reunion",
  "MET",
  "MST",
  "MST7MDT",
  "PST8PDT",
  "Pacific/Apia",
  "Pacific/Auckland",
  "Pacific/Chatham",
  "Pacific/Chuuk",
  "Pacific/Easter",
  "Pacific/Efate",
  "Pacific/Enderbury",
  "Pacific/Fakaofo",
  "Pacific/Fiji",
  "Pacific/Funafuti",
  "Pacific/Galapagos",
  "Pacific/Gambier",
  "Pacific/Guadalcanal",
  "Pacific/Guam",
  "Pacific/Honolulu",
  "Pacific/Johnston",
  "Pacific/Kiritimati",
  "Pacific/Kosrae",
  "Pacific/Kwajalein",
  "Pacific/Majuro",
  "Pacific/Marquesas",
  "Pacific/Midway",
  "Pacific/Nauru",
  "Pacific/Niue",
  "Pacific/Norfolk",
  "Pacific/Noumea",
  "Pacific/Pago_Pago",
  "Pacific/Palau",
  "Pacific/Pitcairn",
  "Pacific/Pohnpei",
  "Pacific/Port_Moresby",
  "Pacific/Rarotonga",
  "Pacific/Saipan",
  "Pacific/Tahiti",
  "Pacific/Tarawa",
  "Pacific/Tongatapu",
  "Pacific/Wake",
  "Pacific/Wallis",
  "WET"
};

static const TZ_COUNTRY tz_countries[] = {
  {"AX", "Aaland Islands"},
  {"AF", "Afghanistan"},
  {"AL", "Albania"},
  {"DZ", "Algeria"},
  {"AD", "Andorra"},
  {"AO", "Angola"},
  {"AI", "Anguilla"},
  {"AQ", "Antarctica"},
  {"AG", "Antigua & Barbuda"},
  {"AR", "Argentina"},
  {"AM", "Armenia"},
  {"AW", "Aruba"},
  {"AU", "Australia"},
  {"AT", "Austria"},
  {"AZ", "Azerbaijan"},
  {"BS", "Bahamas"},
  {"BH", "Bahrain"},
  {"BD", "Bangladesh"},
  {"BB", "Barbados"},
  {"BY", "Belarus"},
  {"BE", "Belgium"},
  {"BZ", "Belize"},
  {"BJ", "Benin"},
  {"BM", "Bermuda"},
  {"BT", "Bhutan"},
  {"BO", "Bolivia"},
  {"BQ", "Bonaire Sint Eustatius & Saba"},
  {"BA", "Bosnia & Herzegovina"},
  {"BW", "Botswana"},
  {"BV", "Bouvet Island"},
  {"BR", "Brazil"},
  {"GB", "Britain (UK)"},
  {"IO", "British Indian Ocean Territory"},
  {"BN", "Brunei"},
  {"BG", "Bulgaria"},
  {"BF", "Burkina Faso"},
  {"BI", "Burundi"},
  {"KH", "Cambodia"},
  {"CM", "Cameroon"},
  {"CA", "Canada"},
  {"CV", "Cape Verde"},
  {"KY", "Cayman Islands"},
  {"CF", "Central African Rep."},
  {"TD", "Chad"},
  {"CL", "Chile"},
  {"CN", "China"},
  {"CX", "Christmas Island"},
  {"CC", "Cocos (Keeling) Islands"},
  {"CO", "Colombia"},
  {"KM", "Comoros"},
  {"CD", "Congo (Dem. Rep.)"},
  {"CG", "Congo (Rep.)"},
  {"CK", "Cook Islands"},
  {"CR", "Costa Rica"},
  {"CI", "Cote d'Ivoire"},
  {"HR", "Croatia"},
  {"CU", "Cuba"},
  {"CW", "Curacao"},
  {"CY", "Cyprus"},
  {"CZ", "Czech Republic"},
  {"DK", "Denmark"},
  {"DJ", "Djibouti"},
  {"DM", "Dominica"},
  {"DO", "Dominican Republic"},
  {"TL", "East Timor"},
  {"EC", "Ecuador"},
  {"EG", "Egypt"},
  {"SV", "El Salvador"},
  {"GQ", "Equatorial Guinea"},
  {"ER", "Eritrea"},
  {"EE", "Estonia"},
  {"ET", "Ethiopia"},
  {"FK", "Falkland Islands"},
  {"FO", "Faroe Islands"},
  {"FJ", "Fiji"},
  {"FI", "Finland"},
  {"FR", "France"},
  {"GF", "French Guiana"},
  {"PF", "French Polynesia"},
  {"TF", "French Southern & Antarctic Lands"},
  {"GA", "Gabon"},
  {"GM", "Gambia"},
  {"GE", "Georgia"},
  {"DE", "Germany"},
  {"GH", "Ghana"},
  {"GI", "Gibraltar"},
  {"GR", "Greece"},
  {"GL", "Greenland"},
  {"GD", "Grenada"},
  {"GP", "Guadeloupe"},
  {"GU", "Guam"},
  {"GT", "Guatemala"},
  {"GG", "Guernsey"},
  {"GN", "Guinea"},
  {"GW", "Guinea-Bissau"},
  {"GY", "Guyana"},
  {"HT", "Haiti"},
  {"HM", "Heard Island & McDonald Islands"},
  {"HN", "Honduras"},
  {"HK", "Hong Kong"},
  {"HU", "Hungary"},
  {"IS", "Iceland"},
  {"IN", "India"},
  {"ID", "Indonesia"},
  {"IR", "Iran"},
  {"IQ", "Iraq"},
  {"IE", "Ireland"},
  {"IM", "Isle of Man"},
  {"IL", "Israel"},
  {"IT", "Italy"},
  {"JM", "Jamaica"},
  {"JP", "Japan"},
  {"JE", "Jersey"},
  {"JO", "Jordan"},
  {"KZ", "Kazakhstan"},
  {"KE", "Kenya"},
  {"KI", "Kiribati"},
  {"KP", "Korea (North)"},
  {"KR", "Korea (South)"},
  {"KW", "Kuwait"},
  {"KG", "Kyrgyzstan"},
  {"LA", "Laos"},
  {"LV", "Latvia"},
  {"LB", "Lebanon"},
  {"LS", "Lesotho"},
  {"LR", "Liberia"},
  {"LY", "Libya"},
  {"LI", "Liechtenstein"},
  {"LT", "Lithuania"},
  {"LU", "Luxembourg"},
  {"MO", "Macau"},
  {"MK", "Macedonia"},
  {"MG", "Madagascar"},
  {"MW", "Malawi"},
  {"MY", "Malaysia"},
  {"MV", "Maldives"},
  {"ML", "Mali"},
  {"MT", "Malta"},
  {"MH", "Marshall Islands"},
  {"MQ", "Martinique"},
  {"MR", "Mauritania"},
  {"MU", "Mauritius"},
  {"YT", "Mayotte"},
  {"MX", "Mexico"},
  {"FM", "Micronesia"},
  {"MD", "Moldova"},
  {"MC", "Monaco"},
  {"MN", "Mongolia"},
  {"ME", "Montenegro"},
  {"MS", "Montserrat"},
  {"MA", "Morocco"},
  {"MZ", "Mozambique"},
  {"MM", "Myanmar (Burma)"},
  {"NA", "Namibia"},
  {"NR", "Nauru"},
  {"NP", "Nepal"},
  {"NL", "Netherlands"},
  {"NC", "New Caledonia"},
  {"NZ", "New Zealand"},
  {"NI", "Nicaragua"},
  {"NE", "Niger"},
  {"NG", "Nigeria"},
  {"NU", "Niue"},
  {"NF", "Norfolk Island"},
  {"MP", "Northern Mariana Islands"},
  {"NO", "Norway"},
  {"OM", "Oman"},
  {"PK", "Pakistan"},
  {"PW", "Palau"},
  {"PS", "Palestine"},
  {"PA", "Panama"},
  {"PG", "Papua New Guinea"},
  {"PY", "Paraguay"},
  {"PE", "Peru"},
  {"PH", "Philippines"},
  {"PN", "Pitcairn"},
  {"PL", "Poland"},
  {"PT", "Portugal"},
  {"PR", "Puerto Rico"},
  {"QA", "Qatar"},
  {"RE", "Reunion"},
  {"RO", "Romania"},
  {"RU", "Russia"},
  {"RW", "Rwanda"},
  {"AS", "Samoa (American)"},
  {"WS", "Samoa (western)"},
  {"SM", "San Marino"},
  {"ST", "Sao Tome & Principe"},
  {"SA", "Saudi Arabia"},
  {"SN", "Senegal"},
  {"RS", "Serbia"},
  {"SC", "Seychelles"},
  {"SL", "Sierra Leone"},
  {"SG", "Singapore"},
  {"SX", "Sint Maarten"},
  {"SK", "Slovakia"},
  {"SI", "Slovenia"},
  {"SB", "Solomon Islands"},
  {"SO", "Somalia"},
  {"ZA", "South Africa"},
  {"GS", "South Georgia & the South Sandwich Islands"},
  {"SS", "South Sudan"},
  {"ES", "Spain"},
  {"LK", "Sri Lanka"},
  {"BL", "St Barthelemy"},
  {"SH", "St Helena"},
  {"KN", "St Kitts & Nevis"},
  {"LC", "St Lucia"},
  {"MF", "St Martin (French part)"},
  {"PM", "St Pierre & Miquelon"},
  {"VC", "St Vincent"},
  {"SD", "Sudan"},
  {"SR", "Suriname"},
  {"SJ", "Svalbard & Jan Mayen"},
  {"SZ", "Swaziland"},
  {"SE", "Sweden"},
  {"CH", "Switzerland"},
  {"SY", "Syria"},
  {"TW", "Taiwan"},
  {"TJ", "Tajikistan"},
  {"TZ", "Tanzania"},
  {"TH", "Thailand"},
  {"TG", "Togo"},
  {"TK", "Tokelau"},
  {"TO", "Tonga"},
  {"TT", "Trinidad & Tobago"},
  {"TN", "Tunisia"},
  {"TR", "Turkey"},
  {"TM", "Turkmenistan"},
  {"TC", "Turks & Caicos Is"},
  {"TV", "Tuvalu"},
  {"UM", "US minor outlying islands"},
  {"UG", "Uganda"},
  {"UA", "Ukraine"},
  {"AE", "United Arab Emirates"},
  {"US", "United States"},
  {"UY", "Uruguay"},
  {"UZ", "Uzbekistan"},
  {"VU", "Vanuatu"},
  {"VA", "Vatican City"},
  {"VE", "Venezuela"},
  {"VN", "Vietnam"},
  {"VG", "Virgin Islands (UK)"},
  {"VI", "Virgin Islands (US)"},
  {"WF", "Wallis & Futuna"},
  {"EH", "Western Sahara"},
  {"YE", "Yemen"},
  {"ZM", "Zambia"},
  {"ZW", "Zimbabwe"}
};
#endif
