name: Comment trigger

on:
  issue_comment:
    types: [created, edited]

jobs:
  run_shell:
    name: run shell test on CircleCI
    if: |
      github.event.issue.pull_request && 
      github.event.comment.body == '/run shell'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Shell Test
        env:
          CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
        run: |
          curl -u "${{ secrets.CIRCLECI_TOKEN }}:" \
          -X POST \
          --header "Content-Type: application/json" \
          -d '{
                "branch": "'"${{ github.event.pull_request.head.ref }}"'",
                "parameters": {
                  "run_shell_test": true
                }
              }' \
          https://circleci.com/api/v2/project/gh/tw-kang/cubrid/pipeline
