name: Comment trigger

on:
  issue_comment:
    types: [created, edited]

jobs:
  run_shell:
    name: run shell test on CircleCI
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Run CircleCI Shell Test
        env:
          CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
        run: echo "/run test"
